## Connection

MPX NYC participants were deeply connected to queer and trans communities in New York City (see @tbl-connection). About two-thirds reported being in recent (preceding 4 weeks) contact with 1 - 10 queer or trans friends. Only 20% reported not being in contact. About half of the participants had between 1 and 3 recent serial sex partnerships with one fifth reporting four or more partners. About one third of participants reported spending 16-30 minutes when traveling to a hookup while a third spent more than 30 minutes. Almost one in four participants reported having recent physical (non-sexual) contact with 2 or more individuals at the same time, and one third reported having had no contact. 

Among all MPX NYC participants, 40% (530) reported reported having had sex or physical contact with two or more people at the same time. These participants identified $604$ venues at which they had contact. These contact venues are examined in the next section.




```{r}
#| tbl-cap: Participants in MPX NYC Study by Sex / Physical Contact in Congregate Setting in past 4 weeks
#| label: tbl-connection


make_tabledata_connection() |>
  draw_table_by_groupSex()


```