

```{r }
#| fig-cap: !expr 'get_figure_details("fig-sexorientation-racegender")'
#| label: fig-racegender-radar-grid
#| fig-width: 8
#| fig-height: 16


make_plotdata_racegender_radar_grid() |>
  plot_radar_grid() +
  ggplot2::scale_y_continuous(breaks = c(0,0.25, 0.50, 1), limits = c(-0.5, 1)) +
  scale_fill_mpxnyc(name = "") +
  theme_mpxnyc_radar_people() 




```

Participants who reported recent physical or sexual contact in a group setting (group contact) were slightly younger than those who did not. They were more likely to identify as gay and less likely to identify as straight. Surprisingly, they were less likely to have been recruited through a Grindr advertisement and more likely to have been recruited before the first Grindr pop-up advertisement on 30 August 2022.

These participants did not differ from the rest in terms of HIV status or HIV viral suppression, but they were more likely to have at least one STI symptom, and showed higher utilization of PrEP, mpox testing, and mpox vaccine. They were more closely connected with the queer and trans community, reporting more contact with friends, more physical contact partners and more sexual contact partners. They spent more time travelling to hookups than participants who had not had recent contact in a group setting.
