## Spatial patterns


@fig-movement-matrix maps each contact venue's community district (x-axis) against the participant's home community district (y-axis). The size of the dot is proportional to the total count of contact venues with the given home and contact venue community district. The color of the dot represents the borough of the contact venue.

The dots on the diagonal line from top left to bottom right, show prominently, indicating that a sizeable proportion of movement happens within community districts. The figure also shows four prominent clusters - the cluster at the top left (in pink) shows significant movement between home and contact venues within Brooklyn and the cluster towards the middle of the plot (in purple) shows significant movement within Manhattan. The clusters at the top center and bottom left show significant movement from Brooklyn to Manhattan and from Manhattan to Brooklyn, respectively.



```{r }
#| fig-cap: !expr 'get_figure_details("fig-communities-movement")'
#| label: fig-movement-matrix
#| fig-width: 9
#| fig-height: 11.5

make_plotdata_movement_matrix() |>
  plot_matrix_movement() +
  scale_fill_mpxnyc(name = "From Borough", option = "dark") +
  scale_color_mpxnyc(name = "To Borough", option = "dark") +
  ggplot2::scale_size_continuous(name = "Count") +
  theme_mpxnyc_matrix_movement() 

```

