# Mixing {#sec-mixing}


```{r}
# Access custom defined functions
targets::tar_source("../R_functions")


```





{{< include fig-racegender-mixing-matrix.qmd >}}




Patterns of mixing reveal how social worlds overlapped—and where they stayed distinct—within queer and trans New York. Using spatial selection coefficients, we measured the degree to which participants who shared certain characteristics (such as race, gender, sexual orientation, or age) tended to live or play in the same neighborhoods.








Across all categories, participants showed **spatial homophily**—people were more likely to live or go out in community districts where others shared their demographic traits. Yet the pattern was not uniform. **Black cisgender men** and **non-binary participants** tended to visit or reside in different neighborhoods than **white cisgender men**, indicating parallel but distinct social geographies. **Non-binary people** also showed spatial proximity to **transgender men**, suggesting overlapping community spaces.  

{{< include fig-sexorientation-mixing-matrix.qmd >}}


When stratified by sexual orientation, **gay-identified participants** clustered in neighborhoods where **bisexual, straight, and queer-identified** participants were less present—and those groups, in turn, were less present in gay-leaning clusters of neighborhoods. These mirrored preferences underscore how social identity, geography, and nightlife intertwine to shape opportunity for connection—and risk for infection.


{{< include fig-age-mixing-matrix.qmd >}}



{{< include plot-icon-3.qmd >}}

