## Spatial efficiency

```{r}
#| fig-cap: !expr 'get_figure_details("fig-hiimpact-communities")'
#| label: 'fig-hiimpact-communities-bar'
#| fig-width: 9
#| fig-height: 7


make_plotdata_coverage_approach_bar() |>
  plot_coverage_bar() +
  scale_fill_mpxnyc(name = "", na.translate = FALSE, option = "light")  +
  theme_mpxnyc_blank() +
  ggplot2::theme(legend.position = "bottom") 

```

@fig-hiimpact-communities shows which community districts would have to be immunized to immunize 33% of the population (Group A), and 66% of the population (Group A + Group B) under both the contact-neutralizing and movement-neutralizing intervention strategies.

Under the contact-neutralizing strategy, it would take five community districts to immunize 33% of the population. These are MN04, BK01, MN10, BK03, and QN01. To reach 66% of participants with the intervention, it would be necessary to immunize 13 community districts. The additional community districts would be MN12, BK04, MN02, BK08, MN07, MN09, BK02, and MN05.

Under the movement-neutralizing strategy, it would take six community districts to reach 33% of the population: MN04, BK01, MN05, BK04, MN02, and BK03. It would take 16 community districts to reach 66% of the population. The additional community districts would be: MN64, MN10, QN01, BK08, MN09, QN05, BK09, MN11, BK14, and BK07.


