## Network impact

@fig-netimpact shows that nearly 100% of individuals are included in the largest connected component before any intervention. For the movement-neutralizing strategy, the proportion of the population included in the largest connected component declines more sharply than for the contact-neutralizing strategy as more community districts are immunized. In the contact-neutralizing strategy, the overall proportion of unvaccinated individuals declines more sharply than in the movement-neutralizing strategy. There is not a noticeable difference between the two strategies for the first 10 community districts to be immunized - differences between the two strategies start emerging once 10 community districts are immunized.


```{r }
#| fig-cap: !expr 'get_figure_details("fig-netimpact")'
#| label: fig-netimpact
#| fig-width: 9
#| fig-height: 6.5

make_plotdata_net_impact_profile() |>
  plot_centrality_bar() +
  scale_fill_mpxnyc(name = "", option = "light") +
  ggplot2::scale_y_continuous("Proportion of participants", limits = c(-0.2, 1), labels = scales::percent) +
  ggplot2::scale_x_continuous("Intervention order", limits = c(0, 40), breaks = c(0, 10, 20, 30, 40)) +
  theme_mpxnyc_netimpact() 
  


```

