
### Notation

Define $\psi(i,j)$ as the adjacency function for the person-place graph. For person $i$ and community $j$:



$$
\psi(i,j) = \begin{cases} 1 &i\sim j \\ 0 &\text{otherwise} \end{cases}
$$

Define $\psi_P(i,k)$ as the adjacency functon for the person graph. For persons $i$ and $k$:


$$
\psi_P(i,k) = \sum_{j \in N_C}{\psi(i,j) \psi(k,j)}
$$

Define $\psi_C(j,l)$ as the adjacency functon for the place graph. For places $j$ and $l$:


$$
\psi_C(j,l) = \sum_{i \in N_P}{\psi(i,j) \psi(i,l)}
$$

In a given network, a connected component is a subset of nodes such that each node in the subset is reachable from any other node in the subset, and such that there are no nodes outside the subset which are reachable from a node inside it. By reachable, we mean possible to reach by tracing a path from one node to another over existing network ties.

In the MPX NYC participant network, it is possible to uniquely partition the node set $N_p$ into connected components. This follows from the facts that connected components form non-overlapping subsets of $N_p$ and that it is possible to write $N_p$ as a union of subsets $C_k$ which are each connected components.

$$
N = \bigcup_{k = 1}^{K}{C_k}
$$


### Node characteristics




**Conditional participant social reach** is defined as weighted node degree in the MPX NYC participant network. For participant $i \in N_p$

$$
R_{i\rightarrow A} = \sum_{j \in N_p \\ j \in A}{\psi_p (i,j)}
$$






**Conditional community district social reach** is defined as the number of connections the focal community district has with participants. It is defined as the weighted node degree in the MPX NYC spatial participant network. For $j \in N_c$:

$$
r_{j\rightarrow A} = \sum_{i \in N_p \\ j \in A}{\psi (i, j)}
$$




When $A=\mathscr{N}_p$, these measures are called participant social reach, and community district social reach. They are denoted $R_i$, and $r_j$, respectively