### Assumptions, revisited

Typically, there are three assumptions whihc are usually said to be necessary conditions for valid causal inferences: conditional exchangeability,

$$
Y_i^{(a)} \perp A_i | L_i
$$
consistency, 

$$
E[Y_i^{(a)} | L_i = l_i, A_i = a] =  E[Y_i | L_i = l_i, A_i = a]
$$
and positivity


$$
0 < E[A_i | L_i] < 1
$$

Conditional exchangeability is a consequence of the independence of errors in the NPSEM-IE. Consistency is a consequence of the fact that a) the structural equations for the observed model are identical with the equations for the counterfactual model, b) the error terms for each individual $i$ are equal when they appear in the counterfactual model as they are in the observed model. i.e. $U_{Y_i}$ has the same value in @eq-independence-swig as it does in @eq-independence-dag. Unlike the first two, the assumption of positivity is not given by the definition of the NPSEM. We make it in defining the structural equation models for counterfactual variables (@eq-independence-swig).


