### Structural equation models {.unnumbered}

A non-parametric structural equation model with independent errors is a system of equations that relates all the entries in a given vector-valued random variable to each other. It does so without specifying parametric functions for each equation in the system. An example of such a model is shown by @eq-fullly-connected-dag. In this set of equations, values that are produced by equations higher up in the list serve as inputs to equations lower down on the list. The functions $f_*$ are deterministic, though their form is not necessarily known. The arguments $U_*$ represent error terms -- random variables that are independent of each other within and across observational units.

NPSEMs are used to represent two types of distributions in causal inference: the probability distribution of observed data, and the hypothetical (counterfactual) probability distribution of the data if the experiment had manipulated one or more variables in the model. The former distribution is modeled using the observed data model and the latter is modeled using the counterfactual data model. @eq-fullly-connected-dag shows the observed model for our example, and @eq-fullly-connected-swig shows the counterfactual model under an intervention setting $A_1$ to $a_1$, $A_2$ to $a_2$, and $A_3$ to $a_3$. Notice how in @eq-fullly-connected-swig, the values set under the intervention supercede the values that would have been generated had the experimenter not intervened. The former values are used in subsequent equations in the model whereas the latter values are not. 



**Observed data model**

$$
\begin{aligned}
L_1 &= f_{L_1}(U_{L_1}) \\
L_2 &= f_{L_2}(U_{L_2}, L_1) \\
L_3 &= f_{L_3}(U_{L_3}, L_1, L_2 ) \\
A_1 &= f_{A_1}(U_{A_1}, L_1, L_2, L_3) \\
A_2 &= f_{A_2}(U_{A_2}, L_1, L_2, L_3, A_1) \\
A_3 &= f_{A_3}(U_{A_3}, L_1, L_2, L_3, A_1, A_2) \\
Y_1 &= f_{Y_1}(U_{Y_1}, L_1, L_2, L_3, A_1, A_2, A_3) \\
Y_2 &= f_{Y_2}(U_{Y_2}, L_1, L_2, L_3, A_1, A_2, A_3, Y_1) \\
Y_3 &= f_{Y_3}(U_{Y_3}, L_1, L_2, L_3, A_1, A_2, A_3, Y_1, Y_2) \\
\end{aligned}
$$ {#eq-fullly-connected-dag}


**Counterfactual data model**


$$
\begin{aligned}
L_1 &= f_{L_1}(U_{L_1}) \\
L_2 &= f_{L_2}(U_{L_2}, L_1) \\
L_3 &= f_{L_3}(U_{L_3}, L_1, L_2 ) \\
A_1 &= f_{A_1}(U_{A_1}, L_1, L_2, L_3) \\
A_2^{(a_1)} &= f_{A_2}(U_{A_2}, L_1, L_2, L_3, a_1) \\
A_3^{(a_1, a_2)} &= f_{A_3}(U_{A_3}, L_1, L_2, L_3, a_1, a_2) \\
Y_1^{(a_1, a_2, a_3)} &= f_{Y_1}(U_{Y_1}, L_1, L_2, L_3, a_1, a_2, a_3) \\
Y_2^{(a_1, a_2, a_3)} &= f_{Y_2}(U_{Y_2}, L_1, L_2, L_3, a_1, a_2, a_3, Y_1^{(a_1, a_2, a_3)}) \\
Y_3^{(a_1, a_2, a_3)} &= f_{Y_3}(U_{Y_3}, L_1, L_2, L_3, a_1, a_2, a_3, Y_1^{(a_1, a_2, a_3)}, Y_2^{(a_1, a_2, a_3)}   ) \\
\end{aligned}
$$ {#eq-fullly-connected-swig}


```{r }
#| fig-align: center
#| label: fig-fullly-connected-swig
#| fig-cap: "Fully connected SWIG"

make_swig("full_interference")      |> 
    plot_swig(node_radius = 0.2) + 
    scale_fill_mpxnyc(option = "light") +
    theme_mpxnyc_blank()

```


### Model restrictions {.unnumbered}

Whereas parametric models are characterized by their probability density functions, non-parametric models of this type are usually characterized by their conditional independencies. These can be represented using DAGs, as we described in the previous section. DAGs take on another meaning when used with NPSEMs -- a DAG is a schematic representation of the structural equations in an NPSEM below. The DAG shown in @fig-fullly-connected-dag, for instance, represents the model specified by @eq-fullly-connected-dag. 


To fully characterize the NPSEM specified in @eq-fullly-connected-dag using observed data, we would need to estimate 9 functions using one observation of the 9-dimensional joint distribution that gave rise to the participants' observations. Recruiting an additional person to the study would not ease this problem; it would add three new equations to the model and we would end up with a similar problem than the one we began with. We would have to estimate 12 functions using one observation of a 12-dimensional joint distribution.

In practice, we simplify this system of equations by making assumptions that leave us with fewer functions to estimate and more observations per function. These assumptions are called model restrictions because they restrict the set of distributions that could possibly be represented by the NPSEM.

For instance, if we add the restriction that all the measures are independent (or equivalently, that the DAG has no arrows), the resulting model would not be able to represent data from a causal system where some of the measures are correlated. By adding the restriction of independence, we would be eliminating the correlated data distribution from consideration as a possibility for how the data we are modelling are truly distributed. 



