

### Example 1: Dress and Jobs {.unnumbered}

We are interested in settling an argument among friends about the relationship between dressing in formal wear and job offers. One friend thinks that dressing formally brings more job offers; everyone she knows who dresses formally has many more job offers than those who dress casually. 

The other friend thinks that what really brings job offers is currently having a job. In their reasoning, having a job causes people to dress formally and also causes people to receive job offers, but dressing formally does not in itself improve a person's likelihood of receiving job offers. We conduct a study to investigate.

We recruit three people, *Person 1*, *Person 2*, and *Person 3*. *Person 1* and *Person 2* are married to each other. *Person 1* and *Person 3* are newly acquainted colleagues. Say *Person 1* has job status $L_1$, *Person 2* has job status $L_2$ and *Person 3* has job status $L_3$. Each of these variables can only take on two values: "employed vs. unemployed". Similarly we define $A_i$ as *Person $i$'s* dress (formal vs. informal), and $Y_i$ as their job offers (many vs. few). The job status measurement ($L_i$) precedes dress ($A_i$) in time, and dress precedes job offers ($Y_i$).

In the next few sections, we will use this example to discuss model restrictions under classical causal inference. 
