

### Assumptions {#sec-assumptions-classic}

Under classic causal inference, we assume that observations are independent and identically distributed. We review these assumptions, naming them slightly differently for the purpose of comparing them with the assumptions made in subsequent sections. In each case, we divide assumptions up into *independence assumptions* (assumptions that delete arrows from the DAG) and *homogeneity assumptions* (assumptions that equate structural equations with each other).

#### Independence

##### No spillover

Under classic causal inference, we make the assumption of no spillover - that measurements taken across participants at the same time (e.g. $L_1$, $L_2$, and $L_3$) are independent of each other given all prior measures. i.e.


$$
\begin{aligned}
L_1 \perp L_2 \\
L_2 \perp L_3 \\
L_1 \perp L_3 
\end{aligned}
$$


$$
\begin{aligned}
A_1 \perp A_2 | L_1, L_2, L_3\\
A_2 \perp A_3 | L_1, L_2, L_3 \\
A_1 \perp A_3 | L_1, L_2, L_3 
\end{aligned}
$$


$$
\begin{aligned}
Y_1 \perp Y_2 | L_1, L_2, L_3, A_1, A_2, A_3\\
Y_2 \perp Y_3 | L_1, L_2, L_3, A_1, A_2, A_3 \\
Y_1 \perp Y_3 | L_1, L_2, L_3, A_1, A_2, A_3 
\end{aligned}
$$

This is shown in @fig-no-spillover-dag, as the removal of arrows that connected the $L_i$'s, $A_i$'s and $Y_i$'s. In @eq-no-spillover-dag, the $L_i$'s are not functions of each other, the $A_i$'s are not functions of each other, and the $Y_i$'s are not functions of each other. This implies that given all the measurements taken prior to a set of contemporaneous measures, the contemporaneous measures are independent. This follows from the independence of the error terms $U_{L_i}$, the error terms $U_{A_i}$, and the terms $U_{Y_i}$ across observations $i$.

```{r}
#| fig-height: 6
#| fig-width: 6.5
#| fig-align: center
#| label: fig-no-spillover-dag
#| fig-cap: "Causal DAG with no spillover"


make_dag("full_interference")      |> 
  plot_swig(node_radius = 0.2) + 
  scale_fill_mpxnyc(labels = c("h"), option = "light") +
  theme_mpxnyc_blank()


```

$$
\begin{aligned}
L_1 &= f_{L_1}(U_{L_1}) \\
L_2 &= f_{L_2}(U_{L_2}) \\
L_3 &= f_{L_3}(U_{L_3} ) \\
A_1 &= f_{A_1}(U_{A_1}, L_1, L_2, L_3) \\
A_2 &= f_{A_2}(U_{A_2}, L_1, L_2, L_3) \\
A_3 &= f_{A_3}(U_{A_3}, L_1, L_2, L_3) \\
Y_1 &= f_{Y_1}(U_{Y_1}, L_1, L_2, L_3, A_1, A_2, A_3) \\
Y_2 &= f_{Y_2}(U_{Y_2}, L_1, L_2, L_3, A_1, A_2, A_3) \\
Y_3 &= f_{Y_3}(U_{Y_3}, L_1, L_2, L_3, A_1, A_2, A_3) \\
\end{aligned}
$$ {#eq-no-spillover-dag}

##### No interference

Classic causal inference makes the no interference assumption. We assume that measurements made across participants, but not at the same time are independent of each other. This is shown as the absence of arrows that connect $L_i$'s to $A_j$'s, $L_i$'s to $Y_j$'s and $A_i$'s to $Y_j$ for participants $i,j$ with $i \neq j$. (See @fig-independence-dag)

This allows us to simplify the structural equation model so that each participants measures are a function of only measures taken on them.

$$
\begin{aligned}
L_1 &= f_{L_1}( U_{L_1}) \\
L_2 &= f_{L_2}( U_{L_2}) \\
L_3 &= f_{L_3}( U_{L_3}) \\
A_1 &= f_{A_1}( U_{A_1}, L_1) \\
A_2 &= f_{A_2}( U_{A_2}, L_2) \\
A_3 &= f_{A_3}( U_{A_3}, L_3) \\
Y_1 &= f_{Y_1}( U_{Y_1}, L_1, A_1 ) \\
Y_2 &= f_{Y_2}( U_{Y_2}, L_2, A_2 ) \\
Y_3 &= f_{Y_3}( U_{Y_3}, L_3, A_3 ) \\
\end{aligned}
$$

#### Homogeneity

##### Identical distribution

Finally, we see above that the functions that generate observations $L_i$ are similar in structure to each other, as are the the functions that generate $A_i$'s and $Y_i$s. We make the homogeneity assumption that the functions are identical to each other. 

$$
\begin{aligned}
 f_L &= f_{L_1} = f_{L_2} = f_{L_3} \\
 f_A &= f_{A_1} = f_{A_2} = f_{A_3} \\
 f_Y &= f_{Y_1} = f_{Y_2} = f_{Y_3}  \\
\end{aligned}
$$
