

#### Counterfactual data

We define counterfactual outcomes $Y_1^{(a_1, \mathbf{a}_{\mathscr{N}_1})}$, $Y_2^{(a_2, \mathbf{a}_{\mathscr{N}_2})}$, and $Y_3^{(a_3, \mathbf{a}_{\mathscr{N}_3})}$, which represent the level of job opportunities, *Persons 1*, *2*, and *3*, would have if we set their dress to level $a_1$, $a_2$, and $a_3$, respectively. Then the model for counterfactual variable is given by @eq-homogenous-interference-swig. It is represented using a SWIG in @fig-homogenous-interference-swig.

Note that because of the assumption of network interference, the counterfactual outcome for *Person 1* is a function of *Person 2*'s treatment value and vice versa. The counterfactual outcome for *Person 3*, on the other hand, is a function of *Person 3*'s treatment ($a_3$) alone. This is because $\mathscr{N}_1 = \{2\}$, $\mathscr{N}_2 = \{1\}$, and $\mathscr{N}_3 = \{\}$, according to Example 2.

To ensure that counterfactual outcomes are well-defined for all experimental units, we make the assumption of positivity:

$$
0 < P[A_i = a_i,  h_Y (\mathbf{A}, \Psi_i) =  h_Y(\mathbf{a}, \Psi_i)| L_i,g_{A}(\mathbf{L}, \Psi_i) ] < 1
$$
for all $\mathbf{a} \in \{0,1\}^n$

```{r}
#| fig-height: 8
#| label: fig-homogenous-interference-swig
#| fig-width: 7
#| fig-cap: "SWIG with homogenous"
make_swig("homogenous_interference")      |> 
  plot_swig(node_radius = 0.2) + 
  scale_fill_mpxnyc(option = "light") +
  theme_mpxnyc_blank()

```

$$
\begin{aligned}
L_i &= f_{L}(  U_{L_i}  ) \\
A_i &= f_{A}( U_{A_i}, L_i, g_{A}(\textbf{L}, \Psi_i) ) \\
Y_i^{(a_i,\textbf{a}_{\mathscr{N}_i} )} &= f_{Y}(U_{Y_i}, L_i,  a_i,  g_{Y}(\textbf{L}, \Psi_i),      h_{Y}(\textbf{a}, \Psi_i)         ) \\
\end{aligned} 
$$ {#eq-homogenous-interference-swig}
