

#### Observed data

@fig-homogenous-dag and @eq-homogenous-dag show the resulting NPSEM and DAG for our data. Because of the assumption of identical distributions, we can represent the model using three equations rather than nine. We retain the person subscript on the random variables in @eq-homogenous-dag and we keep all nine nodes in the DAG on @fig-homogenous-dag and add six additional nodes to represent network exposure values with respect to $\mathbf{A}$ and $\mathbf{L}$. 

We draw the DAG like this to clarify that though our model is for one person, it represents a part of a system that relates all the people in the sample with each other. Our original purpose, after all, was to infer something about the sample, not any one individual in it.

```{r}
#| fig-height: 8
#| fig-width: 7
#| fig-align: center
#| label: fig-homogenous-dag
#| fig-cap: "Causal DAG with homogenous structure"


make_dag("homogenous_interference")            |> 
  plot_swig(node_radius = 0.2) + 
  scale_fill_mpxnyc(option = "light") +
  theme_mpxnyc_blank()




```

We can re-write the structural equation model like this:

$$
\begin{aligned}
L_i &= f_{L}( U_{L_i} ) \\
A_i &= f_{A}( U_{A_i}, L_i, g_{A}(\textbf{L}, \Psi_i) ) \\
Y_i &= f_{Y}( U_{Y_i},  L_i,  g_{Y}(\textbf{L}, \Psi_i),   A_i,  h_{Y}( \textbf{A}, \Psi_i ) ) \\
\end{aligned}
$$ {#eq-homogenous-dag}



