### Assumptions

#### Independence assumptions

##### No spillover

Under network causal inference, we make the assumption of no spillover - that measurements taken across participants at the same time (e.g. $L_1$, $L_2$, and $L_3$) are independent of each other given all prior measures.

This is shown in @fig-interference-dag, as the removal of arrows that connected the $L_i$'s, $A_i$'s and $Y_i$'s in @fig-fullly-connected-dag. In @eq-interference-dag, the $L_i$'s are not functions of each other, the $A_i$'s are not functions of each other, and the $Y_i$'s are not functions of each other. This implies that given all the measurements taken prior to a set of contemporaneous measures, the contemporaneous measures are independent.

##### Network interference

```{r}
#| fig-height: 6
#| fig-width: 6.5
#| fig-align: center
#| label: fig-interference-dag
#| fig-cap: "Causal DAG with network interference"

make_dag("network_interference")   |> 
  plot_swig(node_radius = 0.2) + 
  scale_fill_mpxnyc(option = "light") +
  theme_mpxnyc_blank()


```

$$
\begin{aligned}
L_1 &= f_{L_1}(U_{L_1}) \\
L_2 &= f_{L_2}(U_{L_2}) \\
L_3 &= f_{L_3}(U_{L_3} ) \\
A_1 &= f_{A_1}(U_{A_1}, L_1, L_2) \\
A_2 &= f_{A_2}(U_{A_2}, L_1, L_2) \\
A_3 &= f_{A_3}(U_{A_3}, L_3) \\
Y_1 &= f_{Y_1}(U_{Y_1}, L_1, L_2, A_1, A_2) \\
Y_2 &= f_{Y_2}(U_{Y_2}, L_1, L_2, A_1, A_2) \\
Y_3 &= f_{Y_3}(U_{Y_3}, L_3,  A_3) \\
\end{aligned}
$$ {#eq-interference-dag}

Under network causal inference, we make the assumption that interference respects some mapping between individuals - a mapping given by a graph. In @fig-interference-dag, based on their relationships with one another, *Person 1*'s measures are connected with *Person 2*'s, and neither are connected with *Person 3*. See Aronow and Samii [-@aronow2017]. 

Saying a structural equation model or a DAG shows network interference is equivalent to saying the exposure mapping for each variable in the DAG is loyal to graph $\mathscr{G}$ which encodes the causally relevant relationships between observational units in the sample. In this example 

$$
\mathscr{G}(\{\text{Person 1, Person 2, Person 3}\}, \{\text{Person 1} \sim \text{Person 2}\})
$$

#### Homogeneity assumptions

##### Homogenous interference

###### Separability

We assume that the exposure mapping for each variable in the structural model is separable. i.e. We define $g_{A_i}$, $h_{Y_i}$, and $g_{Y_i}$ as network exposure mappings for $A_i$ with respect to $\mathbf{L}$, for $Y_i$ with respect to $\mathbf{A}$, and for $Y_i$ with respect to $\mathbf{L}$. Seperability allows us to write the model as follows:

$$
\begin{aligned}
L_1 &= f_{L_1}(U_{L_1}) \\
L_2 &= f_{L_2}(U_{L_2}) \\
L_3 &= f_{L_3}(U_{L_3} ) \\
A_1 &= f_{A_1}(U_{A_1}, L_1, g_{A_1}(\mathbf{L}, \{2\})) \\
A_2 &= f_{A_2}(U_{A_2}, L_2, g_{A_2}(\mathbf{L}, \{1\})) \\
A_3 &= f_{A_3}(U_{A_3}, L_3, g_{A_3}(\mathbf{L}, \{\})) \\
Y_1 &= f_{Y_1}(U_{Y_1}, L_1, A_1, g_{Y_1}(\mathbf{L}, \{2\}), h_{Y_1}(\mathbf{A}, \{2\})) \\
Y_2 &= f_{Y_2}(U_{Y_2}, L_2, A_2, g_{Y_2}(\mathbf{L}, \{1\}), h_{Y_2}(\mathbf{A}, \{1\})) \\
Y_3 &= f_{Y_3}(U_{Y_3}, L_3,A_3,  g_{Y_2}(\mathbf{L}, \{\} ), h_{Y_2}(\mathbf{A}, \{\})) \\
\end{aligned}
$$


###### Positional invariance

We assume that the value of a network exposure mapping is invariant to its position in the network. This allows us to drop the person subscript on the network exposure mappings. 

$$
\begin{aligned}
L_1 &= f_{L_1}(U_{L_1}) \\
L_2 &= f_{L_2}(U_{L_2}) \\
L_3 &= f_{L_3}(U_{L_3} ) \\
A_1 &= f_{A_1}(U_{A_1}, L_1, g_{A}(\mathbf{L}, \{2\})) \\
A_2 &= f_{A_2}(U_{A_2}, L_2, g_{A}(\mathbf{L}, \{1\})) \\
A_3 &= f_{A_3}(U_{A_3}, L_3, g_{A}(\mathbf{L}, \{\})) \\
Y_1 &= f_{Y_1}(U_{Y_1}, L_1, A_1, g_{Y}(\mathbf{L}, \{2\}), h_{Y}(\mathbf{A}, \{2\})) \\
Y_2 &= f_{Y_2}(U_{Y_2}, L_2, A_2, g_{Y}(\mathbf{L}, \{1\}), h_{Y}(\mathbf{A}, \{1\})) \\
Y_3 &= f_{Y_3}(U_{Y_3}, L_3, A_3, g_{Y}(\mathbf{L}, \{\} ), h_{Y}(\mathbf{A}, \{\})) \\
\end{aligned}
$$

###### Symmetry 

Since *Person 1* and *Person 2* each have one network exposure unit each, and since *Person 3* does not have any network exposure units, the assumption of symmetry does not make a difference in this example. It would be that the order of entries related to network exposure units does not matter for calculating the network exposure value. Permuting those entries does not change that value. 



###### Boundedness 

If we assume that the only relevant relationships for the causal structure related to employment, formal dress, and job offers are marriages, the assumption of boundedness holds. Each node in this graph will have either a single network exposure unit, or none at all, even if the graph grows arbitrarily large. 

##### Identical distribution

We assume that the structural equations that produce indivdual measures are identical accross individuals. Hence we can drop the person subscript from the structural equations. 

$$
\begin{aligned}
L_1 &= f_{L}(U_{L_1}) \\
L_2 &= f_{L}(U_{L_2}) \\
L_3 &= f_{L}(U_{L_3} ) \\
A_1 &= f_{A}(U_{A_1}, L_1, g_{A}(\mathbf{L}, \{2\})) \\
A_2 &= f_{A}(U_{A_2}, L_2, g_{A}(\mathbf{L}, \{1\})) \\
A_3 &= f_{A}(U_{A_3}, L_3, g_{A}(\mathbf{L}, \{\})) \\
Y_1 &= f_{Y}(U_{Y_1}, L_1, A_1, g_{Y}(\mathbf{L}, \{2\}), h_{Y}(\mathbf{A}, \{2\})) \\
Y_2 &= f_{Y}(U_{Y_2}, L_2, A_2, g_{Y}(\mathbf{L}, \{1\}), h_{Y}(\mathbf{A}, \{1\})) \\
Y_3 &= f_{Y}(U_{Y_3}, L_3, A_3, g_{Y}(\mathbf{L}, \{\} ), h_{Y}(\mathbf{A}, \{\})) \\
\end{aligned}
$$

#### Identification

##### Positivity

We assume that for all $i$

$$
0 < P[A_i =1 | L_i,g_{A}(\mathbf{L}) ] < 1
$$

