
### Data graphs {.unnumbered}

We define the data graph $\mathscr{G}(\mathscr{N}, \psi, \Lambda)$ as an ordered triple whose first entry is a set containing $n$ nodes, each representing an observational unit in the study. The second entry is an adjacency function $\psi(i,j) \in \mathbf{R}^+_0$ which gives the weight between nodes $i$ and $j$. Weights are positive real numbers when the nodes are connected in $\mathscr{G}$ and zero otherwise. The third entry 

$$
\mathbf{\Lambda} = \mathbf{\Lambda}_N \cup \mathbf{\Lambda}_E
$$ 

is the data associated with the graph. The node data $\mathbf{\Lambda}_N$ is a set of $K+1$ vectors of length $n$. For each of these, the $i^{th}$ entry is a dichotomous variable relating to node $i$.

$$
\mathbf{\Lambda}_N = \{ \mathbf{Y}  \} \cup \{\mathbf{X}_t: t \in [1,K]\}
$$

The edge data $\mathbf{\Lambda}_E$ is a set of $Q$ vectors $\mathbf{Z}_t$ of length $m$. Each entry in each of these is associated with a distinct edge.

$$
\mathbf{\Lambda}_E =  \{\mathbf{Z}_t  : t \in [1,Q]\}
$$

The "network exposure units" for node $i$ is defined

$$
\mathscr{N_i} = \{j \in \mathscr{N}: \psi(i, j) > 0\}
$$ 


$\mathbf{W}_i$ is the "network weights" for node $i$. It is a vector of length $|\mathscr{N}_i|$ whose $j^{th}$ entry is $\psi(i,j)$.

$X_i$ is the $i^{th}$ entry of vector $\mathbf{X}$ and $\mathbf{X}_{\mathscr{N_i}}$ is the sub-vector of $\mathbf{X}$ which contains entries related to person $i$'s network exposure units. Where the original vector already has a subscript, we append onto that subscript $i$ and $\mathscr{N_i}$, respectively. For instance, $X_{ti}$ is the $i^{th}$ entry of $\mathbf{X}_t$ and $\mathbf{X}_{t\mathscr{N_i}}$ is the sub-vector relating to node $i$'s network exposure units. 


$\mathbf{M}$ is a permutation matrix -- a square matrix whose row and column margins all equal 1, and whose entries are either zero or one. Pre-multiplying a vector with a conformable permutation matrix permutes the order of the entries in the vector.
