

### Exposure mappings {.unnumbered}


Say we have a non-parametric structural equation model of $n$-dimensional random vectors $\mathbf{X}_t \in \{0,1\}^n$, $t \in [1,k]$, which precede random vector $\mathbf{Y}$. $f_{Y_i}$ is the structural equation for $Y_i$, and $U_{Y_i}$ the error term for that equation. We define the "exposure mapping for $Y_i$" as the function 

$$
g_i: \{0,1\}^{n\times k} \times\mathscr{N} \rightarrow \mathbf{R}^{2k}
$$ 

such that

$$
Y_i = f_{Y_i}(g_i(\mathbf{X}_1,  ..., \mathbf{X}_k, i), U_{Y_i})
$$





#### Definition 1: Loyalty

We say an exposure mapping $g_{i}$ is loyal to graph $\mathscr{G}$ if for any $\mathbf{X},\mathbf{X}' \in \mathbf{R}^n$


$$
\begin{equation}
\mathbf{X}_{\mathscr{N}_i} = \mathbf{X'}_{\mathscr{N}_i} \text{ and } X_i = X'_i\\
\implies \\
g_{i}(...,\mathbf{X}, ..., i) = g_{i}(..., \mathbf{X'}, ..., i) 
\end{equation}
$$


#### Definition 2: Separability

We say exposure mapping $g_i$ is separable if it can be re-written as the vector-valued function

$$
g_i(\mathbf{X}_{1}, ..., \mathbf{X}_{k}, i) = \begin{pmatrix} 
g_{0i}(\mathbf{X}_{1}, ..., \mathbf{X}_{k},  i)  \\ 
g_{1i}(\mathbf{X}_{1},  i) \\
... \\  
g_{ki}(\mathbf{X}_{k},  i) 
\end{pmatrix}
$$

Where for $g_{0i}$ is a vector-valued function and each $g_{ti}$ is a scalar-valued function.

$$
g_{0i}: \{0,1\}^{n\times k} \times\mathscr{N} \rightarrow \mathbf{R}^{k}
$$

$$
g_{ti}: \{0,1\}^{n} \times\mathscr{N} \rightarrow \mathbf{R}
$$


#### Definition 3: Symmetry

For some $t \in [1,K]$ and $i \in \mathscr{N}$, we say $g_{ti}$ is symmetric with respect to graph $\mathscr{G}$ if for any $\mathbf{X},\mathbf{X}' \in \mathbf{R}^n$ and permutation matrix $\mathbf{M}$ (conformable square matrix whose row and column margins all equal 1):


$$
\begin{equation}
\mathbf{X}_{\mathscr{N}_i} = \mathbf{M} \mathbf{X'}_{\mathscr{N}_i}  \\
\implies \\
g_{ti}(\mathbf{X}, i) = g_{ti}(\mathbf{X'}, i) 
\end{equation}
$$

If $g_{ti}$ is symmetric with respect to $\mathscr{G}$ we say it is a "network exposure mapping for $Y_i$ with respect to $\mathbf{X}_t$ in $\mathscr{G}$". The value of the function is called the "network exposure value..."



#### Definition 4: Positional invariance 

We say an network exposure mapping $g_{ti}$ is invariant to its position in the network if  

$$
g_{ti} = g_{tj} = g_t \text{ for all } i,j \in \mathscr{N} 
$$






#### Definition 5: Boundedness

We say that a network exposure mapping $g_{ti}$ is bounded if all possible network exposure values are contained by a finite set $\mathbf{D}$ 

$$
g_{ti}(\mathbf{X}_t, i) \in \mathbf{D} 
$$

and $|\mathbf{D}| < c$ for some constant $c$.


#### Comments

These definitions will be used in the next section to develop a model for inference under causal interference. The first assumption can be stated in graphic terms - it implies certain conditional independencies that can be encoded in a DAG by the removal and addition of arrows between nodes. The DAG in question would represent all the observational units rather than one (a typical) observation unit. 

The following four assumptions are crucial to define here because they are not possible to encode in the aforementioned DAG. We will use these to impose homogeneity restrictions on the DAG that enable us to apply statistical inference methods that are usually thought to require independence of observations. We will make a weaker assumption - that of "no spillover", impose homogeneity restrictions, and apply familiar methods such as generalized linear models to reason about network phenomena. 

It is useful to point out that the symmetry of a network exposure mapping $g_{ti}$ implies that the only thing that matters for the contribution of alters to $Y_i$ is the count of alters for which $X_t = 1$. The positional invariance of $g_{ti}$ means that what ever the function is that relates these counts to the outcome $Y_i$ is the same across observational units. Boundedness limits the number of distinct values that $g_{ti}$ can take because each distinct value constitutes a treatment level whose counterfactual we have to model. As we will see, the assumption of boundedness limits the number of counterfactuals. 

Under network causal inference, boundedness can obtain in three different ways. First, it could be as a result of restrictions on the structure of the underlying network. It could be the case that in the network of interest, there is an upper bound on node degree. For example, if the only relationships of interest between individual participants were marriages, each node would have a degree of either 0 or 1, meaning the count of alters $X_{tj} = 1, j \in N_i$ is either zero or one. The second way boundedness might obtain is via restrictions of the value of $\mathbf{X}_t$. It might be the case, for instance, that the count of $i$'s for which $X_{ti}=1$ is very low, then on average, the count of alters for which $X_{tj} = 1, j \in N_i$ will also be low. Finally, boundedness could obtain as a result of the functional form of $g_t$ itself. 

This might happen if $g_t$ models a network exposure which has a ceiling effect in its dose-response curve with the outcome of interest $Y_i$. For example, if $X_t$ indicates ownership of a car, and $\mathscr{G}$ encodes close friendships, $g_t$ would be a network exposure mapping which tells us how each additional friend who has a car shifts the outcome of interest. For most applications, its likely that beyond some number of friends (say 5) who have a car, an additional friend who gets a car will not change the outcome under investigation. 

Finally, we should note that under classical causal inference $g_t = c \in \mathbf{R}$ for $t \in [1,k]$. Exposure models are trivially loyal to the empty graph, so the network exposure mappings are trivially separable, positionally invariant, and bounded. 
