
::: {.callout-tip  collapse="true"}
# Learning goals

After this section, you will be equipped to:

-   Express NPSEMs, DAGs, and SWIGs as descriptions of the entire sample
    rather than one observation within a sample

-   Write an NPSEM of the whole sample based on a DAG

-   Draw a DAG of the sample based on an NPSEM

-   Write a causal model based on a DAG and intervention regime

-   Draw a SWIG based on a DAG and intervention regime

-   Apply the assumptions of FFRCISTG to a DAG or SWIG
:::

In the next few sections, we will use [Example 1](#sec-example-1) to describe the assumptions made under classical causal inference. First we give an overview of the ideas and tools we need to make that description: structural equation models and the directed acyclic graph (DAGs) that describe them. We use these to state the basic assumptions of the model currently used to reason about causality in epidemiology - the [finest fully randomized causally interpretable structured tree graph (FFRCISTG)](#def-ffrcistg). Finally, we derive an [FFRCISTG](#def-ffrcistg) model for this example, showing concrete illustrations for each assumption of the FFRCISTG model.
 

