```{r}
targets::tar_source("../R_functions")
```


### Assumptions

In [Example 1](#sec-example-1), say *Person 1* has job status $L_1$, *Person 2* has job status $L_2$ and *Person 3* has job status $L_3$. Each of these variables can only take on two values: “employed vs. unemployed.” Similarly, define $A_i$ as *Person $i$'s* dress (formal vs. informal), and $Y_i$ as their job offers (many vs. few). The job status measurement ($L_i$) precedes dress ($A_i$) in time, and dress precedes job offers ($Y_i$).

##### Independence I: No spillover


Under classic causal inference, we make the assumption of [no spillover](#def-no-spillover) -- that [equivalent measurements](#def-equivalence) taken across participants (e.g. $L_1$, $L_2$, and $L_3$) are independent of each other given all prior measures. i.e.:


$$
\begin{aligned}
L_1 \perp L_2 \\
L_2 \perp L_3 \\
L_1 \perp L_3 
\end{aligned}
$$


$$
\begin{aligned}
A_1 \perp A_2 | L_1, L_2, L_3\\
A_2 \perp A_3 | L_1, L_2, L_3 \\
A_1 \perp A_3 | L_1, L_2, L_3 
\end{aligned}
$$


$$
\begin{aligned}
Y_1 \perp Y_2 | L_1, L_2, L_3, A_1, A_2, A_3\\
Y_2 \perp Y_3 | L_1, L_2, L_3, A_1, A_2, A_3 \\
Y_1 \perp Y_3 | L_1, L_2, L_3, A_1, A_2, A_3 
\end{aligned}
$$

This is shown in @fig-no-spillover-dag as the removal of arrows that connected the $L_i$'s, $A_i$'s and $Y_i$'s. In @eq-no-spillover-dag, the $L_i$'s are not functions of each other, the $A_i$'s are not functions of each other, and the $Y_i$'s are not functions of each other. i.e. Given all the measurements taken prior to a set of contemporaneous measures, the contemporaneous measures are independent. This follows from the independence of the error terms $U_{L_i}$, the error terms $U_{A_i}$, and the error terms $U_{Y_i}$ across observations $i$.

{{< include fig-no-spillover-dag.qmd >}}

{{< include eq-no-spillover-dag.qmd >}}

##### Independence II: No interference


Classic causal inference makes the assumption of [no interference](#def-no-interference). i.e. We assume that measurements made across participants, but not at the same time, are independent of each other. This is shown as the absence of arrows that point from the $L_i$'s to $A_j$'s, the $L_i$'s to the $Y_j$'s and the $A_i$'s to the $Y_j$ for participants $i\neq j$ (see @fig-independence-dag).

This allows us to simplify the structural equation model so that each participant's measures are a function of only measures taken on them.


{{< include eq-independence-dag-full.qmd >}}


##### Homogeneity I: Identical distributions

Finally, we see above that the functions that generate observations $L_i$ are similar in structure to each other, as are the the functions that generate $A_i$'s and $Y_i$s. We make the homogeneity assumption that the functions are [identical](#def-identical-distributions) to each other. 

$$
\begin{aligned}
 f_L &= f_{L_1} = f_{L_2} = f_{L_3} \\
 f_A &= f_{A_1} = f_{A_2} = f_{A_3} \\
 f_Y &= f_{Y_1} = f_{Y_2} = f_{Y_3}  \\
\end{aligned}
$$
