
::: {.callout-tip  collapse="true"}
# Learning goals

After this section, you will be equipped to:

- Write an NPSEM of the whole sample for a model that shows network interference  
- Draw the corresponding DAG and SWIG  
- Apply the assumption of homogeneous network interference to an NPSEM 
:::


Before specifying a model that can accommodate the interdependence between *Persons 1* and *2* in [Example 2](#sec-example-2), we outline some useful definitions.  We use these to extend the [FFRCISTG](#def-ffrcistg) model described in @sec-classical-causal-inference to accommodate settings characterized by causal interference.  

Because of the assumptions of *no interference* and *no spillover*, FFRCISTG models are unable to incorporate this additional information about the relationships between individuals in [Example 2](#sec-example-2).  These relationships cause what is termed *causal interference* — the treatment level of one unit affects the outcome of another unit.

We make progress by mapping out the structure of interference in order to incorporate it into the model.  We introduce a statistical model called the [*Network Finest Fully Randomized Causally Interpretable Structured Tree Graph (NFFRCISTG)*](#def-nffrcistg) — an extension of the [FFRCISTG](#def-ffrcistg) model that uses graphs to encode the pattern of causal interference among a set of observational units.

Below we build an [NFFRCISTG](#def-nffrcistg) model for [Example 2](#sec-example-2), illustrating the assumptions of the model.  Before that, we outline some ideas and language we will need for the illustration.






 
