
::: {.callout-warning icon=false appearance="simple"}
#### Example 2: Marriage and jobs {#sec-example-2 .unnumbered}

We mentioned that in our study sample *Person 1* and *Person 2* are married to each other and *Person 1* and *Person 3* are acquaintances.  In the causal system connecting their job status, dress, and job offers, an argument could be made that *Person 1*’s job status affects *Person 2*’s dress, since they pool their salaries as a married couple.   It could also be argued that *Person 1*’s job status affects *Person 2*’s job opportunities if having a job brings the married couple into contact with other married couples who are connected to job markets.  

Finally, we could argue that *Person 1*’s dress affects *Person 2*’s job opportunities if some aspect of the reputation *Person 2* enjoys among potential colleagues derives from their spouse’s appearance.   Symmetrically, *Person 2*’s measures could influence *Person 1*’s.  

But what about the relationship between *Person 1* and *Person 3*?  We can imagine that the dress of a newly acquainted colleague would not affect the dress or job opportunities of her colleague.  Whereas *Person 1* and *Person 2* are causally related, *Person 1* and *Person 3* are not; their relationship is irrelevant to the causal system under investigation.  *Person 2* and *Person 3* do not affect each other since they have no relationship at all.

:::
