### Assumptions

##### Independence I: No spillover

In [Example 2](#sec-example-2), we make the assumption of [no spillover](#def-no-spillover) - that [equivalent measurements](#def-equivalence) (e.g. $L_1$, $L_2$, and $L_3$) are independent of each other given all prior measures.

This is shown in @fig-interference-dag, as the removal of arrows that connected the $L_i$'s, $A_i$'s and $Y_i$'s in @fig-fully-connected-dag. In @eq-interference-dag, the $L_i$'s are not functions of each other, the $A_i$'s are not functions of each other, and the $Y_i$'s are not functions of each other, unlike in @eq-fully-connected-dag. This implies that conditioning all the measurements taken prior to a set of contemporaneous measures, the contemporaneous measures are independent.

##### Independence II: Network interference

{{< include fig-interference-dag.qmd >}} 

{{< include eq-interference-dag.qmd >}} 

We make the assumption that interference respects some mapping between individuals - a mapping given by a [graph](#def-graph) adjacency matrix $\Psi$. In @fig-interference-dag, based on their relationships with one another, *Person 1*'s measures are connected with *Person 2*'s, and neither are connected with *Person 3*'s.  

$$
\Psi = \begin{bmatrix}
0,& 1,& 0 \\
1,& 0,& 0 \\
0,& 0,& 0 \\
\end{bmatrix}
$$


##### Homogeneity I: Homogenous network interference


We assume that the [exposure mapping](#def-exposure-mapping) for each variable in the structural model is [separable](#def-separability). i.e. We define $g_{A_i}$, $h_{Y_i}$, and $g_{Y_i}$ as [component functions](#def-separability) for $A_i$ with respect to $\mathbf{L}$, for $Y_i$ with respect to $\mathbf{A}$, and for $Y_i$ with respect to $\mathbf{L}$. The assumption of [separability](#def-separability) allows us to write the model as follows:

$$
\begin{aligned}
L_1 &= f_{L_1}(U_{L_1}) \\
L_2 &= f_{L_2}(U_{L_2}) \\
L_3 &= f_{L_3}(U_{L_3} ) \\
A_1 &= f_{A_1}(U_{A_1}, L_1, g_{A_1}(\mathbf{L}, \Psi_1)) \\
A_2 &= f_{A_2}(U_{A_2}, L_2, g_{A_2}(\mathbf{L}, \Psi_2)) \\
A_3 &= f_{A_3}(U_{A_3}, L_3, g_{A_3}(\mathbf{L}, \Psi_3)) \\
Y_1 &= f_{Y_1}(U_{Y_1}, L_1, A_1, g_{Y_1}(\mathbf{L}, \Psi_1), h_{Y_1}(\mathbf{A}, \Psi_1)) \\
Y_2 &= f_{Y_2}(U_{Y_2}, L_2, A_2, g_{Y_2}(\mathbf{L}, \Psi_2), h_{Y_2}(\mathbf{A}, \Psi_2)) \\
Y_3 &= f_{Y_3}(U_{Y_3}, L_3,A_3,  g_{Y_2}(\mathbf{L}, \Psi_3), h_{Y_2}(\mathbf{A}, \Psi_3)) \\
\end{aligned}
$$


where $\Psi_i$ is the $i^{th}$ row of matrix $\Psi$.



We assume that the value of a component function is [invariant to its position](#def-positional-invariance) in the network. This allows us to drop the person subscript on the network exposure mappings. 

$$
\begin{aligned}
L_1 &= f_{L_1}(U_{L_1}) \\
L_2 &= f_{L_2}(U_{L_2}) \\
L_3 &= f_{L_3}(U_{L_3} ) \\
A_1 &= f_{A_1}(U_{A_1}, L_1, g_{A}(\mathbf{L}, \Psi_1)) \\
A_2 &= f_{A_2}(U_{A_2}, L_2, g_{A}(\mathbf{L}, \Psi_2)) \\
A_3 &= f_{A_3}(U_{A_3}, L_3, g_{A}(\mathbf{L}, \Psi_3)) \\
Y_1 &= f_{Y_1}(U_{Y_1}, L_1, A_1, g_{Y}(\mathbf{L}, \Psi_1), h_{Y}(\mathbf{A}, \Psi_1)) \\
Y_2 &= f_{Y_2}(U_{Y_2}, L_2, A_2, g_{Y}(\mathbf{L}, \Psi_2), h_{Y}(\mathbf{A}, \Psi_2)) \\
Y_3 &= f_{Y_3}(U_{Y_3}, L_3,A_3,  g_{Y}(\mathbf{L}, \Psi_3), h_{Y}(\mathbf{A}, \Psi_3)) \\
\end{aligned}
$$

We also assume its [bounded](#def-boundedness), meaning

$$
\begin{aligned}
g_{A}(\mathbf{L}, \Psi_i) &\in \{0, 1\} \\
g_{Y}(\mathbf{L}, \Psi_i) &\in \{0, 1\} \\
h_{Y}(\mathbf{A}, \Psi_i) &\in \{0, 1\} \\
\end{aligned}
$$




##### Homogeneity II: Identical distributions

We assume that the structural equations that produce individual measures are [identical](#def-identical-distributions) across individuals. Hence, we can drop the person subscript from the structural equations. 

$$
\begin{aligned}
L_1 &= f_{L}(U_{L_1}) \\
L_2 &= f_{L}(U_{L_2}) \\
L_3 &= f_{L}(U_{L_3} ) \\
A_1 &= f_{A}(U_{A_1}, L_1, g_{A}(\mathbf{L}, \Psi_1)) \\
A_2 &= f_{A}(U_{A_2}, L_2, g_{A}(\mathbf{L}, \Psi_2)) \\
A_3 &= f_{A}(U_{A_3}, L_3, g_{A}(\mathbf{L}, \Psi_3)) \\
Y_1 &= f_{Y}(U_{Y_1}, L_1, A_1, g_{Y}(\mathbf{L}, \Psi_1), h_{Y}(\mathbf{A}, \Psi_1)) \\
Y_2 &= f_{Y}(U_{Y_2}, L_2, A_2, g_{Y}(\mathbf{L}, \Psi_2), h_{Y}(\mathbf{A}, \Psi_2)) \\
Y_3 &= f_{Y}(U_{Y_3}, L_3,A_3,  g_{Y}(\mathbf{L}, \Psi_3), h_{Y}(\mathbf{A}, \Psi_3)) \\
\end{aligned}
$$

