
::: {.callout-tip collapse="true"}
# Learning goals

After this section, you will be equipped to:

- Write an NPSEM of the whole sample for a model that includes network generators  
- Draw the corresponding DANG  
- Apply the assumption of homogeneous network interference to an NPSEM that includes network generators  

:::


In this section of the appendix, we extend the NFFRCISTG model described in @sec-network-causal-inference by allowing for the inclusion of two classes of observational unit — people and places — and by allowing the relationships between people and places to be randomly generated by the [causal model](#def-causal-model). We name this the [Bipartite Random Network FFRCISTG model (BRNFFRCISTG)](#def-brnffrcistg).  It is a [causal model](#def-causal-model) that includes one or more [*graph generators*](#def-graph-generator) — structural equations that model the network edges as random variables.  

Before outlining the [BRNFFRCISTG](#def-brnffrcistg), we introduce new tools to mirror the shift we advocate from conceiving of statistical inference as the task of inferring something about a probability distribution using a growing number of realizations, to thinking about it as the task of inferring something about the distribution using one growing realization of the model.  We introduce the causal Directed Acyclic Network Graph (DANG) and the Single World Intervention Network Graph (SWING).



