
# Outbreaks {#sec-intervention}


```{r}
# Access custom defined functions
targets::tar_source("R_functions")
```




## {.unnumbered}

{{< include ___figures/fig-hiimpact-communities-map.qmd >}}

We modeled how different vaccination strategies that target the most influential community districts could disrupt transmission. Two strategies were compared: a contact-neutralizing strategy, which sees districts affiliated with the highest numbers of unvaccinated people as high priority, and a movement-neutralizing strategy, which priorities districts most connected by movement across neighborhoods.



## Spatial efficiency

@fig-hiimpact-communities-bar and @fig-hiimpact-communities-map show which community districts would need to be immunized to reach one-third and two-thirds of the study population under each strategy. Under the **contact-neutralizing strategy**, just five community districts—Hell’s Kitchen–Chelsea (MN04), Williamsburg–Greenpoint (BK01), Central Harlem North (MN10), Bedford-Stuyvesant West (BK03), and Astoria (QN01)—would together cover roughly 33 percent of participants.  


{{< include ___figures/fig-hiimpact-communities-bar.qmd >}}

Expanding to 13 districts would reach 66 percent, adding Washington Heights South (MN12), Bushwick (BK04), West Village–SoHo–Tribeca (MN02), Crown Heights North (BK08), Upper West Side Central (MN07), Hamilton Heights–Sugar Hill (MN09), Brooklyn Heights–Downtown (BK02), and Midtown–Times Square–Flatiron (MN05).  




Under the **movement-neutralizing strategy**, six districts would be needed to reach 33 percent—Hell’s Kitchen–Chelsea (MN04), Williamsburg–Greenpoint (BK01), Midtown–Times Square–Flatiron (MN05), Bushwick (BK04), and West Village–SoHo–Tribeca (MN02).  

To reach 66 percent, 16 districts would need to be included, adding Bedford-Stuyvesant West (BK03), Central Park–Upper East Side (MN64), Central Harlem North (MN10), Astoria (QN01), Crown Heights North (BK08), Hamilton Heights–Sugar Hill (MN09), Ridgewood–Maspeth (QN05), Crown Heights South (BK09), East Harlem (MN11), Flatbush–Ditmas Park (BK14), and Sunset Park (BK07).  


## Network impact

In the MPX NYX Person-place graph, participants connected to a common set of places form a network. @fig-netimpact  shows how the different vaccination strategies affect connectivity in that network. Before any intervention, nearly every participant belonged to a single large connected component, meaning potential transmission paths linked most of the population. As immunization expanded, this component fragmented—more sharply under the movement-neutralizing approach than under the contact-based one.



{{< include ___figures/fig-netimpact.qmd >}}

The movement-neutralizing strategy reduced overall network connectivity faster, suggesting it may better interrupt chains of exposure by severing travel-based bridges between boroughs. In contrast, the contact-neutralizing approach more efficiently reduced the proportion of unvaccinated individuals, directly shrinking susceptible clusters. Differences between the two approaches became pronounced only after roughly ten districts were vaccinated, highlighting how epidemic control depends on both social density and mobility.

## Interpretation

Together, these models illustrate that how a city moves matters as much as where people meet. In an interconnected urban network like New York, interventions focused solely on individual contact density may miss the spatial bridges that sustain outbreaks. On the other hand, focusing on spatial bridges may slow down the rate of vaccination. In our data, the benefit of quickly breaking up the network was lower than the benefit of quickly vaccinating people.  


{{< include ___misc/banner_seminar.qmd >}}


