

# Gatherings {#sec-venues}

```{r include=FALSE}
targets::tar_source("R_functions")
knitr::opts_chunk$set(cache = TRUE, cache.path = "_cache/gatherings/")
```




### {.unnumbered}



{{< include __figures/fig-gatherings.qmd >}}

MPX NYC participants reported 604 total locations where they had physical or sexual contact in a group setting—what we call *gatherings*. Two in five gatherings occurred in private residences, and about a quarter took place at dance parties. Over half of gatherings were in Manhattan, while roughly one-third occurred in Brooklyn.  




::: {.callout-note collapse=true icon=false}
# Show Table 7.4: Gatherings
{{< include __tables/tbl-gatherings.qmd >}}

:::







## Sexual contact and distance from home 

Just less then one in three of all gatherings happened within the same community district as the participant’s home, one-third were in another borough, and the remainder were in a different community district within the same borough.


{{< include __figures/fig-placetype-bar-grid.qmd >}}

Gatherings that involved sexual contact were overwhelmingly private residences, whereas non-sexual physical gatherings were mostly dance parties (@fig-placetype-bar-grid).

The closer a venue was to a participant’s home, the more likely it was to be a private residence and to include sexual contact. Conversely, the farther the venue, the more likely it was a dance party.




## Popular neighborhoods 

The neighborhoods most frequently mentioned as gathering locations included Hell’s Kitchen and Chelsea in Manhattan, and East Williamsburg, Bushwick, and Bedford-Stuyvesant in Brooklyn.


{{< include __tables/tbl-gatherings-neighborhoods.qmd >}}








