---
execute:
  echo: false
  warning: false
  messages: false
---

# Contact venues 

## Type of venue for contact vs. type of contact {.unnumbered}

::: {.panel-tabset}

### Plot

```{r plot_radar_facet_placetype_placesex}
#| fig-width: 9
#| fig-height: 8
#| 


mpxnyc_colors <- mpxnyc::mpxnyc_colors
attach(mpxnyc_colors)
targets::tar_source(files = "/Users/keletso/Documents/_gitrepos/mpxnyc_data_analysis/R_functions")


make_table_freq2(placeType, placeSex, person_analysis = FALSE) |>
  dplyr::filter(!is.na(level)) |>
  plot_radar_stratified() |>
  add_caption() |>
  apply_style_radar_facet_plot()

```

### Data

```{r table_radar_facet_placetype_placesex}
#| fig-width: 9
#| fig-height: 8
#| 

make_table_freq2(placeType, placeSex, person_analysis = FALSE) |>
        draw_table_stratified()


```

:::

##  Type of venue for contact vs. distance from home {.unnumbered}

::: {.panel-tabset}

### Plot

```{r plot_radar_facet_placetype_distancefromhome}
#| fig-width: 9
#| fig-height: 8
#| 





make_table_freq2(placeType, distanceFromHome, person_analysis = FALSE) |>
  plot_radar_stratified() |>
  add_caption() |>
  apply_style_radar_facet_plot()



```

### Data

```{r table_radar_facet_placetype_distancefromhome}
#| fig-width: 9
#| fig-height: 8
#| 





make_table_freq2(placeType, distanceFromHome, person_analysis = FALSE) |>
          draw_table_stratified()



```

:::



## Place type vs. Distance from home vs. Sex contact {.unnumbered}

::: {.panel-tabset}

### Plot

```{r plot_radar_facet_placetype_placesex_distancefromhome}
#| fig-width: 11
#| fig-height: 10
#| 


  make_table_freq3(placeType, placeSex, distanceFromHome, person_analysis = FALSE) |>
    dplyr::filter(!is.na(level)) |>
  plot_radar_stratified2() |>
  add_caption("Data source: MPX NYC Survey (restricted to 1,304 residents of New York City). www.mpxresponse.org") |>
  apply_style_radar_facet_plot()

```

### Data

```{r table_radar_facet_placetype_placesex_distancefromhome}
#| fig-width: 11
#| fig-height: 10
#| 


  make_table_freq3(placeType, placeSex, distanceFromHome, person_analysis = FALSE) |>
    draw_table_stratified2()

```

:::



