project:
  type: book

book:
  title: "MPX NYC"
  author: "Keletso Makofane"
  date: "11/21/2024"
  chapters:
  - "index.qmd"
  - part: "_methods.qmd"
    chapters:
      - "_data_collection.qmd"
      - "_measures.qmd"
      - "_statistical_analysis.qmd"
  - part: "_results.qmd"
    chapters:
    - "_results_participants.qmd"
    - "_results_contact_venues.qmd"
    - "_results_movement.qmd"
    - "_results_spatial_mixing.qmd"
    - "_results_hypothetical_intervention.qmd"
  - part: "_tech_app.qmd"
    chapters:
    - "_tech_app_data.qmd"
    - "_tech_app_network_measures.qmd"
    - "_tech_app_hypothetical_intervention.qmd"
  
bibliography: bibliography.bib

format:
  html:
    theme: cosmo


