project:
  type: book
  
pdf-engine: pdflatex

    
execute: 
  messages: false
  warning: false
  echo: true
  cache: false
  
preview: 
  watch-inputs: true
    
format:
  html:
    embed-resources: false
    font: "Helvetica Neue"
    grid: 
      gutter-width: 3.5em
    theme: "_const/custom_theme.scss"
    code-fold: true
    code-overflow: wrap
    code-tools: 
      source: false
      toggle: true
    code-block-bg: true
    code-block-border-left: "#FF99C5"
    code-link: true
    number-depth: 3
    crossrefs-hover: true

  

bibliography: "_const/bibliography.bib"
reference-location: margin
citation-location: margin

title-block-style: none

crossref:
  appendix-title: " "
  appendix-delim: " -"


book:
  google-analytics: "G-8EDGL4274R"
  cookie-consent: true
  page-footer: 
    left: "Copyright 2025, RESPND-MI" 
    right: 
      - icon: github
        href: https://github.com/
  sidebar:
    title: " "
    style: floating
    collapse-level: 1
    logo: "_const/images/image_mpxnyc.png"
    
  chapters:
  - "index.qmd"
  - part: "Background"
    chapters:
    - "1_introduction/1_1__intro_outbreak_to_epidemic.qmd"
    - "1_introduction/1_2__intro_our_response.qmd"
    - "1_introduction/1_3__intro_related_research.qmd"
  - part: "Methods"
    chapters:
    - "2_methods/2_2_methods_data.qmd"
    - "2_methods/2_3_methods_measures.qmd"
    - "2_methods/2_4_methods_statistical_analysis.qmd"
  - part: "Results"
    chapters:
      - "3_results/3_1__results_participants.qmd"
      - "3_results/3_2__results_gatherings.qmd"
      - "3_results/3_3__results_movement.qmd"
      - "3_results/3_4__results_mixing.qmd"
      - "3_results/3_5__results_outbreak_control.qmd"
  - part: "Discussion"
    chapters:
      - "4_discussion/4_discussion.qmd"
      - "4_discussion/4_discussion_recommendations.qmd"
  - part: "Endnotes"
    chapters:
      - "6_endnotes/6_1__references.qmd"
      - "6_endnotes/6_2__about.qmd"
  appendices: 
      - "A_ssnac1_context/A__ssnac1_context.qmd"
      - "B_ssnac2_description/B__ssnac2_description.qmd"
      - "C_ssnac3_causality/C__ssnac3_causality.qmd"
      - "D_ssnac3_measurement/D__ssnac3_measurement.qmd"
#      - "E_ssnac5_statistics/E__ssnac5_statistics.qmd"
      - "F_organizing/F__organizing.qmd"
      - "E_marketing_comm/E__marketing_comm.qmd"
      - "G_supplementary_results/G__supplementary_results.qmd"



    

