project:
  type: book

book:
  title: "MPX NYC"
  author: "Keletso Makofane"
  chapters:
  - "index.qmd"
  - part: "Background"
    chapters: 
      - "1_introduction.qmd"
  - part: "Methods"
    chapters:
      - "2_methods_data_collection.qmd"
      - "2_methods_measures.qmd"
      - "2_methods_statistical_analysis.qmd"
  - part: "Results"
    chapters:
      - "3_results_participants.qmd"
      - "3_results_contact_venues.qmd"
      - "3_results_movement.qmd"
      - "3_results_spatial_mixing.qmd"
      - "3_results_hypothetical_intervention.qmd"
  - part: "Discussion"

  - part: "References"
    chapters:
      - "_references.qmd"
  appendices: 
      - "4_methods_appendix.qmd"
      - "5_results_appendix.qmd"
      - "6_questionnaire.qmd"
  sidebar:
    style: floating
    collapse-level: 1
    tools:
    - icon: github
      href: https://github.com/
format:
  html:
    theme: materia
    mainfont: "Helvetica Neue"
    linestretch: 1.5
comments:
  hypothesis: true


