
## Outbreak intervention analysis

Consider a sequence of graphs $G^{(k)}$ for $k \in \mathbb{N}_0$ constructed so that

$$
G^{(0)}(N^{(0)}, \psi^{(0)}) = G(N, \psi).
$$

and so that given $G^{(k)}$, we calculate $G^{(k+1)}(N^{(k+1)}, \psi^{(k+1)})$ by selecting a community district $n^{(k+1)}$ along with all participants connected with it

$$
H^{(k+1)} = \{s \in N^{(k)}_p : \psi^{(k)}(s,n^{(k+1)}) > 0 \}
$$

and removing them from the node set

$$
N^{(k+1)}   = N^{(k)} \backslash \{ H^{(k+1)} \cup \{ n^{(k+1)} \}   \}
$$ The updated adjacency function $\psi^{(k+1)}$ preserves all the edges represented by $\psi^{(k)}$ for terminal nodes included in $N^{(k+1)}$:

$$
\psi^{(k+1)}(a,b) = \psi^{(k)}(a,b),  \forall a,b \in  N^{(k+1)}
$$

Note: All measures defined in the previous sections can be calculated based on the updated graph $G^{(k)}$. We indicate this case by adding a superscript with index number $k$ for the particular measure. e.g. We can define $s_j^{(k)}|A$ relative to graph $G^{(k)}$ just as $s_j|A$ is defined relative to graph $G$.

#### Intervention strategies

We examined two approaches for selecting a community district to immunize, corresponding to different intervention priorities. In the first, we select the next community district to immunize to maximize the number of people to be immunized. In the second, we select the next community district with the goal of minimizing the likelihood of contagion between community districts.

i.e. in the [contact-neutralizing strategy]{.underline} $n^{(k+1)}$ satisfies:

$$
r_{n^{(k+1)}} = \max_{j \in N_c^{(k)}}{r_j^{(k)}}
$$

and in the [movement-neutralizing strategy]{.underline} $n^{(k+1)}$ satisfies:

$$
s_{n^{(k+1)}} = \max_{j \in N_c^{(k)}}{s_j^{(k)}}
$$

#### Intervention outcomes

[spatial efficiency]{.underline}

Intervention coverage for community district $n^{(k)}$, the $k^{th}$ community district to be immunized, is defined as:

$$
\frac{ r_{n^{(k)}}^{(k-1)}}{ |N_p|}
$$

The cumulative intervention coverage after immunizing $k$ community districts, therefore, is:

$$ 
\sum_{t = 1}^k{\frac{ r_{n^{(t)}}^{(t-1)}}{ |N_p|}}
$$

[Social network impact]{.underline}

The cumulative social network impact of immunizing $k$ community districts is measured in terms of the size of the largest of the connected components $C_t^{(k)}$ of the $G_p^{(k)}$ network as a proportion of the total number of participants.

$$
\frac{\max_t{C^{(k)}_{t}}}{|N_p|}
$$

