```{r process_data}

targets::tar_source("R_functions") # Access custom defined functions


```



```{r}
targets::tar_make(reporter = "silent") # Run data pipeline

```


::: {#authors}
Keletso Makofane, Nick Diamond, Jennifer McQueen, Elle Lett, Nguyen Tran

RESPND-MI Collaboration
:::

```{r}
#| fig-width: 2
#| fig-height: 2
#| fig-align: center


plot_icon(icon_name = "peach", color = "dark_orange", shape = 0)

```



::: {#date}
March 2024, New York City

https://www.mpxnyc.app
:::



::: {#acknowledgements}
[Principal investigator]{.underline}: Keletso Makofane, MPH, PhD. [Co-investigators]{.underline}: Jennifer Barnes-Balenciaga, Nicholas Diamond, MPH, Elle Lett, PhD, MA, MBiostat, Cody Nolan, MD, Martez Smith, LMSW, PhD, Nguyen Tran, MPH, PhD. [Former investigators]{.underline}: Pedro Botti Careneiro, MPH, PhD, Seema Kara, MPH, James Krellenstein, Ken Nadolski, MPH, Robert Pitts, MD, Grant Roth, MPH, Sudipta Saha, MS, Christian Urrutia, Chris Wyman. [Translators]{.underline}: Antón Castellanos Usigli, MPH, PhD Referencegroup: Judith D. Auerbach, PhD (*University of California, San Francisco*), Lisa Berkman, PhD (*Harvard University*), Forrest W. Crawford, PhD (*Yale University*), William C. Goedel, PhD (*Brown University*), Gregg Gonsalves, PhD (*Yale University*), Ian W. Holloway, PhD, LCSW, MPH (*University of California, Los Angeles*), Louise Ivers, MB, BCh, MD, MPH, DTMH (*Massachusetts General Hospital)*, Lawrence C. Long, MCom, PhD (*Boston University)*, Kenneth Mayer, MD (*The Fenway Institute*), Gregorio Millett, MPH (*amfAR*), Eric J. Tchetgen Tchetgen, PhD (*University of Pennsylvania*). [Research sponsors and funders]{.underline}: amfAR, National Institutes of Health, neo4j,Marketing sponsors and funders: Grindr, Hub for Health Intervention, UCLA Luskin School of Public Affairs.Administration: Christian Urrutia (prep4all), James Krellenstein (prep4all). [Report reviewers]{.underline}: ...
:::

# Welcome to MPX NYC {.unnumbered .hidden}
