---
title: "MPX NYC"
subtitle: "Key findings and recommendations"
author: "Keletso Makofane"
date: 23 May 2024

crossref: 
  thm-prefix: Box
  thm-title: Box
  tbl-prefix: Table
  tbl-title: Table
  fig-prefix: ""
  fig-title: ""
editor: visual
always_allow_html: true
prefer-html: true
fig-cap-location: top 
execute:
  echo: false
  warning: false
  message: false
format:
  revealjs:
    incremental: true
    scrollable: true
    fig-align: center
    align: center
---

```{r update_mpxnyc_package, include = FALSE, messages=FALSE, warning = FALSE}
remotes::install_github("KeletsoMakofane/mpxnyc", auth_token = "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")
```

```{r load_libraries, include = FALSE, messages=FALSE, warning = FALSE}
library(tidyverse)
library(ggplot2)
library(mpxnyc)
library(sf)
library(tidygraph)
library(ggraph)
library(igraph)



mpxnyc_colors <- mpxnyc::mpxnyc_colors
attach(mpxnyc_colors)

```

```{r scripts}
targets::tar_source(files = "R_functions")
targets::tar_source(files = "R_functions/1_data_processing")
targets::tar_source(files = "R_functions/2_data_summary")
targets::tar_source(files = "R_functions/3_data_extract")
targets::tar_source(files = "R_functions/4_plot")
```

```{r update_data_pipeline, include=FALSE, messages=FALSE, warning = FALSE}


targets::tar_make() # Runs the data pipeline shown in _targets.R


```

```{r}


targets::tar_source(files = "R_functions")

```

```{r plot_styling}
apply_style_spacing_descriptives <- function(plot, caption_hjust = 1){
  
  plot +
    theme_void() +
    scale_fill_manual("", values = c(
                                      dark_blue,
                                      dark_pink,
                                      dark_purple,
                                      light_blue,
                                      light_pink,
                                      light_purple,
                                      light_orange,
                                      dark_green,
                                      light_green,
                                      mid_blue,
                                      mid_purple,
                                      dark_brown,
                                      mid_brown,
                                      light_brown
                                    )) +
    theme(
        plot.title         = element_text(hjust = 0.5, margin = margin(0, 0, 1, 0, "mm")),
        plot.subtitle      = element_text(hjust = 0.5, margin = margin(0, 0, 15, 0, "mm")),
        axis.title.y       = element_text(angle = 90, margin = margin(0, 10, 0, 0, "mm")),
        plot.caption       = element_text(margin = margin(15, 0, 0, 0), hjust = caption_hjust),
        panel.margin       = margin(1,1,1,1, "cm"),
        plot.margin        = margin(1,1,1,1, "cm"),
        legend.position    = "none", 
        panel.grid.major.y = ggplot2::element_line(size = 0.1),
        axis.text.x        = element_text(),
        axis.text.y        = element_text()
    )
}

apply_style_spacing_remainder <- function(plot, caption_hjust = 0){
  
  plot +
    theme(
        plot.title    = element_text(hjust = 0.5, margin = margin(0, 0, 1, 0, "mm")),
        plot.subtitle = element_text(hjust = 0.5, margin = margin(0, 0, 15, 0, "mm")),
        axis.title.y  = element_text(angle = 90, margin = margin(0, 10, 0, 0, "mm")),
        plot.caption  = element_text( hjust = caption_hjust),
        panel.margin  = margin(1,1,1,1, "cm"),
        plot.margin   = margin(1,1,1,1, "cm")
    ) +
            scale_fill_manual("", values = c(
                                      dark_blue,
                                      dark_pink,
                                      dark_purple,
                                      light_blue,
                                      light_pink,
                                      light_purple,
                                      light_orange,
                                      dark_green,
                                      light_green,
                                      mid_blue,
                                      mid_purple,
                                      dark_brown,
                                      mid_brown,
                                      light_brown
                                    )) 
}

apply_style_spacing_place <- function(plot, caption_hjust = 0){
  
  plot +
        scale_fill_manual("", values = c(
                                      dark_blue,
                                      dark_pink,
                                      dark_purple,
                                      light_blue,
                                      light_pink,
                                      light_purple,
                                      light_orange,
                                      dark_green,
                                      light_green,
                                      mid_blue,
                                      mid_purple,
                                      dark_brown,
                                      mid_brown,
                                      light_brown
                                    )) +
     theme(
         plot.title    = element_text(hjust = 0.5, margin = margin(0, 0, 1, 0, "mm")),
         plot.subtitle = element_text(hjust = 0.5, margin = margin(0, 0, 15, 0, "mm")),
         plot.caption  = element_text( hjust = caption_hjust, margin = margin(1, 1, 1, 1, "cm")),
         plot.margin   = margin(1,1,1,1, "cm")
     )
}

apply_style_spacing_grouped_radar <- function(plot, caption_hjust = 0){
    
  plot +
        scale_fill_manual("", values = c(
                                      dark_blue,
                                      dark_pink,
                                      dark_purple,
                                      light_blue,
                                      light_pink,
                                      light_purple,
                                      light_orange,
                                      dark_green,
                                      light_green,
                                      mid_blue,
                                      mid_purple,
                                      dark_brown,
                                      mid_brown,
                                      light_brown
                                    )) +
     theme(
         plot.title    = element_text(hjust = 0.5, margin = margin(0, 0, 1, 0, "mm")),
         plot.subtitle = element_text(hjust = 0.5, margin = margin(0, 0, 15, 0, "mm")),
         plot.caption  = element_text( hjust = caption_hjust, margin = margin(1, 1, 1, 1, "cm")),
         plot.margin   = margin(1,1,1,1, "cm"),
         legend.position = "bottom"
     )
}

apply_style_spacing_heatmap <- function(plot, caption_hjust = 0){
  
  plot +
    theme(
        plot.title    = element_text(hjust = 0.5, margin = margin(0, 0, 1, 0, "mm")),
        plot.subtitle = element_text(hjust = 0.5, margin = margin(0, 0, 15, 0, "mm")),
        plot.caption  = element_text( hjust = caption_hjust),
        panel.margin  = margin(1,1,1,1, "cm"),
        plot.margin   = margin(1,1,1,1, "cm"),
        legend.position = "bottom"
    ) +
      scale_fill_gradient2("", trans = "log", low = dark_blue, mid = "white", high = dark_pink)  
}

apply_style_spacing_coverage <- function(plot, caption_hjust = 0){
  
  plot +
        scale_fill_manual("", values = c(
                                      dark_blue,
                                      dark_pink,
                                      light_blue
                                    )) +
    theme(
        plot.title    = element_text(hjust = 0.5, margin = margin(0, 0, 1, 0, "mm")),
        plot.subtitle = element_text(hjust = 0.5, margin = margin(0, 0, 15, 0, "mm")),
        axis.title.y  = element_text(angle = 90, margin = margin(0, 10, 0, 0, "mm")),
        plot.caption  = element_text( hjust = caption_hjust),
        panel.margin  = margin(1,1,1,1, "cm"),
        plot.margin   = margin(1,1,1,1, "cm"),
        legend.position = "none"
      
    )  
}



```

```{r plot_data}


get_variable_labels             <- function(variable_name, person_analysis = TRUE){
    
  variable_labels           <- targets::tar_read(initial_settings)[["labels_list"]][[variable_name]][["levels"]] %>% unlist()
  variable_levels           <- names(variable_labels)
  
  if (is.null(variable_labels)){
    if (person_analysis){
          variable_labels <- targets::tar_read(bipartite_graph) %>%
                          tidygraph::activate(nodes) %>%
                          tidygraph::filter(type) %>%
                          data.frame() %>%
                          {.[,variable_name]} %>%
                          unique()
    
    variable_levels <- variable_labels
    } else {
              
    variable_labels <- targets::tar_read(bipartite_graph) %>%
                          tidygraph::activate(edges) %>%
                          tidygraph::filter(type) %>%
                          data.frame() %>%
                          {.[,variable_name]} %>%
                          unique()
    
    variable_levels <- variable_labels
    }} 
  
  return(list(variable_levels = variable_levels, variable_labels = variable_labels))

}

make_commuting_network_data     <- function(){
  
home_data <-  targets::tar_read(bipartite_graph) %>%
                activate(edges) %>%
                filter(home) %>%
                mutate(person_name = .N()$name[from]) %>%
                mutate(home_name = .N()$name[to]) %>%
                data.frame() %>%
                select(home_name, person_name)

place_data <-  targets::tar_read(bipartite_graph) %>%
                activate(edges) %>%
                filter(!home) %>%
                mutate(person_name = .N()$name[from]) %>%
                mutate(place_name = .N()$name[to]) %>%
                data.frame() %>%
                select(place_name, person_name)
    
  place_data %>% 
    left_join(home_data) %>%
      transmute(from = home_name, to = place_name) %>%
      group_by(from, to) %>%
      summarize(weight = n()) 
  
}

make_coattendance_network_data  <- function(){
  
  targets::tar_read(bipartite_graph) %>%
    igraph::bipartite_projection(which = "false") %>%
    tidygraph::as_tbl_graph() %>%
    activate(edges) %>%
    mutate(from_name = .N()$name[from], to_name = .N()$name[to]) %>%
    data.frame() %>%
    transmute(from = from_name, to = to_name, weight = weight) %>%
    mutate(
      new_from =  ifelse(from > to, from, to), 
      new_to = ifelse(from > to, to, from)
      ) %>%
    transmute(from = new_from, to = new_to, weight = weight) %>%
    group_by(from, to) %>%
    summarize(weight = sum(weight))
  
  
}

make_3_way_table                <- function(variable = overall,stratum_variable_a = overall, stratum_variable_b = overall, person_analysis = TRUE){
  variable           <- enquo(variable)
  stratum_variable_a <- enquo(stratum_variable_a)
  stratum_variable_b <- enquo(stratum_variable_b)

  variable_name           <- quo_name(variable)
  stratum_variable_a_name <- quo_name(stratum_variable_a)
  stratum_variable_b_name <- quo_name(stratum_variable_b)
  
  get_variable_labels(variable_name)
  
  variable_levels <- get_variable_labels(variable_name)[["variable_levels"]]
  variable_labels <- get_variable_labels(variable_name)[["variable_labels"]]
  
    stratum_variable_a_levels <- get_variable_labels(stratum_variable_a_name)[["variable_levels"]]
  stratum_variable_a_labels <- get_variable_labels(stratum_variable_a_name)[["variable_labels"]]
  
  
    stratum_variable_b_levels <- get_variable_labels(stratum_variable_b_name)[["variable_levels"]]
  stratum_variable_b_labels <- get_variable_labels(stratum_variable_b_name)[["variable_labels"]]
  
  if (person_analysis){
      original_data_raw  <- targets::tar_read(bipartite_graph_coverage) %>%
                                activate(nodes) %>%
                                filter(type == TRUE) 
      
      simulated_data_raw <- targets::tar_read(bipartite_graph_coverage_sim) %>%
                                activate(nodes) %>%
                                filter(type == TRUE) 
  } else {
      original_data_raw  <- targets::tar_read(bipartite_graph_coverage) %>%
                                activate(edges) 
      
      simulated_data_raw <- targets::tar_read(bipartite_graph_coverage_sim) %>%
                                activate(edges)
  }
  

  
  
  
  original_data <- original_data_raw %>%
                            data.frame() %>%
                            mutate(overall = "overall") %>%
                            mutate(
                              level           = {{variable}},
                              stratum_a       = {{stratum_variable_a}},
                              stratum_b       = {{stratum_variable_b}}
                            ) %>%
                            mutate(
                              level = factor(level, variable_levels, variable_labels),
                              stratum_a = factor(stratum_a, stratum_variable_a_levels, stratum_variable_a_labels),
                              stratum_b = factor(stratum_b, stratum_variable_b_levels, stratum_variable_b_labels)
                            ) %>%
                            group_by(level, stratum_a, stratum_b) %>%
                            summarize(count = n()) %>%
                            ungroup() %>%
                            group_by(stratum_a, stratum_b) %>%
                            mutate(proportion = count / sum(count)) 
  
    simulated_data <-   simulated_data_raw %>%
                            data.frame() %>%
                            mutate(overall = "overall") %>%
                            data.frame() %>%
                            mutate(
                              level           = {{variable}},
                              stratum_a       = {{stratum_variable_a}},
                              stratum_b       = {{stratum_variable_b}}
                            ) %>%
                            mutate(
                              level = factor(level, variable_levels, variable_labels),
                              stratum_a = factor(stratum_a, stratum_variable_a_levels, stratum_variable_a_labels),
                              stratum_b = factor(stratum_b, stratum_variable_b_levels, stratum_variable_b_labels)
                            ) %>%
                            group_by(rep, level, stratum_a, stratum_b) %>%
                            summarize(count = n()) %>%
                            ungroup() %>%
                            group_by(rep, stratum_a, stratum_b) %>%
                            mutate(proportion = count / sum(count)) %>%
                            ungroup() %>%
                            group_by(stratum_a, stratum_b, level) %>%
                            summarize(
                                      count_mean = mean(count), 
                                      count_ci_lb = quantile(count, 0.025),
                                      count_ci_ub = quantile(count, 0.975),
                                      proportion_mean = mean(proportion),
                                      proportion_ci_lb = quantile(proportion, 0.025),
                                      proportion_ci_ub = quantile(proportion, 0.975)
                                        )
    
    
    original_data %>%
      left_join(simulated_data) %>%
      arrange(stratum_a, stratum_b, level) %>%
      mutate(
        variable = variable_name,
        strata_a = stratum_variable_a_name,
        strata_b = stratum_variable_b_name) %>%
      ungroup() %>%
      select(variable, strata_a, strata_b, names(.)) 
  
}

make_2_way_table                <- function(variable = overall, stratum_variable = overall, person_analysis = TRUE){
  
  make_3_way_table({{variable}}, {{stratum_variable}}, person_analysis = person_analysis) %>%
    select(-stratum_b, -strata_b) %>%
    rename(stratum = stratum_a, strata = strata_a)
}

make_1_way_table                <- function(variable = overall, person_analysis = TRUE){
  
  make_2_way_table({{variable}}, person_analysis = person_analysis) %>%
    select(-stratum, -strata)
}

make_coverage_table_sim         <- function(intervention_priority_input = "contact", intervention_stratification_input = "overall"){


  
  
    targets::tar_read(intervention_coverage_data_sim)[["place_coverage"]] %>%
    filter(
      intervention_priority == intervention_priority_input, 
      intervention_stratification == intervention_stratification_input
      ) %>%
    mutate(level = intervention_contact_place) %>%
        group_by(intervention_priority, intervention_ranking, intervention_stratification) %>%
    summarize(
              mean_count = mean(count), 
              count_ci_lb = quantile(count, 0.025), 
              count_ci_ub = quantile(count, 0.975),
              mean_proportion = mean(proportion),
              proportion_ci_lb = quantile(proportion, 0.025),
              proportion_ci_ub = quantile(proportion, 0.975),
              mean_cum_prop = mean(cum_prop),
              cum_prop_ci_lb = quantile(cum_prop, 0.025),
              cum_prop_ci_ub = quantile(cum_prop, 0.975)
              ) %>%
    ungroup() %>%
    mutate(level = as.character(level)) %>%
    arrange(-count) %>%
    mutate(level = factor(level, unique(.$level) ))

}

make_coverage_table             <- function(intervention_priority_input = "contact", intervention_stratification_input = "overall"){
  targets::tar_read(intervention_coverage_data)[["place_coverage"]] %>%
    filter(
      intervention_priority == intervention_priority_input, 
      intervention_stratification == intervention_stratification_input
      ) %>%
    mutate(level = intervention_contact_place) %>%
        ungroup() %>%
    mutate(level = as.character(level)) %>%
    arrange(-count) %>%
    mutate(level = factor(level, unique(.$level) ))

}

make_contact_matrix_table       <- function(variable){
  variable <- enquo(variable)
  
  variable_name <- quo_name(variable)
  
  
  data <- targets::tar_read(bipartite_graph) %>%
  filter(!(demo_group %in% c("missing", "other")) | !type) %>%
                    igraph::bipartite.projection(which = "true") %>%
                    as_tbl_graph(directed = FALSE) %>%
                    mutate(connection_var = {{variable}}) %>%
    mutate(connection_var = factor(connection_var, get_variable_labels(variable_name)[["variable_levels"]], get_variable_labels(variable_name)[["variable_labels"]])) %>%
                    activate(edges) %>%
                    mutate(
                      from_level = .N()$connection_var[from], 
                      to_level = .N()$connection_var[to]) %>%
                    data.frame() 

conditional <- data %>%
                    group_by(from_level, to_level) %>%
                    summarize(weight = sum(weight)) %>%
                    group_by(from_level) %>%
                    mutate(conditional = weight / sum(weight))

marginal <- data %>%
                    group_by(to_level) %>%
                    summarize(weight = sum(weight)) %>%
                    mutate(marginal = weight / sum(weight))

conditional %>%
  left_join(marginal, by = c("to_level")) %>%
  mutate(bias = conditional / marginal ) %>%
  ungroup()
}

make_network_impact_table       <- function(){
    targets::tar_read(graph_evolution_data) %>%
          dplyr::transmute(
                    intervention_ranking, 
                    n_lcc                       = mean_n_lcc, 
                    n_remainder                 = mean_n_remainder, 
                    n_singleton                 = mean_n_singleton, 
                    intervention_priority, 
                    intervention_stratification
                    ) %>%
          tidyr::pivot_longer(cols = c(n_lcc, n_remainder, n_singleton))
      }

plot_network_impact             <- function(data){
  data %>%
    ggplot2::ggplot() +
    ggplot2::geom_bar(
                      aes(x = intervention_ranking, y = value, fill = name), 
                      stat = "identity", 
                      position = "fill"
                      ) +
    ggplot2::facet_grid(intervention_stratification ~ intervention_priority)
}







```

```{r plot_code}

make_bar_plot                 <- function(data){
  
  ggplot2::ggplot(data) + 
      ggplot2::geom_bar(
                        aes(x = level, fill = level, y = proportion), 
                        width = 1, 
                        stat = "identity", 
                        color = "black"
                        ) + 
      ggplot2::geom_text(
                        aes(x = level, y = proportion + 0.05, label = count), 
                        alpha = 0.7
                        ) +
      ggplot2::theme_void() + 
      ggplot2::scale_x_discrete(
                                drop = FALSE
                                ) +
      ggplot2::scale_y_continuous(
                                  "Proportion of participants", 
                                  labels = scales::percent
                                  )
}

make_coverage_plot            <- function(data){
  
  data %>%
    ggplot2::ggplot() + 
    ggplot2::geom_bar(
                      aes(x = level, 
                          fill = group, 
                          y = proportion
                          ), 
                      width = 1, 
                      stat = "identity", 
                      color = "black"
                      ) + 
    ggplot2::theme_void() + 
    ggplot2::scale_x_discrete(
                              ) +
    ggplot2::scale_y_continuous(
                                "Proportion of participants", 
                                labels = scales::percent
                                ) + 
    ggplot2::theme(
                    axis.text = element_text(),
                    axis.text.x = element_text(angle = 90),
                    panel.grid.major.y = element_line()
                    )

}

make_one_stratum_radar_plot   <- function(data){
  
  data_n_counts <- data %>%
                        dplyr::group_by(stratum) %>%
                        dplyr::summarize(n = sum(count))
  
  
  data %>%
    dplyr::mutate(prop_label = scales::percent(proportion, accuracy = 1)) %>%
    ggplot2::ggplot() +
    ggplot2::geom_bar(
            aes(x = level, y = proportion, fill = level), 
            stat   = "identity", 
            width  = 1, 
            color  = "black"
            ) +
    ggplot2::geom_text(
            aes(x = 0, y = -0.8, label = paste("n =", n)), 
            data  = data_n_counts, 
            size  = 5
            ) +
    ggplot2::geom_text(
              aes(label = prop_label, x = level, y = proportion + 0.3), 
              size  = 3, 
              face  = "bold", 
              alpha = 0.7
              ) +
    ggplot2::facet_grid( . ~ stratum, switch = "y") +
    ggplot2::coord_polar(clip = FALSE) +
    ggplot2::theme_void() +
    ggplot2::theme(
                  legend.position = "bottom",
                  strip.text      = element_text( hjust = 0.5),
                  strip.text.y    = element_text(),
                  plot.title      = element_text(hjust = 0.5),
                  plot.subtitle   = element_text(hjust = 0.5, margin = margin(1, 0, 15, 0, "mm")),
                  plot.caption    = element_text( hjust = 0)
                  ) +
    ggplot2::scale_y_continuous(breaks = c(0,0.25, 0.50, 1), limits = c(-0.8, 1))
}

make_two_stratum_radar_plot   <- function(data){
    
  
  data_n_counts <- data %>%
                        dplyr::group_by(stratum_a, stratum_b) %>%
                        dplyr::summarize(n = sum(count))
  
    
    data %>%
      dplyr::mutate(prop_label = scales::percent(proportion, accuracy = 1)) %>%
      ggplot2::ggplot() +
      ggplot2::geom_bar(aes(x = level, y = proportion, fill = level), stat = "identity", width = 1, color = "black") +
      ggplot2::geom_text(aes(x = 0, y = -0.8, label = paste("n =", n)), data = data_n_counts, size = 5) +
      ggplot2::geom_text(aes(label = prop_label, x = level, y = proportion + 0.3), size = 3, face = "bold", alpha = 0.7) +
      ggplot2::facet_grid( stratum_a ~ stratum_b, switch = "y") +
      ggplot2::coord_polar(clip = FALSE) +
      ggplot2::theme_void() +
      ggplot2::theme(
            legend.position = "bottom",
            strip.text    = element_text( hjust = 0.5),
            strip.text.y  = element_text(),
            plot.title    = element_text(hjust = 0.5),
            plot.subtitle = element_text(hjust = 0.5, margin = margin(1, 0, 15, 0, "mm")),
            plot.caption  = element_text( hjust = 0)
           ) +
    ggplot2::scale_y_continuous(breaks = c(0,0.25, 0.50, 1), limits = c(-0.8, 1))
}

make_grouped_radar_plot       <- function(data){
  data %>%
      dplyr::filter(!is.na(stratum)) %>%
      ggplot2::ggplot() +
      ggplot2::geom_bar(
                        aes(x = level, y = proportion, fill = level), 
                        stat = "identity",
                        width = 1, 
                        color = "black"
                        ) +
      ggplot2::facet_wrap(. ~ stratum) +
      ggplot2::coord_polar() +
      ggplot2::theme_void()  +
      ggplot2::scale_y_continuous(breaks = c(0,0.25, 0.50, 1), limits = c(-0.8, 1))
}

make_map_coverage_plot        <- function(data){
  
  map_object <- mpxnyc::community_sf_obj %>%
                    dplyr::rename(level = 1) %>%
                    dplyr::left_join(data) 
                  
  map_object %>%
        ggplot() +
          geom_sf(fill = "grey") +
          geom_sf(aes(fill = group), color = "black") +
          theme_void() +
          theme(
            axis.text = element_blank(),
            legend.position = "bottom"
            ) 
  }

plot_place_network_matrix     <- function(data){
  
   data_tiles <- mpxnyc::community_sf_obj %>%
                     dplyr::transmute(to = community, from = community) %>%
                     tidyr::expand(to, from)
   
   
  data %>% 
    ggplot2::ggplot() +
    ggplot2::geom_point(
              aes(y =from, x = to), 
              data = data_tiles, 
              color = "white"
              ) +
    ggplot2::geom_point(
              aes(y =from, x = to, size = weight), 
              color = "black", 
              alpha = 0.5
                ) +
    ggplot2::theme_void() +
    ggplot2::theme(
                  axis.text        = element_text(size = 7, color = "black"),
                  axis.text.x      = element_text(angle = 90),
                  axis.title       = element_text(),
                  axis.title.y     = element_text(angle = 90),
                  legend.position  = "none"
                  ) +
  ggplot2::scale_x_discrete(
                            "Destination community district", 
                            position = "top"
                            ) +
  ggplot2::scale_y_discrete(
                            "Home community district",  
                            limits=rev
                            ) 
}

plot_place_network_viz        <- function(data){
  
    graph_object <- targets::tar_read(bipartite_graph) %>%
                          igraph::bipartite_projection(which = "false") %>%
                          tidygraph::as_tbl_graph() %>%
                          dplyr::rename(level = name) %>% 
                          dplyr::left_join(data) %>%
                          dplyr::select(level, group) %>%
                          dplyr::mutate(deg = igraph::degree(.)) %>%
                          dplyr::filter(deg > 0) %>%
                          dplyr::filter(!is.na(group)) %>%
      tidygraph::activate(edges) %>%
      dplyr::mutate(group_from = .N()$group[from], group_to = .N()$group[to]) %>%
      dplyr::mutate(outer_edges = group_from == "Group C" | group_to == "Group C")
    
    ggraph(graph_object) +
      geom_edge_link( aes(linewidth = weight), alpha = 0.3, , linewidth = 0.1) +
      geom_node_point(aes(color = group, filter = group %in% c("Group C") ), size = 2) +
      geom_edge_link( aes(linewidth = weight, filter = !outer_edges), alpha = 0.1) +
      geom_node_label(aes(label = level , fill = group, size = deg, filter = group %in% c("Group A", "Group B")),  color = "white") +
      theme_void() +
      scale_color_manual(values = c("Group A" = dark_pink, "Group B" = dark_blue, "Group C" = "grey")) +
       scale_fill_manual(values = c("Group A" = dark_pink, "Group B" = dark_blue, "Group C" = "grey")) +
      scale_linewidth_continuous() +
      theme(
        legend.position = "none",
        plot.margin = margin(0,0,0,0, "cm"),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        plot.caption = element_text(hjust = 0)
      ) 
  
}

plot_heatmap_contact          <- function(data){

   
  
  data %>%
    ggplot() +
    geom_tile(aes(y = from_level, x = to_level, fill = bias), color = "black") +
    theme_void() +
    theme(
      axis.text.x = element_text(),
      axis.text.y = element_text(),
      axis.title = element_blank()
    ) +
    scale_x_discrete(drop = FALSE) +
    scale_x_discrete(drop = FALSE) 
}




```

# People

## 

```{r plot_bar_demogroup}
#| fig-width: 11
#| fig-height: 7




make_1_way_table(demo_group) %>%    
  make_bar_plot() %>%
  add_caption("bar_demo_group") %>%
  apply_style_bar_plot()


```

## 

```{r plot_bar_age}
#| fig-width: 7
#| fig-height: 7


make_1_way_table(age) %>%
    make_bar_plot() %>%
    add_caption("bar_age") %>%
    apply_style_bar_plot()

```

## 

```{r plot_bar_channel}
#| fig-width: 7
#| fig-height: 7

#| 


make_1_way_table(channel) %>%
  make_bar_plot() %>%
  add_caption("bar_channel") %>%
  apply_style_bar_plot()


```

## 

```{r plot_bar_gender}
#| fig-width: 9
#| fig-height: 7

#| 




make_1_way_table(genderId) %>%  
  make_bar_plot() %>%
  add_caption("bar_gender") %>%
  apply_style_bar_plot()
 
```

## 

```{r plot_bar_race}
#| fig-width: 7
#| fig-height: 7

#| 





  make_1_way_table(race) %>%
      make_bar_plot() %>%
      add_caption("bar_race") %>%
      apply_style_bar_plot()
  
```

## 

```{r plot_bar_sexorientation}
#| fig-width: 7
#| fig-height: 7

#| 



make_1_way_table(sexOrientation) %>%    
  make_bar_plot() %>%
  add_caption("bar_sex_orientation") %>%
  apply_style_bar_plot()


```

## 

```{r plot_radar_grid_sexOrientation_demo_group}
#| fig-width: 7
#| fig-height: 10

make_2_way_table(sexOrientation, demo_group) %>%
  make_grouped_radar_plot() %>%
  add_caption("radar_sexOrientation_demo_group") %>%
  apply_style_radar_grid_plot()

```

## 

```{r plot_radar_grid_monkeypoxVaccine_demo_group}
#| fig-width: 7
#| fig-height: 10

make_2_way_table(monkeypoxVaccine, demo_group) %>%
  make_grouped_radar_plot() %>%
  add_caption("radar_monkeypoxVaccine_demo_group") %>%
  apply_style_radar_grid_plot()

```

## 

```{r plot_radar_grid_hivPrep_demo_group}
#| fig-width: 10
#| fig-height: 10

make_2_way_table(hivPrep, demo_group) %>%
  make_grouped_radar_plot() %>%
  add_caption("radar_hivPrep_demo_group") %>%
  apply_style_radar_grid_plot()

```

## 

```{r plot_bar_groupsex}
#| fig-width: 7
#| fig-height: 7
#| 

make_1_way_table(groupSex) %>%  
  make_bar_plot() %>%
  apply_style_bar_plot()

```

# Places

## 

```{r plot_radar_facet_placetype_placesex}
#| fig-width: 9
#| fig-height: 8
#| 





  make_2_way_table(placeType, placeSex, person_analysis = FALSE) %>%
        filter(!is.na(level)) %>%
        make_one_stratum_radar_plot() %>%
        add_caption("radar_placetype_placesex") %>%
        apply_style_rdar_facet_plot()





```

## 

```{r plot_radar_facet_placetype_distancefromhome}
#| fig-width: 9
#| fig-height: 8
#| 





make_2_way_table(placeType, distanceFromHome, person_analysis = FALSE) %>%
          filter(!is.na(level)) %>%
  make_one_stratum_radar_plot() %>%
  apply_style_rdar_facet_plot()



```

## 

```{r plot_radar_facet_placetype_placesex_distancefromhome}
#| fig-width: 11
#| fig-height: 10
#| 


  make_3_way_table(placeType, placeSex, distanceFromHome, person_analysis = FALSE) %>%
    filter(!is.na(level)) %>%
  make_two_stratum_radar_plot() %>%
  add_caption("radar_placetype_sex_distance") %>%
  apply_style_rdar_facet_plot()

```

# People Mixing through Places

## 

```{r plot_matrix_mixing_age}
#| fig-width: 10
#| fig-height: 10


make_contact_matrix_table(age) %>%
  plot_heatmap_contact() %>%
  add_caption("radar_hivPrep_demo_group") %>%
  apply_style_spacing_heatmap()



```

## 

```{r plot_matrix_mixing_demo_group}
#| fig-width: 10
#| fig-height: 10


make_contact_matrix_table(demo_group) %>%
  plot_heatmap_contact() %>%
  add_caption("radar_hivPrep_demo_group") %>%
  apply_style_spacing_heatmap()



```

## 

```{r plot_matrix_mixing_sexorientation}
#| fig-width: 10
#| fig-height: 10


make_contact_matrix_table(sexOrientation) %>%
  plot_heatmap_contact() %>%
  add_caption("radar_hivPrep_demo_group") %>%
  apply_style_spacing_heatmap()



```

# Places connecting through People

## 

```{r plot_netviz_places}
#| fig-width: 9
#| fig-height: 9


make_coverage_table(intervention_priority = "contact", intervention_stratification = "overall") %>%
  plot_place_network_viz() %>%
  add_caption("networkcoverage") 
  
```

## 

```{r plot_matrix_movement_travel}
#| fig-width: 9
#| fig-height: 11


  make_commuting_network_data() %>%
    plot_place_network_matrix() %>%
    add_caption("matrix_places") %>%
    apply_style_spacing_remainder()
  
  

```


## 

```{r plot_matrix_movement_coattendance}
#| fig-width: 9
#| fig-height: 11


  make_coattendance_network_data() %>%
    plot_place_network_matrix() %>%
    add_caption("matrix_places") %>%
    apply_style_spacing_remainder()
  
  

```


# Interventions

## 

```{r plot_map_coverage}
#| fig-width: 7
#| fig-height: 10

make_coverage_table(intervention_priority = "contact", intervention_stratification = "overall") %>%
  make_map_coverage_plot() %>%
  add_caption("map_coverage") %>%
  apply_style_spacing_coverage(caption_hjust = 0)


```

## 

```{r plot_bar_coverage}
#| fig-width: 14
#| fig-height: 7


make_coverage_table(intervention_priority = "contact", intervention_stratification = "overall") %>%
    make_coverage_plot() %>%
    add_caption("bar_age") %>%
    apply_style_spacing_coverage()

```

## 

```{r plot_net_impact}
#| fig-width: 7
#| fig-height: 7


make_network_impact_table() %>%
    plot_network_impact() %>%
    add_caption("bar_age") %>%
    apply_style_spacing_descriptives()


```

