

## Spatial mixing 


### Age {.unnumbered}

::: {.panel-tabset}
#### Spatial mixing coefficient
{{< include ___figures/fig-age-mixing-matrix.qmd >}}


#### Gathering and residence maps

```{r }
#| fig-width: 5
#| fig-height: 5
#| fig-cap: Community districts reported by participants in the age group of interest as places of residence or gathering were ranked by frequency and divided into three groups, each representing approximately one third of all reported locations. Group A contains the most frequently reported districts, followed by Groups B and C.



targets::tar_read(plotdata_place_census_age)  |> 
  plot_placecensus_map() +
  scale_fill_mpxnyc(name = "", na.translate = FALSE, option = "light") +
  theme_mpxnyc_blank(
                      legend.position = "bottom", 
                      strip.text.y.left = ggplot2::element_text(size = 14, angle = 65, margin = ggplot2::margin(0,0,0,0), color = "#636363"),
                      strip.clip = "off"
                      )  
```
:::


### Sexual orientation  {.unnumbered}


::: {.panel-tabset}
#### Spatial mixing coefficient
{{< include ___figures/fig-sexorientation-mixing-matrix.qmd >}}

#### Gathering and residence maps


```{r }
#| fig-width: 5
#| fig-height: 5
#| fig-cap: Community districts reported by participants in the sexual-orientation group of interest as places of residence or gathering were ranked by frequency and divided into three groups, each representing approximately one third of all reported locations. Group A contains the most frequently reported districts, followed by Groups B and C.


targets::tar_read(plotdata_place_census_sexorientation)  |> 
  plot_placecensus_map() +
  scale_fill_mpxnyc(name = "", na.translate = FALSE, option = "light") +
  theme_mpxnyc_blank(
                      legend.position = "bottom", 
                      strip.text.y.left = ggplot2::element_text(size = 14, angle = 65, margin = ggplot2::margin(0,0,0,0), color = "#636363"),
                      strip.clip = "off"
                      )  

 
```




:::

### Race and gender modality {.unnumbered}

::: {.panel-tabset}
#### Spatial mixing coefficient

{{< include ___figures/fig-racegender-mixing-matrix.qmd >}}



#### Gathering and residence maps

```{r }
#| fig-width: 5
#| fig-height: 5
#| fig-cap: Community districts reported by participants in the race and gender group of interest as places of residence or gathering were ranked by frequency and divided into three groups, each representing approximately one third of all reported locations. Group A contains the most frequently reported districts, followed by Groups B and C.



targets::tar_read(plotdata_place_census_racegender)  |> 
  plot_placecensus_map() +
  scale_fill_mpxnyc(name = "", na.translate = FALSE, option = "light") +
  theme_mpxnyc_blank(
                      legend.position = "bottom", 
                      strip.text.y.left = ggplot2::element_text(size = 14, angle = 65, margin = ggplot2::margin(0,0,0,0), color = "#636363"),
                      strip.clip = "off"
                      )  

```



:::