## Preliminaries

### Person-place network

We define the MPX NYC spatial participant graph as

$$
G(N, \psi) 
\text{ where } \psi:N\times N \rightarrow \mathbb{N}_0
$$

$N$ is a set containing node indices and $\psi$ (the adjacency function for $G$) is a mapping from each possible pair of nodes to the set of non-negative integers. $\psi(a,b) = 0$ when there is no edge between distinct nodes $a,b \in N$ and $\psi(a,b) > 0$ if there is. By definition, a node cannot have an edge with itself. i.e. $\psi(a,a) = 0$ $\forall a \in N$.

In the MPX NYC spatial participant graph, nodes can be partitioned into a set of study participants $N_p$ and a set of community districts $N_c$. i.e.

$$
N_p \cup N_c = N \text{ and }  N_p \cap N_c = \emptyset
$$

Each individual participant can have a relation with any number of community districts, but not with another participant. Similarly, each community district can have a relation with multiple participants, but not with another community district. i.e.:

$$
\psi(a,b) > 0 \Rightarrow a\in N_p, b\in N_c
$$ Finally, we define $M$ as a $q \times r$ weighted adjacency matrix for $G$ where $q = |N_p|$ and $r = |N_c|$. The $ij^{th}$ entry of $M$ is

$$
m^{ij} = \psi(i,j)
$$

In this mathematical description, we assume that there can only be one edge between a pair of nodes. In the MPX NYC data, it is possible for there to be more than one relation between a specific pair of nodes. We bridge this gap by assigning the count of relations in MPX NYC study data as an edge weight in the mathematical description. i.e In the case where participant $a \in N_p$ has $r$ relations with community district $c \in N_c$, there is only one edge $(a,c)$ in $G$ and the weight of that edge equals the count of relations ($\psi(a,c) = r$).

The MPX NYC spatial participant graph meets the definition for a bipartite graph. This allows us to easily derive two related graphs - the bipartite projection onto participant nodes $G_p(N_p,\psi_p)$, and the bipartite projection onto community district nodes $G_c(N_c,\psi_c)$. The former graph is used to represent the MPX NYC participant network, and the latter is used to represent the MPX NYC community district network. Both are defined below.

### Participant network

We define the MPX NYC participant graph as

$$
G_p(N_p, \psi_p)  \text{ where } \psi_p:N_p\times N_p \rightarrow \mathbb{N}_0 
$$

$N_p$ is a set containing node indices for participant nodes and $\psi_p$ is a mapping from each possible pair of participants to the set of non-negative integers. $\psi_p(a,b) = 0$ when there is no edge between distinct participants $a$ and $b$ and $\psi_p(a,b) > 0$ if there is. By definition, a node cannot have a tie with itself. i.e. $\psi_p(a,a) = 0$ $\forall a \in N_p$.

$G_p(N_p, \psi_p)$ can be derived from $G$ by taking the product of the $q \times r$ adjacency matrix $M$ with its transpose:

$$
M_p = MM^T
$$

The result is a $q \times q$ adjacency matrix $M_p$ whose entries $m_p^{ij}$ are used to define $\psi_p$:

$$
\psi_p(i,j) = m_p^{ij}
$$

### Community district network

We define the MPX NYC community district graph as

$$
G_c(N_c, \psi_c)  \text{ where }  \psi_c:N_c\times N_c \rightarrow \mathbb{N}_0 
$$

where $N_c$ is a set containing node indices for community district nodes and $\psi_c$ is a mapping from each possible pair of community districts to the set of non-negative integers. $\psi_c(a,b) = 0$ when there is no edge between community districts $a$ and $b$ and $\psi_c(a,b) > 0$ if there is. By definition, a node cannot have a tie with itself. i.e. $\psi_c(a,a) = 0$ $\forall a \in N_c$.

$G_c(N_c, \psi_c)$ can be derived from $G$ by taking the product of the $r \times q$ matrix $M^T$ with its transpose:

$$
M_c = M^TM
$$

The result is a $r \times r$ matrix $M_c$, whose entries $m^{ij}_c$ are used to define $\psi_c$:

$$
\psi_c(i,j) = m_c^{ij}
$$

for $a \in N_p^*$ and $b \in N_c$.

In $G(N^*, \psi^*)$, individuals are batched into equal groups. Each group represent a repetition of the bootstrap procedure. Then for a given statistic, statistical inference is implemented by calculating the statistic separately in each of these groups and treating the result as a random realization from the distribution of that particular statistic.

