

# Discussion {#sec-discussion}

- How do people move?
- Why do they move that way?
- Who are these people?
- Notes on community
- Notes on mpox transmission
- Notes on covid and the coming pandemics

Join us

The spatial mixing coefficient is related to ideas in the social network analysis literature. The coefficient of a given subgroup for itself indicates homophily when it is positive, and heterophily when it is negative. In the case of heterophily, it shows which other subgroups members of a given subgroup tend to be connected with. The measure also relates to the literature on compartmental infectious disease models (SIR models). When it is zero, the spatial mixing coefficient indicates random mixing in the population.

### Main results {.unnumbered}

### Contributions to social network epidemiology {.unnumbered}

### Contributions to spatial epidemiology {.unnumbered}

### Another application: understanding the role of schools in the rapid dissemination of pathogens {.unnumbered}

-   understanding the movement of children from their homes to school to activities can help to explain the role of schools in shaping the speed and frequency of future covid outbreaks.
-   this understanding can also help to guide control efforts that minimize the impact of intervention on learning (learning loss)

### Future direction: assessing access to services by integrating location of contact with healthcare providers {.unnumbered}
