#### Counterfactual data model


We define counterfactual outcomes $Y_1^{(a_1, \mathbf{a}_{\mathscr{N}_1})}$, $Y_2^{(a_2, \mathbf{a}_{\mathscr{N}_2})}$, and $Y_3^{(a_3, \mathbf{a}_{\mathscr{N}_3})}$, which represent the level of job opportunities, *Persons 1*, *2*, and *3*, would have if we set their dress to level $a_1$, $a_2$, and $a_3$, respectively. Then the model for counterfactual variable is given by @eq-homogenous-interference-swig. It is represented using a SWIG in @fig-homogenous-interference-swig.

Note that because of the assumption of network interference, the counterfactual outcome for *Person 1* is a function of *Person 2*'s treatment value and vice versa. The counterfactual outcome for *Person 3*, on the other hand, is a function of *Person 3*'s treatment ($a_3$) alone. This is because $\mathscr{N}_1 = \{2\}$, $\mathscr{N}_2 = \{1\}$, and $\mathscr{N}_3 = \{\}$, according to Example 2.

To ensure that counterfactual outcomes are well-defined for all experimental units, we make the assumption of positivity:

$$
0 < P[A_i = a_i,  h_Y (\mathbf{A}, \Psi_i) =  h_Y(\mathbf{a}, \Psi_i)| L_i,g_{A}(\mathbf{L}, \Psi_i) ] < 1
$$
for all $\mathbf{a} \in \{0,1\}^n$


{{< include __figures/fig-homogenous-interference-swig.qmd >}} 

{{< include __equations/eq-homogenous-interference-swig.qmd >}}
