## Social and Spatial Network Analysis with Causal Interpretation {.unnumbered}

The **Social and Spatial Network Analysis with Causal Interpretation (SSNAC)** framework can be used to guide the collection, management, analysis, and causal interpretation of data. It offers guidance on conceptualizing and organizing spatial and social data as networks (see @sec-appendix-social-spatial) and provides tools for descriptive (see @sec-appendix-analysis) and causal analysis.

We define SSNAC as a set of straightforward extensions of the currently dominant framework for conducting causal inference with observational data in epidemiology. We begin by giving an overview of this approach, which we will call [classic causal inference](#sec-classical-causal-inference). We extend this system to situations where data are characterized by *interdependence* of observational units rather than independence in the [social networks](#sec-network-causal-inference) section. Finally, we accommodate social and spatial data simultaneously in the [social–spatial networks](#sec-social-spatial-networks) section. In each case, we describe the assumptions and implications of each system, illustrating with worked examples.

> “We re-frame the task of statistical inference from that of learning from a growing collection of identically distributed random vectors to that of learning from a growing random vector whose entries are related through a causal structure. These assumptions allow our estimates to benefit from having more observational units, even if they collectively contribute to one realization of the statistical model.”


#### Classic causal inference {.unnumbered}

Classic causal inference, as elaborated by Robins [-@robins1986], Hernán and Robins [-@hernan2021], and others, sharpens epidemiologic reasoning by providing a template for conducting thought experiments about population health. Typically, the researcher reasons about the likely effect of some hypothetical intervention on an outcome in a defined population. They define a set of **causal estimands**—quantities that describe how the outcome would differ under the intervention—and, through transparent statistical assumptions, express those estimands in terms of quantities we can calculate using observed data.

For example, consider a hypothetical intervention where every person in the United States receives free, unlimited access to healthcare. Under classic causal inference, we can ask whether the prevalence of diabetes would change if we implemented such an intervention. We can even ask about the extent of change and estimate that using data that have already been observed. The classic causal inference framework allows this by:

- making causal assumptions about the relationship between healthcare access, diabetes prevalence, and any factors that determine both
- mathematically defining the hypothetical quantities of interest and expressing them in terms of estimable quantities
- estimating those quantities using data we have collected (or can collect)



#### Independence {.unnumbered}

A strong assumption made often by practitioners of classic causal inference is that of **independence** between observational units or groups of observational units. This assumption simplifies the mathematics involved in estimating quantities from data, but it also has profound implications for how we think about the causal process under study.

In our opening example, the independence assumption holds that one person’s access to healthcare does not affect any other person’s diabetes status. It would imply that the diabetes status for a married man who does not know how to cook would not be affected by improvements in health literacy experienced by his wife who shops and cooks for the household. This assumption runs counter to our intuitions about social life. Humans are deeply networked—our lives are defined by our relationships with one another.



#### Homogeneity {.unnumbered}

Accompanying the independence assumption are implicit or explicit assumptions about the **homogeneity** of the causal process under study. Consider two people, Tumi and Thabo, who each toss the same coin once at time 1 and again at time 2. Depending on our homogeneity assumptions, we could say that we are conducting:

- one experiment called *“coin toss”* and repeating it four times  
- two experiments called *“coin toss by Thabo”* and *“coin toss by Tumi”* and repeating each experiment twice  
- two experiments called *“coin toss at time 1”* and *“coin toss at time 2”* and repeating each experiment twice  
- four experiments called *“coin toss by Thabo at time 1”*, *“coin toss by Thabo at time 2”*, *“coin toss by Tumi at time 1”*, and *“coin toss by Tumi at time 2”* and not repeating any of them.

The choice among these interpretations turns on the experimenter’s prior beliefs: Does the likelihood of a head or tail change over time? Does it change based on who tosses the coin? Such considerations are routine in statistical modeling of longitudinal data. A question researchers do not often ask, however, is whether one person’s coin toss affects another’s.


#### Interdependence {.unnumbered}

Now consider the experiment *“Thabo tosses a coin, then Tumi tosses the coin, then Thabo tosses the coin again, then Tumi tosses the coin again.”* Whereas in the above listing we implicitly assumed that each coin toss was self-contained, this sequence accommodates the possibility that the outcomes of Thabo and Tumi’s coin tosses might be causally related.

We can quantitatively assess this possibility by repeating the sequence many times and computing the correlation coefficient between the outcomes of Thabo and Tumi’s tosses. Without explicitly structuring the experiment as a sequence, we have no framework for asking whether their tosses are related.

In epidemiologic practice, the modeling decision to treat individuals or groups as independent is so well-entrenched that it is often presented as a necessary condition for doing valid causal research. Yet with humans—unlike with coins—there is abundant evidence and experience demonstrating that *interdependence is the rule rather than the exception.*



#### Towards a causal inference of dependent happenings {.unnumbered}

Our goal in this appendix and project is to offer ideas and tools for causal inference that allow researchers to *learn from interdependence rather than avoid it* in pursuit of clear causal reasoning. We can have both clarity and an understanding enriched by the analysis of dependent happenings.

In crude terms, our approach involves moving to a framework where, as a rule, we consider Thabo and Tumi’s coin tosses **one experiment**. Rather than define a scalar random variable to represent a measure made on $n$ individuals, we define a **vector-valued random variable** of length $n$ and assume that some of its entries are correlated as a result of being part of the same causal structure.

But why do that when our tools for statistical modeling require as many repetitions as possible for valid inferences? How can we quantify uncertainty when we always have a sample size of one?  

Regarding the first question: we take this approach because it allows us to investigate and quantify causal in<u>ter</u>ference rather than assume it away.  
Regarding the second: SSNAC advocates a shift in perspective.

We re-frame the task of statistical inference from that of learning from a growing collection of identically distributed random vectors to that of learning from a growing random vector whose entries are related through a causal structure. In that causal structure, we distinguish between causal relationships that play out *within* observational units (“structural”) from those that play out *across* them (“relational”), making homogeneity assumptions about each.

We avail ourselves of asymptotic theory by making the assumption of **no spillover** between observational units—a weaker version of the independence assumption. These assumptions allow our estimates to benefit from having more observational units, even if they collectively contribute to one realization of the statistical model.

In the sections that follow, we describe classic causal inference, social network analysis with causal interpretation, and the SSNAC framework, each time discussing their assumptions, causal model, and causal estimands and illustrating a causal identification strategy. Finally, we describe the main analysis of the report, which applies the SSNAC framework to RESPND-MI data.


