#### Observed data model

The causal DANG shown in @fig-placeintervention-dang represents the three week campaign mentioned in Example 3. Let $\mathbf{T}_s$ be a $3\times1$ vector whose entries $T_{sj}$ are 1 if *Neighborhood* $j$ is to be vaccinated at time $s$ and $0$ otherwise. $\mathbf{M}_s$ is a $5\times1$ vector whose entries $M_{si}$ indicate whether the $i^{\text{th}}$ person received a campaign message at time $s$ or not. $\mathbf{V}_s$ is a $5\times1$ vector whose entries $V_{si}$ show whether participant $i$ is vaccinated or not at time $s$. Finally, $\mathbf{R}_s$ is a $3\times1$ vector whose entries $R_{si}$ shows the risk rating of neighborhood $j$ at the beginning of time $s$. @eq-placeintervention-dang specifies this model for *Person* $i$ and *Neighborhood* $j$ at time $s$:



{{< include ___figures/fig-placeintervention-dang.qmd >}} 

{{< include ___equations/eq-placeintervention-dang.qmd >}} 

According to @eq-placeintervention-dang, $R_{sj}$, the risk rating for *Neighborhood* $j$ at time $s$, is a function of $\mathbf{V}_{s-1}$, the vaccination status of every individual at time $s-1$. $T_{sj}$ - an indicator for whether or not *Neighborhood* $j$ conducted a campaign at time $s$, is a function of the risk rating for *Neighborhood* $j$ at time $s$.

$M_{si}$, which indicates whether or not an *Person* $i$ received a campaign message at time $s$, is a function of whether or not person $i$ was vaccinated at time $s-1$, whether they received a campaign message at time $s-1$, and whether or not one of the neighborhoods they live in or visit conducted a campaign at time $s$. The vaccination status of individual $i$ at time $s$ is a function of whether or not they received a campaign message at time $s$ and whether or not they were vaccinated as at time $s-1$.