
```{r}
targets::tar_source("R_functions")
```

### Assumptions

See @sec-network-causal-inference for a fuller description of the below assumptions.

#### Independence assumptions


Under the SSNAC framework, we make the assumption of *no spillover*: contemporaneous measurements on observational units of a given entity type are independent of each other given all prior measures. The time-ordering of the measurements is given by the structural part of the causal DANG. 

We further make the assumption of *network interference* - that interference respects the mapping given by the relational part of a causal DANG. 

#### Homogeneity assumptions

*Identical distribution*: we assume that the structural equations that produce each observational unit's measures are identical across observational units of the same entity type.


*Homogenous interference*: we assume that the exposure mapping for each variable in the model is characterized by homogenous interference. i.e: the exposure mapping is separable, equivalent, symmetric, and bounded.


*Time homogeneity (optional)*: in applications with repeated measures, if the structure of the causal DANG allows, we can make the assumption that the structural equations are identical across time. We apply this assumption in Example 3 below. 


