

#### Observational data

The causal DANG shown in @fig-repeated-observations-dang represents the three week campaign mentioned in Example 3 (we omit the relational part and show only the structural part). Let $\mathbf{T}_s$ be a $3\times1$ vector whose entries $T_{sj}$ are 1 if *Neighborhood* $j$ is to be vaccinated at time $s$ and $0$ otherwise. $\mathbf{M}_s$ is a $5\times1$ vector whose entries $M_{si}$ indicate whether the $i^{\text{th}}$ person received a campaign message at time $s$ or not. $\mathbf{V}_s$ is a $5\times1$ vector whose entries $V_{si}$ show whether participant $i$ is vaccinated or not at time $s$. Finally, $\mathbf{R}_s$ is a $3\times1$ vector whose entries $R_{si}$ shows the risk rating of neighborhood $j$ at the beginning of time $s$. @eq-placeintervention-dang specifies this model for *Person* $i$ and *Neighborhood* $j$ at time $s$:

```{r}
#| fig-width: 8
#| fig-height: 5
#| label: fig-repeated-observations-dang
#| fig-cap: "Causal DANG for Week 1-3 in Example 3"



program_dang() |>
  plot_swig(node_radius = 0.4) +
  scale_fill_mpxnyc(option = "light") +
  theme_mpxnyc_blank()




```

$$
\begin{aligned}
M_{0i} &=  f_{M_0}(U_{M_{0i}}) \\
V_{0i} &=  f_{V_0}(U_{V_{0i}}) \\
R_{sj} &=  f_{R}(U_{R_{sj}}, \mathbf{V}_{s-1}) \\
T_{sj} &=  f_{T}(U_{T_{sj}}, R_{s,j}) \\
M_{si} &=  f_{M} (U_{M_{\{si\}}} , V_{\{s-1,i\}}, M_{\{s-1,i\}}, \mathbf{T}_{\{s,\mathscr{N}_i\}})\\
V_{si} &=  f_{V}(U_{V_{\{si\}}}, M_{\{si\}}, V_{\{s-1,i\}}) \\
\end{aligned}
$$ {#eq-placeintervention-dang}

According to @eq-placeintervention-dang, $R_{sj}$, the risk rating for *Neighborhood* $j$ at time $s$, is a function of $\mathbf{V}_{s-1}$, the vaccination status of every individual at time $s-1$. $T_{sj}$ - an indicator for whether or not *Neighborhood* $j$ conducted a campaign at time $s$, is a function of the risk rating for *Neighborhood* $j$ at time $s$.

$M_{si}$, which indicates whether or not an *Person* $i$ received a campaign message at time $s$, is a function of whether or not person $i$ was vaccinated at time $s-1$, whether they received a campaign message at time $s-1$, and whether or not one of the neighborhoods they live in or visit conducted a campaign at time $s$. The vaccination status of individual $i$ at time $s$ is a function of whether or not they received a campaign message at time $s$ and whether or not they were vaccinated at time $s-1$.
