### Identification

We can start by using the law of iterated expectations:

$$
\begin{aligned}
E \left[ \frac{1}{n} \sum_i Y_i^{(a_i, \mathbf{a}_{\mathscr{N}_i})}  \right] &= E \left[ \frac{1}{n} \sum_i E[Y_i^{(a_i, \mathbf{a}_{\mathscr{N}_i})}  | \mathbf{L}] \right] \\
\end{aligned}
$$ 

Then we can evaluate the inner expectation as follows:


::: aside
**Notes on identification** 

**A**. In the first line, we use the loyalty of the network exposure mapping for $Y_i^{(...)}$ with respect to $\mathbf{L}$ in $\mathscr{G}$ to simplify the conditioning statement.

**B**. In the second line we use the definition of counterfactual variable $Y_i^{(..)}$ given in @eq-homogenous-interference-swig. 

**C**. In the third line, we use the fact that given fixed $\mathbf{L}$, $f_{Y}$ is a function of random variable $U_{Y_i}$. Since $U_{Y_i}$ is independent of $U_{A_i}$ as well as $U_{A_j}$ for $j \in \mathscr{N}_i$, $f_{Y}(...) \perp \mathbf{A} | \mathbf{L}$. 

**D**. In the final line, we use the definition of observed variable $Y_i$ given in @eq-homogenous-dag.
:::


$$
\begin{aligned}
 E[Y_i^{(a_i, \mathbf{a}_{\mathscr{N}_i})} | \mathbf{L}] 
 &=  E[Y_i^{(a_i, \mathbf{a}_{\mathscr{N}_i})}                                  | L_i , g_Y(\mathbf{L}, \Psi_i)]  \\
 &=  E[f_{Y}(U_{Y_i}, L_i,  a_i, g_{Y}(\textbf{L}, \Psi_i),  h_{Y}(\textbf{a}, \Psi_i))   | L_i , g_Y(\mathbf{L}, \Psi_i)]  \\ 
 &=  E[f_{Y}(...)                                                               | L_i , g_Y(\mathbf{L}, \Psi_i), A_i = a_i, h_Y(\textbf{A}, \Psi_i) = h_Y(\textbf{a}, \Psi_i)] \\
 &=  E[Y_i                                                                      | L_i , g_Y(\mathbf{L}, \Psi_i), A_i = a_i, h_Y(\textbf{A}, \Psi_i) = h_Y(\textbf{a}, \Psi_i)] \\
\end{aligned}
$$

We are left with this functional:

$$
E[ \frac{1}{n} \sum_i  E[Y_i |  L_i , g_Y(\mathbf{L}, \Psi_i), A_i = a_i, h_Y(\textbf{A}, \Psi_i) = h_Y(\textbf{a}, \Psi_i) ]]
$$



