
## Places

### Type of venue for contact vs. type of contact 

::: {.panel-tabset}

#### Plot

```{r plot_radar_facet_placetype_placesex}
#| fig-width: 9
#| fig-height: 8
#| 


mpxnyc_colors <- mpxnyc::mpxnyc_colors
attach(mpxnyc_colors)
targets::tar_source(files = "/Users/keletso/Documents/_gitrepos/mpxnyc_data_analysis/R_functions")


make_table_freq2(placeType, placeSex, person_analysis = FALSE) |>
  dplyr::filter(!is.na(level)) |>
  plot_radar_stratified() 

```

#### Data

```{r table_radar_facet_placetype_placesex}
#| fig-width: 9
#| fig-height: 8
#| 

make_table_freq2(placeType, placeSex, person_analysis = FALSE) |>
        draw_table_stratified()


```

:::

###  Type of venue for contact vs. distance from home 

::: {.panel-tabset}

#### Plot

```{r plot_radar_facet_placetype_distancefromhome}
#| fig-width: 9
#| fig-height: 8
#| 





make_table_freq2(placeType, distanceFromHome, person_analysis = FALSE) |>
  plot_radar_stratified() 



```

#### Data

```{r table_radar_facet_placetype_distancefromhome}
#| fig-width: 9
#| fig-height: 8
#| 





make_table_freq2(placeType, distanceFromHome, person_analysis = FALSE) |>
          draw_table_stratified()



```

:::



### Place type vs. Distance from home vs. Sex contact 

::: {.panel-tabset}

#### Plot

```{r plot_radar_facet_placetype_placesex_distancefromhome}
#| fig-width: 11
#| fig-height: 10
#| 


  make_table_freq3(placeType, placeSex, distanceFromHome, person_analysis = FALSE) |>
    dplyr::filter(!is.na(level)) |>
  plot_radar_stratified2() 

```

#### Data

```{r table_radar_facet_placetype_placesex_distancefromhome}
#| fig-width: 11
#| fig-height: 10
#| 


  make_table_freq3(placeType, placeSex, distanceFromHome, person_analysis = FALSE) |>
    draw_table_stratified2()

```

:::



