## Mobilising a rapid and comprehensive community-led response to MPOX: lessons from the RESPND-MI study team
Wordcount: 347 out of 350


Figure/Table Count: 1 out of 2


Keletso Makofane1,2, Jennifer Barnes-Balenciaga1,3, Pedro Carneiro1,4, Nick Diamond1, Dennis Kunichoff1,2, Elle Lett1,5,6, Kenneth H. Mayer1,7,8, Connor Mccombs1,9, Robert Pitts1, Grant Roth1, Martez Smith1,10, Nguyen Tran1,11


1. RESPND-MI Study Team, New York 2. FXB Center for Health and Human Rights, Harvard University, Boston 3. Crystal La’Beija Organizing Fellowship, KBCAN, New York City 4. School of Public Health, City University of New York, New York City 5. Computational Health Informatics, Boston Children’s Hospital, Boston 6. Perelman School of Medicine, University of Pennsylvania, Philadelphia 7. The Fenway Institute, Boston 8. Harvard Medical School, Harvard University, Boston 9. School of Public Health, Boston University, Boston 10. School of Nursing, Rochester University, Rochester 11. School of Medicine, Stanford University, Stanford

#### Presenting Authors
Jennifer Barnes-Balenciaga, Elle Lett

### Background 
Early mpox responses by U.S. public health agencies (PHAs) failed to provide timely vaccination, testing, treatment, and educational materials to the public. Consequently, information about the outbreak, exclusively based on testing data, was unreliable. The RESPND-MI study team (RST) was established to gather actionable data on the social and spatial epidemiology of mpox in New York City (NYC).

### Description 
RST consists of 19 scholar-activists. Starting in May 2022, we prepared a study about sexual activity and mpox symptoms among those most vulnerable to mpox. To promote collective decision making, we organised an online community forum (CF). In the first CF, attendees expressed the need for a space to continually coordinate response efforts across organisations, and to address gaps not immediately met by local and federal public health agencies

CFs thus became weekly calls where participants received epidemiologic updates, discussed problems, and provided input on study design and marketing decisions. From June to September 2022, over 80 activists, community leaders, public health professionals participated in CFs. We produced policy briefs, op-eds, and educational materials; and conducted media outreach. The RST website became a clearing house for community-generated resources, as well as community-generated information on vaccination, testing, and treatment services.

Educational materials and policy recommendations from the CF were adopted by city, state, and federal PHAs. Reporters cited the RST in over 90 press clips. Survey data were used to inform NYC vaccination outreach services.

### Lessons Learnt 
Community-led research efforts can provide useful data in the context of public health emergencies. Consulting diverse stakeholders can improve data quality; whereas the RST initially planned to disseminate an English-only survey for gay and bisexual cis-gender men, CF participants successfully advocated to include trans individuals and to add a Spanish version.

### Conclusions / Next Steps 
Structured community engagement can facilitate comprehensive responses to novel public health threats. Facilitating spaces for community members to discuss challenges can yield creative solutions that tackle multiple aspects of an emergency, identifying otherwise obscured problems and exploiting the collective strengths of all organisations and individuals in the coalition. To prepare for future outbreaks, PHAs should invest resources in platforms that enable such engagement.

## A limited number of census tracts are associated with greatest risk for MPOX transmission: Implications for outbreak management
Wordcount: 297 out of 300

Figure/Table Count: 1 out of 2


Keletso Makofane1,2, Jennifer Barnes-Balenciaga1,3, Pedro Carneiro1,4, Nick Diamond1, Dennis Kunichoff1,2, Elle Lett1,5,6, Kenneth H. Mayer1,7,8, Connor Mccombs1,9, Cody Nolan1, Joe Osmundson1,10, Robert Pitts1, Grant Roth1, Sudipta Saha1,2,11, Martez Smith1,12, Nguyen Tran1,13, Antón Castellanos Usigli1

1. RESPND-MI Study Team, New York 2. FXB Center for Health and Human Rights, Harvard University, Boston 3. Crystal La’Beija Organizing Fellowship, KBCAN, New York City 4. School of Public Health, City University of New York, New York City 5. Computational Health Informatics, Boston Children’s Hospital, Boston 6. Perelman School of Medicine, University of Pennsylvania, Philadelphia 7. The Fenway Institute, Boston 8. Harvard Medical School, Harvard University, Boston 9. School of Public Health, Boston University, Boston 10. Biology Department, New York University, New York City 11. Department of Social and Behavioral Sciences, Harvard University, Boston 12. School of Nursing, Rochester University, Rochester 13. School of Medicine, Stanford University, Stanford

#### Presenting Author
Keletso Makofane

### Background 
In response to the global MPOX outbreak of 2022, public health authorities focused place-based health interventions on commercial sex venues. To inform alternative strategies, we conducted an anonymous, community-led, online survey on other places where people meet for sex among queer and trans residents of New York City (NYC).

### Methods 
Participants were recruited through geo-targeted online ads from September to November 2022. We recorded census tract identifiers for participants’ homes and for venues they had sexual or prolonged physical contact in (SVs) during the preceding four weeks. For analysis, NYC census tracts were grouped into community districts (CDs). These range in population from approximately 50,000 to 200,000.

We calculated coverage – the proportion of the study sample that could potentially be reached through two strategies: In Strategy A, CDs were ranked by number of participants who live in them. In Strategy B, CDs were ranked by number of SVs. In both strategies, a limited number of top-ranked CDs were targeted. We present estimates with bootstrap confidence intervals.

### Results 
The survey was completed by 1494 participants (1226 cisgender men, 67 cisgender women, 39 transgender men, 29 transgender women, 106 non-binary persons). Nearly two thirds (66%) were gay identified, and 15%, bisexual. Overall, 39% of participants reported attending 768 venues (40% private residences; 11% sex parties or dark rooms, 35% dance parties, concerts, and sports games; 14% other).

To achieve 33% coverage, Strategy A would need to be implemented in 5 (95% CI: 4 – 5) CDs, and Strategy B in 3 (2 – 3). For 66% coverage, these figures would be 14 (12 – 14) and 11 (9 – 11), respectively.

### Conclusions 
Collecting spatial data on group sex is feasible. Through the use of these data, it is possible to devise venue-based intervention strategies that achieve high coverage while focusing on a limited number of CDs.