# Who we are {.unnumbered}

This website was developed by **Dr. Keletso Makofane**, who holds a PhD in social network epidemiology from Harvard University (2021), and a MPH in Biostatistics from Columbia University (2012), which he earned as a Fulbright scholar. Dr. Makofane is an **internationally recognized public health expert** in the global response to HIV. His focus is the **health and human rights of gay and bisexual men**. As a scholar, Dr. Makofane develops **cutting-edge methods in network epidemiology** for use in community settings.

The content was drafted in consultation and discussion with **Nicholas Diamond**, MPH; **Jennifer Barnes-Balenciaga**; **Elle Lett**, MA, MBiostat, PhD; **Ken Mayer**, MD; and **Nguyen Tran**, MPH, PhD. It is a culmination of discussions held by members of the **RESPND-MI Investigator Group** (see below) over two years with early inputs from the RESPND-MI Reference Group. The **RESPND-MI** **LGBTQ+ Community Forum** guided the preparation of the study and helped us to make crucial decisions about study design collectively.