### Link tracing


We designed a system for anonymously building a referral network

At the start of the survey, the participant is given an identifier image showing a unique combination of words and a QR code. They are prompted to save the image of their identifier card.

Near the end of the survey, the participant is prompted to share the survey with friends with a share button on screen. The share button opens the participant’s device’s native share menu and allows them to edit and share a pre-written invitation to the survey with a unique URL.

If a contact of the participant’s uses the url, an edge will be added between their node and the original participant’s node

Say an new participant takes the survey and shares it with somebody who has already taken the survey (an old participant)

The old participant would go to the url and be prompted to upload their identifier card or to enter the combination of words on the card in a text field. An edge would be added between the new and old participants’ nodes in the graph database