### Implementation

#### Rationale
Collecting spatial coordinates would increase the risk of accidentally identifying people by, for instance, capturing the exact coordinate of a college dormitory as a participant's residence, or capturing the exact coordinates of a federal government office as a venue for sexual contact in a group setting. In both these examples, it becomes easier to narrow down the identity of participants using the location and the particiapnts' characteristics as recorded in survey data.

#### Continuation
The front end of the MPX NYC Person-Place Network Mapper was developed as a single-page web application using the React/NextJS framework [@vercel2024] with visual design based on the MPX NYC style guide. The back end was a custom-built neo4j graph database [@neo4j2024]. Along with the Network Map question format, the instrument allows the use of standard survey question formats (multiple choice, single choice, text field etc.).

The MPC NYC Person-Place Network Mapper underwent two rounds of user testing. About 10 people participated each time, returning feedback via an informal feedback questionnaire and via email.


Data flow

-   Front end interface in Next.js hosted on Vercel

    -   takex a JSON file for the content of questions, text prompts

    -   parses URL for referrer identifier (if any), and survey language

    -   requests a public identifier from the API - the API returns a new public identifier. a unique combination of words.

    -   shows unique public identifier and a QR code of the public identifier to participant, prompting participant to save the image on their device

    -   for person-place network mapper data, front end queries a government database to transform spatial coordinates into census tract identifiers

    -   returns a JSON object using the API

-   API on XYZ

    -   receives request for an identifier

        -    generates a public identifier (described above) paired with a private identifier in the form of uid.

        -   Returns public identifer to front end

        -   Saves public identifer / private identifer pair in an identifier table in a secure database, separate from study data base

    -   receives study data from front end

        -   transforms public identifier to private identifers by querying the identifier table

        -   sends data to graph data base

    -   receives confirmation of link

        -   transforms public identifier to private identifers by querying the identifier table

        -   send data on the new edge to graph data base

-   graph data base

    -   hosted on a cloud server platform

    -   designed to represent survey data as one giant graph (see data graph)

    -   uses a query language that uses the structure of the graph to simplify complex queries

    -   use script or manual entry to declare node types, edge types, and node and edge attribute data
    
    
To ensure participant anonymity, the survey tool coarsens spatial data to the census tract level before sending them to the study database. Census tracts are non-overlapping spatial units that partition the United States into areas ranging from $2500$ to $8000$ in population size [@uscensus2022]. This is done through The Federal Communications Commission API [@fcc2022] which receives longitude-latitude coordinates from the survey instrument, and returns census block identifiers, which are transformed to census tract identifiers by truncating the last X digits. \[CITATION\] It is only after spatial data are transformed that they are transmitted to the study database (backend).

