

## Social and spatial analysis with causal interpretation (SSNAC) {.unnumbered}

The SSNAC framework is an approach to collecting, analyzing and interpreting data which explicitly accounts for causal relations among people, among places, and across people and places. It is applicable in two situations: when investigators want to describe patterns in how people interact with each other and/or with shared spaces; or when investigators are interested in understanding or intervening on the causal system formed by these components. 

For the descriptive interest, it is necessary to have data on individuals and spatial units they co-inhabit. For richer analyses, data on relationships among individuals and on relationships between spatial units could be incorporated. For the causal interest, it is necessary for investigators to additionally have a theory or set of theories about the causal process under investigation. At minimum, theory should clarify:

-   the meaning of nodes (which entities they represent)

-   the meaning of ties (how they relate entities)

-   an account of the causal processes that causally link nodes