


### The data are a network {.unnumbered}

The central data structure in a SSNAC is the data graph. @fig-ssnac depicts the final frame of @fig-context, showing households as nodes in a network, connecting neihgboring households with a network edge, and connecting individuals with the households they belong to. In a data graph, study data are stored as node or edge attributes. Person nodes might have attributes like age and race whereas place nodes could have attributes like density or surface area. An edge linking a person to a place might have an attribute conveying how the person relates to the place (e.g. home or work) and an edge linking a person to a person might have attributes related to the type of relationship (e.g. friend, sex partner), etc. 


```{r}
#| label: fig-ssnac
#| fig-cap: SSNAC data graph encoding people, places, and spatial and social connections
#| fig-width: 8

data_snac_example() |>
  plot_ssnac_example() |>
  style_ssnac_example() +
  theme_mpxnyc_blank(legend.position = "bottom") 


```


