


### New causal structures open new causal enquiries {.unnumbered}

The SSNAC framework opens up the potential to investigate causal queries that more closely resemble the program decisions that public health leaders have to make when faced with health challenges. The four standard SSNAC causal queries focus on node-level outcomes in the SNACC framework.

**Person-to-place intervention**: Evaluating the causal impact of a person-level intervention on place-level outcomes for some defined set of people and some defined set of places. e.g. What is the impact of vaccinating college-aged adults in New York City on mpox incidence in Washington Square (a favorite hangout spot for NYU students)?

**Person-to-person intervention**: Evaluating the impact of a person-level intervention on person-level outcomes for some defined sets of people. e.g. How does vaccinating all cisgender white men in New York City affect mpox incidence among Black and Latinx cisgender black men in New York City?

**Place-to-place intervention**: Evaluating the impact of a place-level intervention on place-level outcomes for some defined sets of places. e.g How does vaccinating Manhattan affect mpox incidence in Brooklyn?

**Place-to-person intervention**: Evaluating the impact of a place-level intervention on person-level outcomes for some defined set of people and some defined set of places. e.g. How does vaccinating Harlem affect mpox incidence among cisgender black men in New York City

In addition there is an endless potential for constructing causal queries that focus on characteristics that cannot be represented as node characteristics for any single node, but rather are characteristics that emerge as a result of the pattern of interactions among nodes. We investigate such a query in @sec-causal-interpretation.

