```{r}
targets::tar_source("../R_functions")
```


#### Observed data model

The homogeneity and independence assumptions allow us to re-write the structural equation model dropping the person subscript from the equations. Since the measures on each person are identically distributed, this model can be used three times to separately generate the measures for *Person 1*, *Person 2*, and *Person 3*. By contrast, the original model produced measures for all three people at one go.

@fig-independence-dag and @eq-independence-dag show the resulting non-parametric structural equation model for our data if we analyse it under classic causal inference. As a consequence of the assumptions stated above, we can represent the model using three equations rather than nine. We retain the person subscript on the random variables in @eq-independence-dag and we keep all nine nodes in the DAG on @fig-independence-dag. This is to remind us that, though our model is for one person, our purpose was always to infer something about the sample of three people.

{{< include ___figures/fig-independence-dag.qmd >}}
{{< include ___equations/eq-independence-dag.qmd >}}
