```{r  include=FALSE}
targets::tar_source("../R_functions")

```

# MPX NYC III: Web Dev {#sec-data}




::: {#leading}
In this appendix, we describe the process of designing and testing a novel survey questionnaire tool we call the MPX NYC person-place mapper. We show the questions participants were presented with in the survey.

:::

::: {#acknowledgements}
[Acknowledgements]{.underline}: The survey instrument was designed by Keletso Makofane and coded by Keletso Makofane (front end) and Imran Ansari (back end). Sudipta Saha found the web service that allowed us to safely collect spatial data. Seema Kara wrote the initial technical specifications for the instrument. neo4j granted a concessionary licence for the graph database system we used for the back end. Pedro Carneiro and Nguyen Tran led the development of survey questions. Cody Nolan and Anton Antón Castellanos Usigli conducted translation from English to Spanish. Robert Pitts helped to design questions on suspected mpox symptoms.

[Lead author]{.underline}: Keletso Makofane, MPH, PhD. [Editor]{.underline}: Nicholas Diamond, MPH. (Published: June 2025).
:::





```{r}
#| fig-width: 3
#| fig-height: 3
#| fig-align: center


plot_icon(icon_name = "taco", color = "light_purple", shape = 16, alpha = 0,  size = 100, image_size = 0.2)

```



{{< include C_2__person_place_network_mapper.qmd >}}



