---
bibliography: ../bibliography.bib
---

# Further projects {#sec-appendixfurtherprojects}

### Distributing the Map-Input question format {.unnumbered}

This project will use the custom designed measurement tool to create a more general one that can be used in a variety of settings.

### Packaging social spatial network analyses {.unnumbered}

Using the theory and measures developed in the above projects, this project will establish a collaboration to develop and maintain an R package for spatial network epidemiological analyses.

### Anticipating health disparities {.unnumbered}

Since different groups of people are unevenly distributed across neighborhoods in the city, conducting any intervention that prioritizes neighborhoods will likely lead to intervention outcomes that are differential across key demographic variables (race, age, gender, sexual orientation).

This project will evaluate health disparities generated in the course of conducting an intervention. It will design intervention approaches that minimize health disparities.

### Formalizing causality in spatial network interventions {.unnumbered}

Following Makofane PhD dissertation and auto-g-computation paper, we can define hypothetical interventions on nodes in counterfactual terms by: defining the intervention regime as the $n-$dimensional array indicating the treatment status of each individual; defining the counterfactual outcome as the n-dimensional array of outcome measurements taken on each node; using the MPX NYC participant network to define the pattern of causal interference between treatment units; and using the MPX NYC participant network to define a structure for network autocorrelation among outcome measures.

The goal of the project will be to articulate a framework for causal inference for the spatial social network setting:

1.  identify estimands for the spatial social network setting

2.  Identify intervention regimes

3.  Identify methods for estimating the causal effect of different strategies on different estimands.

### Assessing leaky interventions {.unnumbered}

While the main analysis of MPX NYC considers the impact of a 100% effective vaccine deployed so as to achieve 100% coverage in each community district that has been vaccinated.

Using simulation, this study will

1.  articulate a framework for considering interventions in an inter-connected city

<!-- -->

2.  examine the impact of the strategies tested in the main analysis when we relax the assumptions of 100% coverage and 100% efficacy.
