---
bibliography: "../const/bibliography.bib"
---

# From outbreak to epidemic

When we started, MPOX testing was not at all available. Our goal was to estimate the proportion of community members who experienced mpox-like symptoms. We also wanted to understand the structure of social and sexual networks that connect our community so that we could understand how to most effectively distribute MPOX vaccines. Within 5 months of conceiving the project, we had strated collecting data. We kept the survey open for about 1 month, obtaining about 1300 responses.The data have proven useful - we started sharing periodic analyses with the New York City Department of Health, guiding their outreach activities. Preliminary analyses were shared at the IAS international conference in Montreal, and have through several presentations and public discussions since then.As MPOX shifted from an outbreak to an epidemic, we took time to come up with the best way to make sense of these data and to convey them to different readers. This report is the result of that effort.We have prioritized the reproducibility of our study findings and our study design. Our hope is that alliances of LGBTQ activists and researchers will use these methods to answer the pressing questions of their contexts. The data and code we used to make this report are available here \[HYPERLINK TO GITHUB\]. We have written detailed appendices on the methods we devised to make sense of our data.As resources allow, we will publish the code for the custom-designed tool we developed to safely measure sensitive locations as well as explainer videos. Our goals is for the report to be accessible to most interested readers while maintain enough technical precision to allow others to understand, critique, and possibly replicate the study.The next section gives an overview of what scientists already know about the themes our research report touches on: the relationship between people’s social networks and their health, the infectious disease dynamics of a novel outbreak, the health of

```{r}

# Access custom defined functions
targets::tar_source("../R_functions")

```

## Rapid oubreak

Mpox cases in the United States (U.S.) were first detected in May 2022 and rapidly escalated, with over 10,000 cases reported by the end of July 2022 [@minhaj2022]. Initial clusters were associated with large gatherings involving sex and concentrated in white, cisgender, gay, bisexual, and other men who have sex with men, with limited data available for minoritized ethno-racial and transgender communities. Over time, new data indicated that Black, Latinx, and transgender communities were also disproportionately affected [@blackburn2022].

## Slow responses

Despite early warnings from activists about the lack of testing capacity in the U.S., responses from city, state, and federal governments were slow and inadequate [@krellenstein2023]. At the height of Pride month in June, only about 20 mpox tests were administered daily in New York City (NYC), in stark contrast to the 719 probable or confirmed mpox cases in NYC between May 19 to July 15, 2022 [@kyaw2022]. This was a critical period for scaling prevention efforts in vulnerable communities affected by mpox, yet structural divestments led to inadequate data collection; unpredictable vaccination access and vaccine shortages [@annagracelee]; and challenges in obtaining and providing treatment [@formonk2022].

## Weak systems

### Health communication

-   Limited
-   Ugly
-   Stigmatizing
-   Inaccessible

### Healthcare delivery

-   Informal networks // Variable care if you can afford
-   FQHC if you can't afford
-   

### Strategic information

-   Based on biased healthcare delivery data
-   Not fine-grained

## A living epidemic

### Burden

### Transmission dynamics

### The role of networks
