```{r include=FALSE}
targets::tar_source("../R_functions")
```

# *Outbreak to epidemic

When we started, MPOX testing was not at all available. Our goal was to estimate the proportion of community members who experienced mpox-like symptoms. We also wanted to understand the structure of social and sexual networks that connect our community so that we could understand how to most effectively distribute limited MPOX vaccine doses. 

## Rapid outbreak

Mpox cases in the United States (U.S.) were first detected in May 2022 and rapidly escalated. Initial clusters were associated with large gatherings involving sex and concentrated in white, cisgender, gay, bisexual, and other men who have sex with men, with limited data available for minoritized ethno-racial and transgender communities. Over time, new data indicated that Black, Latinx, and transgender communities were also disproportionately affected [@blackburn2022].

## Slow responses

Despite early warnings from activists about the lack of testing capacity in the U.S., responses from city, state, and federal governments were slow and inadequate [@krellenstein2023]. At the height of Pride month in June, only about 20 mpox tests were administered daily in New York City (NYC), in stark contrast to the 719 probable or confirmed mpox cases in NYC between May 19 to July 15, 2022 [@kyaw2022]. This was a critical period for scaling prevention efforts in vulnerable communities affected by mpox, yet structural divestments led to inadequate data collection; unpredictable vaccination access and vaccine shortages [@annagracelee]; and challenges in obtaining and providing treatment [@formonk2022]. Whereas the World Health Organization declared MPOX a \[EPIDEMIC OF INTERNATIONAL INTEREST\], it took New York State x months to declare a state of emergency and it took New York City x months to do the same. By the end of July 2022, there were over 10,000 cases of MPOX reported [@minhaj2022].

## Broken surveillance

Systems for understanding the scale and epidemic dynamics of an outbreak of a new infection like MPOX were fatally flawed. In particular, surveillance of MPOX was based on MPOX lab test data, which were unreliable because of likely selection bias. This is because at each state of the testing process, there were barriers to obtaining a test.

**To be tested for MPOX**:

it is required to have a pustule that can be swabbed.

-   some had internal lesions that could not be swabbed

You have to know what MPOX is

-   some did not recognize their lsesions as mpox

-   for some, the lesion resolves on its own

-   health communication was either vague of disgusting

You have to see a doctor.

-   under insurance / biased by social determinants

You have to convince the doctor to take your symptoms and account seriously.

-   homophobia - doctors does not examine anus

-   homophobia - doctor does not treat pain

-   ignorance - doctor last heard of mpox as a foreign disease, test not indicated

-   inconvenience - The doctor has to call the local department of health to ask to send a specimen to their lab.

The local department of health approves the test and doctor collects

-   There was limited testing capacity - they would run out of reagents.

-   local departments of health would throttle testing by making it difficult to order a test, or saying that a test is not indicated
