
# Our response

```{r}

# Access custom defined functions
targets::tar_source("../R_functions")

```

We organized the RESPND-MI study team into three working groups, inviting community members to join regardless of academic credentials: the administration group (fundraising and Institutional Review Board applications); the technical group (questionnaire and survey instrument development); and the external affairs group (public-facing marketing, communications, and partnerships). Community partners joined as co-investigators and participated in all collective decision-making.

## Administration 
 - First, developed a study protocol and obtained institutioal review board clearence. 
 - Fundraising 
 - Financial reporting
 - Financial transactions

## Technical

## External affairs

The external affairs group played a crucial role in ensuring that RESPND-MI benefited from the expertise of individuals and organizations working in queer and transgender health in NYC. The team regularly consulted with stakeholders, including activists, government officials, community-based organizations, clinicians, researchers, and other community partners through the RESPND-MI’s community forum.

### RESPND-MI Community Forum and Investigator team

Starting in May 2022, we prepared a study about sexual activity and mpox symptoms among those most vulnerable to mpox. To promote consultation and collective decision making for the study, we organised an online community forum (CF). In the first CF, attendees expressed the need for a space to continually coordinate response efforts across organisations, and to address gaps not immediately met by local and federal public health agencies

CFs thus became weekly calls where participants received epidemiologic updates, discussed problems, and provided input on study design and marketing decisions. From June to September 2022, over 80 activists, community leaders, public health professionals participated in CFs. We produced policy briefs, op-eds, and educational materials; and conducted media outreach. The RST website became a clearing house for community-generated resources, as well as community-generated information on vaccination, testing, and treatment services.

Educational materials and policy recommendations from the CF were adopted by city, state, and federal PHAs. Reporters cited the RST in over 90 press clips. Survey data were used to inform NYC vaccination outreach services. [@roth2023].

The Community Forum shaped study plans, including the recruitment campaign, the design of a novel spatial data collection tool, and the development of our study questionnaire. Sustained engagement led to several concrete improvements in research approach. For example, a criticism of the initial communication approach was that it centered cisgender men to the exclusion of transgender women and transgender men. This was consistent with most communication about the social epidemiology of MPOX at the time, and most scientific reporting.

But given that many public heatlh data systems use measures for gender that are unable to identify transgender individuals, limiting attention to cisgender men would have limited our ability to understand the true extent of the mpox outbreak. We assumed that transgender people and cisgender people are part of the same social and sexual networks which would likely be affected by mpox. We invited the participant who raised that criticism to join the study team. Over time, we attempted to continually improve gender related language and iconography in the project through discussion among investigators.
