
```{r}
targets::tar_source("R_functions")
```

### Example 1: Wealth, Dress, and Jobs {.unnumbered}

We are interested in settling an argument among friends about the relationship between dressing in formal wear and job opportunities. One friend thinks that dressing formally clearly brings more job opportunities; everyone she knows who dresses formally has many more opportunities than people who dress casually. The other friend thinks that what really brings job opportunities is currently having a job. In their reasoning, having a job causes people to dress formally and causes people to have job opportunities, but dressing formally does not in itself improve opportunities. We conduct a study to try investigate.

We recruit three people, Person 1, Person 2, and Person 3. Person 1 and Person 2 are married to each other. Person 1 and Person 3 are newly acquainted colleagues. Say Person 1 has job status $L_1$, Person 2 has job status $L_2$ and Person 3 has job status $L_3$. Each of these variables can only take on two values: "employed vs. unemployed". Similarly we define $A_i$ as Person $i$'s dress (formal vs. informal), and $Y_i$ as their job opportunities (high vs. low). The job status measurement ($L_i$) precedes dress ($A_i$) in time, and dress precedes job opportunities ($Y_i$).
