
```{r}
targets::tar_source("R_functions")
```

### Example 2: Marriage, Wealth, Dress, Jobs {.unnumbered}

We mentioned that in our study sample, Person 1 and Person 2 are married to each other, and Person 1 and Person 3 are new colleagues. In the causal system connecting their job status, dress and job opportunities, an argument could be made that Person 1's wealth affects Person 2's dress, since they pool their individually held wealth as a married couple. It could also be argued that Person 1's job status affects Person 2's job opportunities if having a job brings the married couple into contact with other couples who are connected to job markets. Finally, we could argue that Person 1's dress affects Person 2's job opportunities if some aspect of the reputation Person 2 enjoys among potential colleagues derives from Person 1's current job in that market. Symmetrically, Person 2's current job could also potentially affect Person 1 job opportunities.

But what about the relationship between Person 1 and Person 3? How does that shape the measurements of either person? We can imagine that the wealth and dress of a newly acquainted colleague would not affect the dress and job opportunities of her colleague. Whereas Person 1 and Person 2 are connected in @fig-homogenous-dag, Person 1 and Person 3 are not because their relationship is irrelevant to the causal system under investigation. Person 2 and Person 3 do not affect each other since they have no relationship at all.