
```{r}
targets::tar_source("R_functions")
```

### Assumptions

#### Independence assumptions

##### No spillover

Under the SSNAC framework, we make the assumption of no spillover - that contemporaneous measurements taken across observational units are independent of each other given all prior measures. The time-ordering of the measuremnts is given by the structural part of the causal DANG.


##### Network interference

We make the assumption that interference respects the mapping given by the relational part of a causal DANG. 

#### Homogeneity assumptions

##### Identical distribution

As in the case of classical causal inference, we assume that the structural equations that produce each observatoinal unit's measures are identical across observational units i.e. we assume:

```{=tex}
\begin{aligned}
f_A = f_{A_1} &= f_{A_2} = f_{A_3} \\
f_L = f_{L_1} &= f_{L_2} = f_{L_3} \\
f_Y = f_{Y_1} &= f_{Y_2} = f_{Y_3} \\

\end{aligned}
```
##### Homogenous interference

*Separability*

We assume that in each structural equation, each covariate contributes to the exposure mapping in two parts: i) the covariate level for the individual and ii) a covariate level of the ego-network of that individual.

Define $\mathscr{N_i}$ as the indices of all the nodes connected to node $i$. Then $\mathbf{L}_{\mathscr{N}_i}$ is the sub-vector of $\mathbf{L}$ containing the entries corresponding to the indices in $\mathscr{N}_i$. Similarly, we define $A_{\mathscr{N}_i}$ as the sub-vector of $A$ corresponding to the indices in $\mathscr{N}_i$.

Functions $g_{A_i}$, $g_{Y_i}$, and $h_{Y_i}$ are exposure mappings - functions that summarize covariate values for observational unit $i$t. They map vectors of any length to the real line. 

$$
g: \bigcup_{k = 0}^{\infty}{\mathbb{R}^k}  \rightarrow  \mathbb{R}
$$

$\mathbb{R}^0$ is defined as a set that has only one element - the empty vector ($\mathbb{R}^0 = \{[]\}$). This represents the situation where observational unit $i$ is not related to any other observational unit in the sample.  

$$
\begin{aligned}
L_1 &= f_{L_1}(U_{L_1}) \\
L_2 &= f_{L_2}(U_{L_2}) \\
L_3 &= f_{L_3}(U_{L_3} ) \\
A_1 &= f_{A_1}(U_{A_1}, L_1, g_{A_1}(\mathbf{L}_{\mathscr{N}_1})) \\
A_2 &= f_{A_2}(U_{A_2}, L_2, g_{A_2}(\mathbf{L}_{\mathscr{N}_2})) \\
A_3 &= f_{A_3}(U_{A_3}, L_3, g_{A_3}(\mathbf{L}_{\mathscr{N}_3})) \\
Y_1 &= f_{Y_1}(U_{Y_1}, L_1, A_1, g_{Y_1}(\mathbf{L}_{\mathscr{N}_1}), h_{Y_1}(\mathbf{A}_{\mathscr{N}_1})) \\
Y_2 &= f_{Y_2}(U_{Y_2}, L_2, A_2, g_{Y_2}(\mathbf{L}_{\mathscr{N}_2}), h_{Y_2}(\mathbf{A}_{\mathscr{N}_2})) \\
Y_3 &= f_{Y_3}(U_{Y_3}, L_3,A_3,  g_{Y_2}(\mathbf{L}_{\mathscr{N}_3}), h_{Y_2}(\mathbf{A}_{\mathscr{N}_3})) \\
\end{aligned}
$$

This simplifies the model, but still forces us to write the structural equations for each observation separately since each observation potentially has a set of unique exposure mappings.

*Equivalency*

We assume that exposure mappings $g_A$, $h_y$, and $g_Y$ are identical across individuals.

```{=tex}
\begin{aligned}
g_L = g_{L_1} &= g_{L_2} = g_{L_3} \\
h_A = h_{A_1} &= h_{A_2} = h_{A_3} \\
g_Y = g_{L_1} &= g_{L_2} = g_{L_3} \\
\end{aligned}
```
*Symmetry*

We also assume that the order of the entries does not matter in the the input for functions $g_A$, $g_Y$, and $h_Y$. i.e. the functions are invariant under any permutation of the entries in the input vector.

*Boundedness*

We assume that exposure mappings are bounded above.

$$
g_A, h_Y, g_Y < c \text{ for } c \in \mathbf{Z}
$$


*(time homogeneity)*

In applications with repeated measures, if the structure of the causal DANG allows, we can make the assumption that the structural equations are identical accross time. We apply this assumption in the example 3 below. 


