
```{r}
targets::tar_source("R_functions")
```

### Assumptions

#### Independence assumptions

##### No spillover

Under the SSNAC framework, we make the assumption of no spillover - that contemporaneous measurements on observational units of a given entity type are independent of each other given all prior measures. The time-ordering of the measurements is given by the structural part of the causal DANG.


##### Network interference

We make the assumption that interference respects the mapping given by the relational part of a causal DANG. 

#### Homogeneity assumptions

##### Identical distribution

We assume that the structural equations that produce each observational unit's measures are identical across observational units of the same entity type.

##### Homogenous interference

*Separability*

We assume that in each structural equation, each covariate contributes to the exposure mapping in two parts: i) the covariate level for the observational unit and ii) a summary of the covariate levels of members of the the ego-network of that unit given by exposure mappings.

*Equivalency*

We assume that exposure mappings are identical across observational units of each given entity type.

*Symmetry*

We also assume that the order of the entries does not matter in the the input for exposure mappings. i.e. the mappings are invariant under any permutation of the entries in the input vector.

*Boundedness*

We assume that exposure mappings are bounded above.


*Time homogeneity (optional)*

In applications with repeated measures, if the structure of the causal DANG allows, we can make the assumption that the structural equations are identical across time. We apply this assumption in Example 3 below. 


