
```{r}
targets::tar_source("R_functions")
```

### Example 3: Longitudinal Data-Driven Vaccination Campaign {.unnumbered}

You are a public health officer at the department of health in Nowhereville, and are planning to conduct and assess a three week flu vaccination campaign. None of the townspeople have been vaccinated against flu.

In the city of Nowhereville there is a population of 5 residents. The city is divided into three neighborhoods. Each resident has a primary home in one of the neighborhoods, but might visit other residents in another. Person 1 lives in Neighborhood A and visit Neighborhood B. Person 2 lives in Neighborhood B, but vists Neighborhoods A and B. Person 3 lives in Neighborhood C and visits Neighborhood B. Persons 5 and 6 live in Neighborhood C and they do not visit any other neighborhoods.

The city of Nowhereville has a very structured approach to vaccination campaigns. At the beginning of each week, each neighborhood gets a risk rating based on the prevalence of vaccination among its residents and visitors. Based on that rating, each neighborhood decides whether to conduct a local vaccination drive or not. Vaccination drives are done in the same way regardless of neighborhood - visitors and residents are offered immediate vaccination at a nearby mobile van through a pop-up message on the local dating app. Not everyone will receive the messages because some will not open the app during the period of the campaign. Those who do will have the choice of getting vaccinated or not. Each person can only get vaccinated once. 
