# Data {#sec-data}

```{r  include=FALSE}
targets::tar_source("../R_functions")
```


## MPX NYC Person–Place Network Mapper

Data were collected using the [MPX NYC Person–Place Network Mapper](https://survey-instrument.vercel.app){target="blank}, a web survey tool designed to elicit sensitive spatial and social data under conditions of anonymity. The Mapper displayed an interactive city map where participants identified key places—such as homes, parties, or social venues—by tapping on the map (see @fig-map-input). Each tap generated a marker and a short sequence of questions about that location.

To preserve confidentiality, the tool automatically transformed geographic coordinates into U.S. Census Tract identifiers before transmission. These tracts, which partition the United States into units of roughly 2,500 – 8,000 residents, ensured that no identifying spatial data entered the study database. The resulting dataset represents a **bipartite person–place graph**, where people and places are nodes and their reported connections (residence, social contact, or sexual contact) form edges. This graph structure defines the analytic foundation for SSNAC, supporting causal reasoning under network interference.

{{< include fig-map-input.qmd >}}




## Marketing and communication

To support recruitment, we developed a bilingual, community-centered communication campaign in collaboration with a marketing agency. The campaign was guided by the RESPND-MI LGBTQ+ Community Forum, which emphasized visual language rooted in queer and trans culture—emojis with sexual connotations, humor, and peer-to-peer tone.

{{< include fig-options.qmd >}}

Paid and donated advertising was distributed through Grindr, Twitter (X), Instagram, and outdoor digital billboards across New York City. The campaign’s creative concepts (see @fig-options) combined scientific credibility with cultural familiarity, fostering trust and broad participation while maintaining visual distinctiveness in a crowded media environment.

## Study implementation

### Inclusion Criteria {.unnumbered}

Eligible participants were: - At least 18 years old,\
- Living in or recently present in New York City, and\
- Identifying as transgender, gay, bisexual, queer, or as men who have sex with men.

Eligibility required informed consent before participation. Individuals younger than 18 or who declined consent were excluded.

### Translation {.unnumbered}

All study materials were professionally translated from English to Spanish and reviewed by six bilingual professionals in health-related fields whose first language is Spanish. This ensured linguistic accuracy and cultural appropriateness across recruitment, consent, and survey materials.

### Consent and Ethical Approval {.unnumbered}

Participants provided informed consent electronically before beginning the survey. The study protocol—including recruitment materials, web application, and data-collection procedures—was reviewed and approved by the *Harvard T.H. Chan School of Public Health Institutional Review Board* (IRB22-0761).



## References

U.S. Census Bureau. 2022. “Census Tracts.” https://www2.census.gov/geo/pdfs/education/CensusTracts.pdf.

{{< include fig-plot-icon-2.qmd >}}

