

```{r}



plot_radar_graphic_single <- function(data, variable_name = "age", stratum_input = "Black\nCisgender\nMen", 
    list_labels) 
{
    variable_levels <- names(list_labels[[variable_name]][["levels"]])
    variable_labels <- list_labels[[variable_name]][["levels"]]
    stratum_levels <- names(list_labels[["stratum"]][["levels"]])
    stratum_labels <- list_labels[["stratum"]][["levels"]]
    data %>% dplyr::filter(variable == variable_name, stratum == 
        stratum_input) %>% dplyr::mutate(variable = as.character(variable), 
        stratum = as.character(stratum), level = as.character(level)) %>% 
        dplyr::mutate(level = factor(level, variable_levels, 
            variable_labels), stratum = factor(stratum, stratum_levels, 
            stratum_labels)) %>% ggplot2::ggplot() + ggplot2::geom_bar(aes(x = level, 
        fill = level, y = proportion), width = 1, stat = "identity") + 
        ggplot2::coord_polar() + ggplot2::theme_void() + ggplot2::theme(legend.position = "none", 
        panel.grid.major.x = ggplot2::element_line(size = 0.1)) + 
        ggplot2::scale_fill_manual(values = c(mpxnyc_colors$dark_blue, 
            mpxnyc_colors$dark_pink, mpxnyc_colors$dark_purple, 
            mpxnyc_colors$light_blue, mpxnyc_colors$light_pink, 
            mpxnyc_colors$light_purple)) + ggplot2::scale_x_discrete(drop = FALSE) + 
        ggplot2::ylim(-0.5, 1)
}


plot_radar_title_single <- function (title, showdot = FALSE) 
{
    result <- ggplot2::ggplot()
    if (showdot) {
        result <- result + ggplot2::geom_point(ggplot2::aes(x = 0, 
            y = 0), size = 30, color = "#f7fbff")
    }
    result <- result + 
                ggplot2::geom_text(aes(x = 0, y = 0, label = title), size = 3.5) + 
                ggplot2::theme_void() + 
                ggplot2::theme(plot.title = ggplot2::element_text(vjust = -0.5, hjust = 0.5))
    result
}


plot_radar_legend_single <- function (data, variable_name, list_labels) 
{
    variable_levels <- names(list_labels[[variable_name]][["levels"]])
    variable_labels <- list_labels[[variable_name]][["levels"]]
    
    data %>% 
      dplyr::filter(variable == variable_name) %>% 
      dplyr::mutate(count = 0.2) %>% 
      dplyr::mutate(level = as.character(level)) %>% 
      dplyr::mutate(level = factor(level, variable_levels, variable_labels)) %>% 
      ggplot2::ggplot() + 
        ggplot2::geom_bar(ggplot2::aes(x = level, y = count, fill = level), width = 1, stat = "identity", alpha = 0.2) + 
        ggplot2::coord_polar(clip = "off") + 
      ggplot2::theme_void() + 
      ggplot2::theme(
        axis.text.x = element_text(size = 8, angle = 30),
        plot.margin = margin(0,0,0,0, "mm")
      ) +
      ggplot2::theme(
        legend.position = "none", 
        panel.grid.major.x = ggplot2::element_line(size = 0.1)
        ) + 
        ggplot2::scale_fill_manual(values = c(
                                              dark_blue, 
                                              dark_pink, 
                                              dark_purple, 
                                              light_blue, 
                                              light_pink, 
                                              light_purple
                                              )) + 
      ggplot2::scale_x_discrete(drop = FALSE) + 
      ggplot2::ylim(-0.5, 1)
}




list_labels_descriptives_by_demogroup <- targets::tar_read(initial_settings)$labels_list[c( "monkeypoxVaccine", "hivPrep", "sexOrientation")]

list_labels_descriptives_by_demogroup[["stratum"]] <- list()
list_labels_descriptives_by_demogroup[["stratum"]][["levels"]] <- list()

list_labels_descriptives_by_demogroup[["stratum"]][["levels"]][["white-cisgender-man"]]  <- "White\nCisgender\nMan"
list_labels_descriptives_by_demogroup[["stratum"]][["levels"]][["latinx-cisgender-man"]] <- "Latinx\nCisgender\nMan"
list_labels_descriptives_by_demogroup[["stratum"]][["levels"]][["black-cisgender-man"]]  <- "Black\nCisgender\nMan"
list_labels_descriptives_by_demogroup[["stratum"]][["levels"]][["other-cisgender-man"]]  <- "Other\nCisgender\nMan"
#list_labels_descriptives_by_demogroup[["stratum"]][["levels"]][["non-binary"]]           <- "Non-Binary\nPerson"
#list_labels_descriptives_by_demogroup[["stratum"]][["levels"]][["transgender-man"]]      <- "Transgender\nMan"
#list_labels_descriptives_by_demogroup[["stratum"]][["levels"]][["transgender-woman"]]    <- "Transgender\nWoman"
#list_labels_descriptives_by_demogroup[["stratum"]][["levels"]][["cisgender-woman"]]      <- "Cisgender\nWoman"
#list_labels_descriptives_by_demogroup[["stratum"]][["levels"]][["other"]]                <- "Another\nDemographic"






data            <- targets::tar_read(data_radar_graphic_demo_group_raw) %>% 
                            dplyr::mutate(stratum = stratum_demo_group) 

list_labels     <- list_labels_descriptives_by_demogroup
  
main_plots_list <- list_labels %>% 
                        names() %>% 
                        setdiff(c("stratum")) %>% 
                        purrr::map(function(variable_name) {
                          list_labels$stratum$levels %>% 
                            names() %>% 
                            purrr::map(
                                function(stratum_input) {
                                  plot_radar_graphic_single(
                                                              data, 
                                                              variable_name = variable_name, 
                                                              stratum_input = stratum_input, 
                                                              list_labels   = list_labels
                                                              )
                                  }
                                ) %>% 
                            setNames(list_labels$stratum$levels) %>%
                            cowplot::plot_grid(
                                                plot_radar_title_single(list_labels[[variable_name]][["label"]]), 
                                                plot_radar_legend_single(data, variable_name, list_labels), 
                                                plotlist = ., 
                                                ncol = 1, 
                                                rel_heights = c(0.5, 1, rep(1, length(.))))
                          })


    labels_length <- data %>% 
                        dplyr::pull(stratum) %>% 
                        levels() %>% 
                        length()
    
    labels <- data %>% 
              dplyr::mutate(stratum = factor(
                                              stratum, 
                                              names(list_labels[["stratum"]][["levels"]]),
                                              list_labels[["stratum"]][["levels"]])
                            ) %>% 
              dplyr::pull(stratum) %>% 
              levels() %>% 
              purrr::map(
                function(level) {
                                  plot_radar_title_single(level)
                  }
                ) %>% 
      cowplot::plot_grid(
                          plot_radar_title_single(""), 
                          plot_radar_title_single(""), 
                          plotlist = ., 
                          ncol = 1, 
                          rel_heights = c(0.5, 1, rep(1, length(.)))
                          )
    
    
        
    main_body <- cowplot::plot_grid(labels, plotlist = main_plots_list, nrow = 1) 
    
    
    
plot_a <- ggplot() +
      labs(
        title = captions_and_titles("demogroup")$title,
        subtitle = captions_and_titles("demogroup")$subtitle,
        caption = captions_and_titles("demogroup")$caption
      ) +
      theme_void() +
      theme(
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5)
      ) +
      cowplot::draw_plot(cowplot::ggdraw(main_body), 0, 0, 1, 1)



```




```{r}





plot_radar_graphic_single <- function(data, variable_name = "age", stratum_input = "Black\nCisgender\nMen", 
    list_labels) 
{
    variable_levels <- names(list_labels[[variable_name]][["levels"]])
    variable_labels <- list_labels[[variable_name]][["levels"]]
    stratum_levels <- names(list_labels[["stratum"]][["levels"]])
    stratum_labels <- list_labels[["stratum"]][["levels"]]
    data %>% dplyr::filter(variable == variable_name, stratum == 
        stratum_input) %>% dplyr::mutate(variable = as.character(variable), 
        stratum = as.character(stratum), level = as.character(level)) %>% 
        dplyr::mutate(level = factor(level, variable_levels, 
            variable_labels), stratum = factor(stratum, stratum_levels, 
            stratum_labels)) %>% ggplot2::ggplot() + ggplot2::geom_bar(aes(x = level, 
        fill = level, y = proportion), width = 1, stat = "identity") + 
        ggplot2::coord_polar() + ggplot2::theme_void() + ggplot2::theme(legend.position = "none", 
        panel.grid.major.x = ggplot2::element_line(size = 0.1)) + 
        ggplot2::scale_fill_manual(values = c(mpxnyc_colors$dark_blue, 
            mpxnyc_colors$dark_pink, mpxnyc_colors$dark_purple, 
            mpxnyc_colors$light_blue, mpxnyc_colors$light_pink, 
            mpxnyc_colors$light_purple)) + ggplot2::scale_x_discrete(drop = FALSE) + 
        ggplot2::ylim(-0.5, 1)
}


plot_radar_title_single <- function (title, showdot = FALSE) 
{
    result <- ggplot2::ggplot()
    if (showdot) {
        result <- result + ggplot2::geom_point(ggplot2::aes(x = 0, 
            y = 0), size = 30, color = "#f7fbff")
    }
    result <- result + 
                ggplot2::geom_text(aes(x = 0, y = 0, label = title), size = 3.5) + 
                ggplot2::theme_void() + 
                ggplot2::theme(plot.title = ggplot2::element_text(vjust = -0.5, hjust = 0.5))
    result
}


plot_radar_legend_single <- function (data, variable_name, list_labels) 
{
    variable_levels <- names(list_labels[[variable_name]][["levels"]])
    variable_labels <- list_labels[[variable_name]][["levels"]]
    
    data %>% 
      dplyr::filter(variable == variable_name) %>% 
      dplyr::mutate(count = 0.2) %>% 
      dplyr::mutate(level = as.character(level)) %>% 
      dplyr::mutate(level = factor(level, variable_levels, variable_labels)) %>% 
      ggplot2::ggplot() + 
        ggplot2::geom_bar(ggplot2::aes(x = level, y = count, fill = level), width = 1, stat = "identity", alpha = 0.2) + 
        ggplot2::coord_polar(clip = "off") + 
      ggplot2::theme_void() + 
      ggplot2::theme(
        axis.text.x = element_text(size = 8, angle = 30),
        plot.margin = margin(0,0,0,0, "mm")
      ) +
      ggplot2::theme(
        legend.position = "none", 
        panel.grid.major.x = ggplot2::element_line(size = 0.1)
        ) + 
        ggplot2::scale_fill_manual(values = c(
                                              dark_blue, 
                                              dark_pink, 
                                              dark_purple, 
                                              light_blue, 
                                              light_pink, 
                                              light_purple
                                              )) + 
      ggplot2::scale_x_discrete(drop = FALSE) + 
      ggplot2::ylim(-0.5, 1)
}




list_labels_descriptives_by_demogroup <- targets::tar_read(initial_settings)$labels_list[c( "monkeypoxVaccine", "hivPrep", "sexOrientation")]

list_labels_descriptives_by_demogroup[["stratum"]] <- list()
list_labels_descriptives_by_demogroup[["stratum"]][["levels"]] <- list()

#list_labels_descriptives_by_demogroup[["stratum"]][["levels"]][["white-cisgender-man"]]  <- "White\nCisgender\nMan"
#list_labels_descriptives_by_demogroup[["stratum"]][["levels"]][["latinx-cisgender-man"]] <- "Latinx\nCisgender\nMan"
#list_labels_descriptives_by_demogroup[["stratum"]][["levels"]][["black-cisgender-man"]]  <- "Black\nCisgender\nMan"
#list_labels_descriptives_by_demogroup[["stratum"]][["levels"]][["other-cisgender-man"]]  <- "Other\nCisgender\nMan"
list_labels_descriptives_by_demogroup[["stratum"]][["levels"]][["non-binary"]]           <- "Non-Binary\nPerson"
list_labels_descriptives_by_demogroup[["stratum"]][["levels"]][["transgender-man"]]      <- "Transgender\nMan"
list_labels_descriptives_by_demogroup[["stratum"]][["levels"]][["transgender-woman"]]    <- "Transgender\nWoman"
list_labels_descriptives_by_demogroup[["stratum"]][["levels"]][["cisgender-woman"]]      <- "Cisgender\nWoman"
#list_labels_descriptives_by_demogroup[["stratum"]][["levels"]][["other"]]                <- "Another\nDemographic"






data            <- targets::tar_read(data_radar_graphic_demo_group_raw) %>% 
                            dplyr::mutate(stratum = stratum_demo_group) 

list_labels     <- list_labels_descriptives_by_demogroup
  
main_plots_list <- list_labels %>% 
                        names() %>% 
                        setdiff(c("stratum")) %>% 
                        purrr::map(function(variable_name) {
                          list_labels$stratum$levels %>% 
                            names() %>% 
                            purrr::map(
                                function(stratum_input) {
                                  plot_radar_graphic_single(
                                                              data, 
                                                              variable_name = variable_name, 
                                                              stratum_input = stratum_input, 
                                                              list_labels   = list_labels
                                                              )
                                  }
                                ) %>% 
                            setNames(list_labels$stratum$levels) %>%
                            cowplot::plot_grid(
                                                plot_radar_title_single(list_labels[[variable_name]][["label"]]), 
                                                plot_radar_legend_single(data, variable_name, list_labels), 
                                                plotlist = ., 
                                                ncol = 1, 
                                                rel_heights = c(0.5, 1, rep(1, length(.))))
                          })


    labels_length <- data %>% 
                        dplyr::pull(stratum) %>% 
                        levels() %>% 
                        length()
    
    labels <- data %>% 
              dplyr::mutate(stratum = factor(
                                              stratum, 
                                              names(list_labels[["stratum"]][["levels"]]),
                                              list_labels[["stratum"]][["levels"]])
                            ) %>% 
              dplyr::pull(stratum) %>% 
              levels() %>% 
              purrr::map(
                function(level) {
                                  plot_radar_title_single(level)
                  }
                ) %>% 
      cowplot::plot_grid(
                          plot_radar_title_single(""), 
                          plot_radar_title_single(""), 
                          plotlist = ., 
                          ncol = 1, 
                          rel_heights = c(0.5, 1, rep(1, length(.)))
                          )
    
    
        
    main_body <- cowplot::plot_grid(labels, plotlist = main_plots_list, nrow = 1) 
    
    
    
plot_b <- ggplot() +
      labs(
        title = captions_and_titles("demogroup")$title,
        subtitle = captions_and_titles("demogroup")$subtitle,
        caption = captions_and_titles("demogroup")$caption
      ) +
      theme_void() +
      theme(
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5)
      ) +
      cowplot::draw_plot(cowplot::ggdraw(main_body), 0, 0, 1, 1)



```


:::: {.columns}

::: {.column width="50%"}
```{r}
#| fig-width: 7
#| fig-height: 9

plot_a
```
:::

::: {.column width="50%"}
```{r}
#| fig-width: 7
#| fig-height: 9

plot_b
```
:::

::::