```{r include=FALSE}
targets::tar_source("../R_functions")
```


# SSNAC I: Context {#sec-appendix-social-spatial}

::: {#acknowledgements}
[Acknowledgements]{.underline}: The name and main ideas of SSNAC were sketched out in a symposium titled "BEYOND disparities: Broadening Epidemiologic methods of 'who, what, where, when, and whY'' to further consider 'hOw'' we research has the potential to move health equity in New Directions" organized by Nedghie Adrien (Harvard University) and Julie M. Petersen (University of Nebraska) at the Society for Epidemiologic Research mid-year meeting (virtual, January 2025). Leading up to that presentation, the ideas developed in conversation with Eric Tchetgen Tchetgen (University of Pennsylvania) and colleagues at University of Pennsylvania Center for Causal Inference. 

[Lead author]{.underline}: Keletso Makofane, MPH, PhD. [Editor]{.underline}: Nicholas Diamond, MPH. (Published: June 2025).
:::


```{r}
#| fig-width: 2
#| fig-height: 2
#| fig-align: center


plot_icon(icon_name = "eggplant", color = "dark_purple", shape = 0)

```







{{< include A_0__preface.qmd >}} 
{{< include A_1__ssnac_components.qmd >}} 
{{< include A_2__data_are_network.qmd >}} 
{{< include A_3__network_is_causal.qmd >}} 
{{< include A_4__new_structures_new_questions.qmd >}}



