---
title: "MPX NYC"
subtitle: "Key findings and recommendations"
author: "Keletso Makofane"
date: 23 May 2024

crossref: 
  thm-prefix: Box
  thm-title: Box
  tbl-prefix: Table
  tbl-title: Table
  fig-prefix: ""
  fig-title: ""
editor: visual
always_allow_html: true
prefer-html: true
fig-cap-location: top 
execute:
  echo: false
  warning: false
  message: false
format:
  revealjs:
    incremental: true
    scrollable: true
    fig-align: center
    align: center
    smaller: true
---

```{r update_mpxnyc_package, include = FALSE, messages=FALSE, warning = FALSE}
#remotes::install_github("KeletsoMakofane/mpxnyc", auth_token = "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")
```

```{r load_libraries, include = FALSE, messages=FALSE, warning = FALSE}
library(tidyverse)
library(ggplot2)
library(mpxnyc)
library(sf)
library(tidygraph)
library(ggraph)
library(igraph)



mpxnyc_colors <- mpxnyc::mpxnyc_colors
attach(mpxnyc_colors)

```

```{r scripts}

targets::tar_source(files = "/Users/keletso/Documents/_gitrepos/mpxnyc_data_analysis/R_functions")
targets::tar_source(files = "/Users/keletso/Documents/_gitrepos/mpxnyc_data_analysis/R_functions/1_data_processing")
targets::tar_source(files = "/Users/keletso/Documents/_gitrepos/mpxnyc_data_analysis/R_functions/2_data_summary")
targets::tar_source(files = "/Users/keletso/Documents/_gitrepos/mpxnyc_data_analysis/R_functions/3_data_extract")
targets::tar_source(files = "/Users/keletso/Documents/_gitrepos/mpxnyc_data_analysis/R_functions/4_plot")
targets::tar_source(files = "/Users/keletso/Documents/_gitrepos/mpxnyc_data_analysis/R_functions/5_tables")

```

```{r update_data_pipeline, include=FALSE, messages=FALSE, warning = FALSE}


targets::tar_make() # Runs the data pipeline shown in _targets.R


```

```{r captions_and_titles}


captions_and_titles <- function(figure_name){
  
   
  
    list_captions_and_titles <- list()
    list_captions_and_titles[["common_caption"]] <- "Data source: MPX NYC Survey (restricted to 1,304 residents of New York City). www.mpxresponse.org"
    
    list_captions_and_titles[["bar_group_sex"]]                          <- list()
    list_captions_and_titles[["bar_group_sex"]][["title"]]               <- "Figure 1. Social or sexual contact in group setting over prior four weeks"
    list_captions_and_titles[["bar_group_sex"]][["subtitle"]]            <- "New York, United States, Aug. - Nov. 2022"
    list_captions_and_titles[["bar_group_sex"]][["caption"]]             <- "Participants were asked whether they 'had sex with two or more people at the same time or had close, physical contact with multiple people at the same time (e.g. at a party, sport game, concert, show)' over the prior four weeks. About two fifths responded yes."
    
    list_captions_and_titles[["radar_placetype_placesex"]]                       <- list()
    list_captions_and_titles[["radar_placetype_placesex"]][["title"]]            <- "Figure 2. Type of venue for contact vs. type of contact"
    list_captions_and_titles[["radar_placetype_placesex"]][["subtitle"]]         <- "New York, United States, Aug. - Nov. 2022"
    list_captions_and_titles[["radar_placetype_placesex"]][["caption"]]          <- "We asked participants to show the location of their home and the locations of places where they had close, physical contact in a group setting. For each place, they indicated what kind of venue it was and whether they had sexual contact there. Among places where participants did not have sex, most were public settings. By contrast, the majority of places for sexual contact were private residences."
    
    
    list_captions_and_titles[["radar_placetype_distance"]]                         <- list()
    list_captions_and_titles[["radar_placetype_distance"]][["title"]]              <- "Figure 3. Type of venue for contact vs. distance from home"
    list_captions_and_titles[["radar_placetype_distance"]][["subtitle"]]           <- "New York, United States, Aug. - Nov 2022"
    list_captions_and_titles[["radar_placetype_distance"]][["caption"]]            <- "We asked participants to show the location of their home and the locations of places where they had close, physical contact in a group setting. For each place, they indicated what kind of venue it was and whether they had sexual contact there. The further away from home a place was, the less likely it was to be a private residence and the more likely it was to be a dance party."
    
    list_captions_and_titles[["radar_placetype_sex_distance"]]                <- list()
    list_captions_and_titles[["radar_placetype_sex_distance"]][["title"]]     <- "Figure 4. Type of venue for contact vs. type of contact and distance from home"
    list_captions_and_titles[["radar_placetype_sex_distance"]][["subtitle"]]  <- "New York, United States, Aug. - Nov. 2022"
    list_captions_and_titles[["radar_placetype_sex_distance"]][["caption"]]   <- "We asked participants to show the location of their home and the locations of places where they had close, physical contact in a group setting. For each place, they indicated what kind of venue it was and whether they had sexual contact there. Among places for sexual contact, the further away from home a place was, the less likely it was to be a private residence. At each distance, however, private residencs were the predominant venue for sexual contact."
    
    list_captions_and_titles[["map_coverage"]]                          <- list()
    list_captions_and_titles[["map_coverage"]][["title"]]               <- "Figure 5. Large number of individuals reachable in limited geographic area"
    list_captions_and_titles[["map_coverage"]][["subtitle"]]            <- "New York, United States, Aug. - Nov. 2022"
    list_captions_and_titles[["map_coverage"]][["caption"]]             <- "It may be possible to mount geographically targeted interventions that have impact across New York City. We ranked community districts in terms of the number of participants who reside or reported close, physical contact in them. The top five community districts (which comprise Group A) together account for about one third of participants. The next eight community districts (Group B) account for another third of participants."
    
    list_captions_and_titles[["matrix_places"]]                      <- list()
    list_captions_and_titles[["matrix_places"]][["title"]]           <- "Figure 6. Movement between community districts in New York City"
    list_captions_and_titles[["matrix_places"]][["subtitle"]]        <- "New York, United States, Aug. - Nov. 2022"
    list_captions_and_titles[["matrix_places"]][["caption"]]         <- "We asked participants to show the location of their home and the locations of places where they had close, physical contact in a group setting. The axis on the left shows the home community district of each participant, and the top axis shows the destination community. The size of each circle is proportional to the number of respondents with a home in the community on the left who had contact in a community showed at the top."
    
    list_captions_and_titles[["networkcoverage"]]                         <- list()
    list_captions_and_titles[["networkcoverage"]][["title"]]              <- "Figure 7. Community districts densely connected"
    list_captions_and_titles[["networkcoverage"]][["subtitle"]]           <- "New York, United States, Aug. - Nov. 2022"
    list_captions_and_titles[["networkcoverage"]][["caption"]]            <- "We asked participants to show the location of their home and the locations of places where they had close, physical contact in a group setting. We constructed a network where nodes are community districts. A tie between a given pair of nodes indicates that at least one study participant was present in both community districts. The thickness of the tie is proportional to the number of study participants who have been present in both community districts."
    
    list_captions_and_titles[["bar_demo_group"]]                 <- list()
    list_captions_and_titles[["bar_demo_group"]][["title"]]      <- "Figure 8. Race and gender of participants"
    list_captions_and_titles[["bar_demo_group"]][["subtitle"]]   <- "New York, United States, Aug. - Nov. 2022"
    list_captions_and_titles[["bar_demo_group"]][["caption"]]    <- ""
    
    list_captions_and_titles[["bar_age"]]                 <- list()
    list_captions_and_titles[["bar_age"]][["title"]]      <- "Figure 9. Age of participants"
    list_captions_and_titles[["bar_age"]][["subtitle"]]   <- "New York, United States, Aug. - Nov. 2022"
    list_captions_and_titles[["bar_age"]][["caption"]]    <- ""
    
    list_captions_and_titles[["bar_channel"]]                 <- list()
    list_captions_and_titles[["bar_channel"]][["title"]]      <- "Figure 10. Study recruitment channel"
    list_captions_and_titles[["bar_channel"]][["subtitle"]]   <- "New York, United States, Aug. - Nov. 2022"
    list_captions_and_titles[["bar_channel"]][["caption"]]    <- ""
    
    list_captions_and_titles[["bar_gender"]]                 <- list()
    list_captions_and_titles[["bar_gender"]][["title"]]      <- "Figure 11. Gender identity of participants"
    list_captions_and_titles[["bar_gender"]][["subtitle"]]   <- "New York, United States, Aug. - Nov. 2022"
    list_captions_and_titles[["bar_gender"]][["caption"]]    <- ""
    
    list_captions_and_titles[["bar_race"]]                 <- list()
    list_captions_and_titles[["bar_race"]][["title"]]      <- "Figure 12. Race of participants"
    list_captions_and_titles[["bar_race"]][["subtitle"]]   <- "New York, United States, Aug. - Nov. 2022"
    list_captions_and_titles[["bar_race"]][["caption"]]    <- ""
    
    list_captions_and_titles[["bar_sex_orientation"]]                 <- list()
    list_captions_and_titles[["bar_sex_orientation"]][["title"]]      <- "Figure 13. Sexual orientation of participants"
    list_captions_and_titles[["bar_sex_orientation"]][["subtitle"]]   <- "New York, United States, Aug. - Nov. 2022"
    list_captions_and_titles[["bar_sex_orientation"]][["caption"]]    <- ""
    
    list_captions_and_titles[["demogroupa"]]                 <- list()
    list_captions_and_titles[["demogroupa"]][["title"]]      <- "Figure 14a. Demographic characteristics of participants"
    list_captions_and_titles[["demogroupa"]][["subtitle"]]   <- "New York, United States, Aug. - Nov. 2022"
    list_captions_and_titles[["demogroupa"]][["caption"]]    <- ""
    
    list_captions_and_titles[["demogroupb"]]                 <- list()
    list_captions_and_titles[["demogroupb"]][["title"]]      <- "Figure 14b. Demographic characteristics of participants"
    list_captions_and_titles[["demogroupb"]][["subtitle"]]   <- "New York, United States, Aug. - Nov. 2022"
    list_captions_and_titles[["demogroupb"]][["caption"]]    <- ""
    
    list_captions_and_titles[["radar_sexOrientation_demo_group"]]                         <- list()
    list_captions_and_titles[["radar_sexOrientation_demo_group"]][["title"]]              <- "Sexual Orientation by Race-Gender"
    list_captions_and_titles[["radar_sexOrientation_demo_group"]][["subtitle"]]           <- "New York, United States, Aug. - Nov 2022"
    list_captions_and_titles[["radar_sexOrientation_demo_group"]][["caption"]]            <- ""
    
    list_captions_and_titles[["radar_hivPrep_demo_group"]]                         <- list()
    list_captions_and_titles[["radar_hivPrep_demo_group"]][["title"]]              <- "HIV/PreP Status by Race-Gender"
    list_captions_and_titles[["radar_hivPrep_demo_group"]][["subtitle"]]           <- "New York, United States, Aug. - Nov 2022"
    list_captions_and_titles[["radar_hivPrep_demo_group"]][["caption"]]            <- ""
    
    list_captions_and_titles[["radar_monkeypoxVaccine_demo_group"]]                         <- list()
    list_captions_and_titles[["radar_monkeypoxVaccine_demo_group"]][["title"]]              <- "MPOX Vaccination Status by Race-Gender"
    list_captions_and_titles[["radar_monkeypoxVaccine_demo_group"]][["subtitle"]]           <- "New York, United States, Aug. - Nov 2022"
    list_captions_and_titles[["radar_monkeypoxVaccine_demo_group"]][["caption"]]            <- ""
    
    
    
    list_captions_and_titles[[figure_name]]
}



```

# People

## 

```{r plot_bar_demogroup}
#| fig-width: 11
#| fig-height: 7

make_table_freq1(demo_group) %>%    
  filter(!is.na(level)) %>%
  plot_bar() %>%
  add_caption() %>%
  add_title("Race and gender of MPX NYC participants") %>%
  apply_style_bar_plot()

```

## 

```{r plot_bar_age}
#| fig-width: 7
#| fig-height: 7


make_table_freq1(age) %>%
  plot_bar() %>%
  add_caption() %>%
  add_title("Age of MPX NYC participants") %>%
  apply_style_bar_plot()

```

## 

```{r plot_bar_channel}
#| fig-width: 7
#| fig-height: 7

#| 


make_table_freq1(channel) %>%
  plot_bar() %>%
  add_caption() %>%
  add_title("Recruitment Channel of MPX NYC participants") %>%
  apply_style_bar_plot()


```

## 

```{r plot_bar_gender}
#| fig-width: 9
#| fig-height: 7

#| 




make_table_freq1(genderId) %>%  
  plot_bar() %>%
  add_caption() %>%
  add_title("Gender identity of MPX NYC participants") %>%
  apply_style_bar_plot()
 
```

## 

```{r plot_bar_race}
#| fig-width: 7
#| fig-height: 7
#| 

make_table_freq1(race) %>%
  plot_bar() %>%
  add_caption() %>%
  add_title("Race of MPX NYC participants") %>%
  apply_style_bar_plot()
  
```

## 

```{r plot_bar_sexorientation}
#| fig-width: 7
#| fig-height: 7


make_table_freq1(sexOrientation) %>%    
  plot_bar() %>%
  add_caption() %>%
  add_title("Sexual orientation of MPX NYC participants") %>%
  apply_style_bar_plot()


```

## 

```{r plot_radar_grid_sexOrientation_demo_group}
#| fig-width: 7
#| fig-height: 10

make_table_freq2(sexOrientation, demo_group) %>%
  plot_radar_grid() %>%
  add_caption() %>%
  add_title("Sexual orientation of MPX NYC participants by race and gender") %>%
  apply_style_radar_grid_plot()

```

## 

```{r plot_radar_grid_monkeypoxVaccine_demo_group}
#| fig-width: 7
#| fig-height: 10

make_table_freq2(monkeypoxVaccine, demo_group) %>%
  plot_radar_grid() %>%
  add_caption() %>%
  add_title("MPOX vaccination status of MPX NYC participants by race and gender") %>%
  apply_style_radar_grid_plot()

```

## 

```{r plot_radar_grid_hivPrep_demo_group}
#| fig-width: 10
#| fig-height: 10

make_table_freq2(hivPrep, demo_group) %>%
  plot_radar_grid() %>%
  add_caption() %>%
  add_title("HIV and PrEP status of MPX NYC participants by race and gender") %>%
  apply_style_radar_grid_plot()

```

## 

```{r plot_bar_groupsex}
#| fig-width: 7
#| fig-height: 7
#| 

make_table_freq1(groupSex) %>%  
  plot_bar() %>%
  add_caption() %>%
  add_title("Sexual or physical contact with more than two other people at the same time") %>%
  apply_style_bar_plot()

```

# Places

## 

```{r plot_radar_facet_placetype_placesex}
#| fig-width: 9
#| fig-height: 8
#| 

make_table_freq2(placeType, placeSex, person_analysis = FALSE) %>%
  filter(!is.na(level)) %>%
  plot_radar_stratified() %>%
  add_caption() %>%
  add_title("Type of venue for contact vs. type of contact") %>%
  apply_style_radar_facet_plot()

```

## 

```{r plot_radar_facet_placetype_distancefromhome}
#| fig-width: 9
#| fig-height: 8
#| 





make_table_freq2(placeType, distanceFromHome, person_analysis = FALSE) %>%
  plot_radar_stratified() %>%
  add_caption() %>%
  add_title("Type of venue for contact vs. distance from home") %>%
  apply_style_radar_facet_plot()



```

## 

```{r plot_radar_facet_placetype_placesex_distancefromhome}
#| fig-width: 11
#| fig-height: 10
#| 


  make_table_freq3(placeType, placeSex, distanceFromHome, person_analysis = FALSE) %>%
    filter(!is.na(level)) %>%
  plot_radar_stratified2() %>%
  add_caption("Data source: MPX NYC Survey (restricted to 1,304 residents of New York City). www.mpxresponse.org") %>%
  add_title("Race-Gender of MPX NYC Participants") %>%
  apply_style_radar_facet_plot()

```

# People Mixing through Places

## 

```{r plot_matrix_mixing_age}
#| fig-width: 10
#| fig-height: 10


make_table_mixing(age) %>%
  plot_matrix_mixing() %>%
  add_caption("Data source: MPX NYC Survey (restricted to 1,304 residents of New York City). www.mpxresponse.org") %>%
  add_title("Race-Gender of MPX NYC Participants") %>%
  apply_style_matrix_mixing_plot()



```

## 

```{r plot_matrix_mixing_demo_group}
#| fig-width: 10
#| fig-height: 10


make_table_mixing(demo_group) %>%
  plot_matrix_mixing() %>%
  add_caption("Data source: MPX NYC Survey (restricted to 1,304 residents of New York City). www.mpxresponse.org") %>%
  add_title("Race-Gender of MPX NYC Participants") %>%
  apply_style_matrix_mixing_plot()



```

## 

```{r plot_matrix_mixing_sexorientation}
#| fig-width: 10
#| fig-height: 10


make_table_mixing(sexOrientation) %>%
  plot_matrix_mixing() %>%
  add_caption("Data source: MPX NYC Survey (restricted to 1,304 residents of New York City). www.mpxresponse.org") %>%
  add_title("Race-Gender of MPX NYC Participants") %>%
  apply_style_matrix_mixing_plot()



```

# Places connecting through People

## 

```{r plot_netviz_places}
#| fig-width: 9
#| fig-height: 9


make_coverage_table(intervention_priority = "contact", intervention_stratification = "overall") %>%
  plot_network_viz() %>%
  add_caption("Data source: MPX NYC Survey (restricted to 1,304 residents of New York City). www.mpxresponse.org") %>%
  add_title("Race-Gender of MPX NYC Participants") %>%
  apply_style_network_viz()
  
```

## 

```{r plot_matrix_movement_travel}
#| fig-width: 9
#| fig-height: 11

# 
# groupColors <- c("MN" = dark_blue, "BK" = dark_purple, "QN" = dark_pink, "SI" = dark_orange, "BX" = light_purple)
# 
#   data <- make_table_movement_travel() %>%
#     ungroup() %>%
#     rename(from = to, to = from) %>%
#     tbl_graph(edges = .) %>%
#     mutate(deg = igraph::degree(.)) %>%
#     mutate(borough = str_sub(name, 1, 2)) %>%
#     filter(deg > 10) %>%
#     arrange(borough, -deg) %>%
#     get.adjacency(attr = "weight") %>%
#     as.matrix()
#   
# data2 <- data.frame(name = attr(data, "dimnames")[[1]]) %>%
#               mutate(borough = str_sub(name, 1, 2)) %>%
#               mutate( col = groupColors[borough])
#               
# col = pull(data2, col)
# names(col) <- NULL
#   
#   data %>%
#     chorddiag::chorddiag( groupColors = col, groupThickness = 0.2, chordedgeColor = NULL, fadeLevel = 0.05, type = "bipartite")
#   
#   
#   
#   san_data <-  make_table_movement_travel() %>%
#     ungroup() %>%
#     rename(from = to, to = from) %>%
#     mutate(from = paste(from, "f"), to = paste(to, "t")) %>%
#     tbl_graph(edges = .) %>%
#     mutate(group = str_sub(name, 1, 2))
#   
#   
#   nodes <- san_data %>% activate(nodes) %>% data.frame()
#     edges <- san_data %>% activate(edges) %>% data.frame() %>%
#       mutate(from = from -1, to = to -1)
#   
#   
# networkD3::sankeyNetwork(Links = edges, Nodes = nodes, Source = "from",
#               Target = "to", Value = "weight", NodeID = "name",
#               units = "TWh", fontSize = 12, nodeWidth = 30, NodeGroup = "group")
# 
#   
  make_table_movement_travel() %>%
    plot_matrix_movement() %>%
  add_caption("Data source: MPX NYC Survey (restricted to 1,304 residents of New York City). www.mpxresponse.org") %>%
  add_title("Race-Gender of MPX NYC Participants") %>%
    apply_style_matrix_movement()
  
  

```

## 

```{r plot_matrix_movement_coattendance}
#| fig-width: 9
#| fig-height: 11


  make_table_movement_coattendance() %>%
    plot_matrix_movement() %>%
  add_caption("Data source: MPX NYC Survey (restricted to 1,304 residents of New York City). www.mpxresponse.org") %>%
  add_title("Race-Gender of MPX NYC Participants") %>%
    apply_style_matrix_movement()
  
  

```

# Interventions

## 

```{r plot_map_coverage}
#| fig-width: 7
#| fig-height: 10

make_coverage_table(intervention_priority = "contact", intervention_stratification = "overall") %>%
  plot_coverage_map() %>%
  add_caption("Data source: MPX NYC Survey (restricted to 1,304 residents of New York City). www.mpxresponse.org") %>%
  add_title("Race-Gender of MPX NYC Participants") %>%
  apply_style_coverage_map(caption_hjust = 0)


```

## 

```{r plot_bar_coverage}
#| fig-width: 14
#| fig-height: 7


make_coverage_table(intervention_priority = "contact", intervention_stratification = "overall") %>%
    plot_coverage_bar() %>%
  add_caption("Data source: MPX NYC Survey (restricted to 1,304 residents of New York City). www.mpxresponse.org") %>%
  add_title("Race-Gender of MPX NYC Participants") %>%
    apply_style_coverage_bar()

```

## 

```{r plot_net_impact}
#| fig-width: 7
#| fig-height: 7


make_table_centrality() %>%
  filter(intervention_ranking < 41) %>%
    plot_netimpact_bar() %>%
  add_caption("Data source: MPX NYC Survey (restricted to 1,304 residents of New York City). www.mpxresponse.org") %>%
  add_title("Race-Gender of MPX NYC Participants") %>%
    apply_style_bar_netimpact()


```
