# \*Responding to an oubreak

Draft Project Proposal:

An Operational Guidance for Community-Led Emergency Response to Health Emergencies


Keletso Makofane

RESPND-MI Study Group


## Outline of Operational Guidance

\

The main content of the document will be divided into four chapters, which each discuss one of four core functions of the plan: Coordination, Surveillance, Health Communications, and Resourcing. These will be bookended by a background chapter and a chapter outlining an operational structure for organizing the work outlined in the core chapters. 

\

Below is an outline of each chapter: 

\

Background

-   Motivation for creating the document

-   Process of creating the document

-   Principles that guided creation of process

-   Brief history of health emergency response in NYC

-   Outline of guidance

\

Core Function 1 – Coordination 

-   Responsibilities under this function:

    -   To collect and disseminate information about the health emergency among stakeholders

    -   To collect and disseminate information about the experiences of community-based organizations and NYC government agencies responding to the health emergency

    -   To coordinate programmatic activities by NYC agencies and civil society organizations

    -   To coordinate political action by civil society organizations 

-   Current Situation:

    -   Current NYC mechanisms for coordinating action in emergencies as well as an assessment of their strengths and weaknesses

    -   Current civil society mechanisms for coordinating action in emergencies as well as an assessment of their strengths and weaknesses

-   Recommendations:

    -   Recommendations for coordinating action across NYC and civil society going forward

\

Core Function 2 – Surveillance 

-   Responsibilities under this function:

    -   Assess data needs, data availability, and data gaps

    -   Design and conduct data collection activities to address gaps

    -   Synthesize and summarize relevant existing data and share in digestible format

    -   Disseminate data among stakeholders 

    -   Release data to press

-   Current Situation:

    -   Current data sources to guide City programs in emergencies as well as an assessment of their strengths and weaknesses

    -   Current data sources to guide civil society programs in emergencies as well as an assessment of their strengths and weaknesses

-   Recommendations:

    -   Recommendations for effectively summarizing or generating, and using data to guide action in emergencies 

\

Core Function 3 – Health Communication

-   Responsibilities under this function:

    -   Assess health communications needs

    -   Create communications materials in consultation with communities

    -   Collect and disseminate community-made health communications materials

-   Current Situation

    -   Current City practices for creating health communications materials in an emergency situation as well as an assessment of their strengths and weaknesses

    -   Current civil society practices for creating health communications materials in an emergency situation as well as an assessment of their strengths and weaknesses

-   Recommendations:

    -   Recommendations for effectively creating and disseminating effective and culturally competent health communications materials in emergencies

\

Core Function 4 – Resourcing:

-   Responsibilities under this function:

    -   Assess resource needs for CF1, CF2, CF3

    -   Mobilize resources for CF1, CF2, CF3 from:

        -   Companies that serve queer and trans people (e.g. Grindr)

        -   Individual donors

        -   Private foundations

        -   City, state, federal government

-   Current Situation

    -   Current City practices for mobilizing and deploying resources in an emergency response as well as an assessment of their strengths and weaknesses

    -   Civil society practices for mobilizing and deploying resources in an emergency response as well as an assessment of their strengths and weaknesses

-   Recommendations

    -   Recommendations for effectively mobilizing and deploying resources in an emergency situation.

\

Operational Structure

\

This chapter will lay out a “peace-time” structure that monitors for health emergencies and keeps stakeholders in the emergency response connected, as well as a structure that can be rapidly built in order to undertake the core functions outlined above. It will also include sample budgets for different functions, and sample Terms of Reference documents for the different roles outlined in the structure. 

\

For example, we could have something like:

\

And then provide TORs for each of the committees, as well as sample budgets for coordination, surveillance, communications, and resourcing activities.

# Project Plan

\

This section outlines the different groups that will participate in the process of developing the operational guidance, and shows key milestones for the project.

\

Steering Committee

To create legitimacy for the project among civil society members and city officials, it should be led by a steering committee consisting of civil society members who have convening power in their different communities (e.g. House Ball mothers, NGO directors, Party Promoters, etc.), and city officials with institutional power. Civil society members should receive honoraria. City members should be recognized by the city for their contributions.

\

Working Groups and Reviewers

The steering committee will then pull members of different communities into working groups that will each work on one pillar of the operational plan and invite colleagues to review the document once a draft is ready. Civil society members should receive honoraria. City members should be recognized by the city for their contributions.

\

Observers

To cultivate an audience for the operational guidance, and to initiate a national conversation about city-level emergency response, the steering committee will invite peers (both City officials, and civil society members) from other major U.S. cities. Observers will be invited to steering committee and working group meetings and will be invited to review the document. 

\

Consultants

The project will be supported by consultants whose responsibilities will include:

1.  Conducting consultations, including working group meetings, steering committee meetings, and document reviews to write the “Responsibilities under this function”, and “Recommendations” sections. 

2.  Interviewing key leaders and conducting document review to write “Current Situation” sections.

3.  Creating video/audio of interviews and consultations for internal and external use.

4.  Drafting the operational guidance.

5.  Creating a website to host the operational guidance and related media.

\
\
\

Key Milestones

\

|                                                                     |              |
|--------------------------------------------------------|----------------|
| **Milestone**                                                       | **Timeline** |
| Draft project proposal reviewed                                     |              |
| Steering Committee formed                                           |              |
| Steering Committee finalizes Project plan                           |              |
| Steering Committee creates working groups                           |              |
| Steering Committee invites reviewers                                |              |
| Consultants engaged                                                 |              |
| Consultant conducts interviews, focus groups, and writes up results |              |
| Release first draft for comment                                     |              |
| Consultation meeting/call on first draft                            |              |
| Finalize document                                                   |              |
| Steering committee reviews document                                 |              |
| Finalize and release document                                       |              |
| Have a launch event for document + website                          |              |

\
\

Goals:

-   joy, not stress

-   low stakes failure

-   redundancy

-   democracy

Approach:

-   Elaborate well-structured task list by team

-   Assign tasks to indiviuals

-   Empower individuals to mark tasks as done or pending

-   Empower individuals to re-assign tasks

-   Devolve responsibilities, setting clear expectatios

Roles:

-   Principal investigator

    -   Partnerships

    -   Fundraising

    -   Drafting study protocol

    -   Ethical review of protocol

    -   Quality check

-   Research coordinator

    -   Schedule group meetings

    -   Draft technical documents

    -   Research

    -   Bookkeeping

-   Communications lead

    -   Newsletter

    -   Website

    -   Attencance lists

    -   Press

-   Questionnaire lead

    -   coordinate development of questionnaire

    -   integrate feedback from stakeholders

    -   Seek guidance from technical expertw

    -   Work with translation lead

-   Web development lead

    -   develop technical specs for web tool

    -   Oversee contract with external web developer

-   Translation lead

    -   oversee contracts with professional translators

    -   quality check translation

    -   liase between translator and investigator team

## Contracts and fundraising

Asked for low medium high packaged

Asked for low package to include only intellecgtual work, for medium to include production, and for high to include advertising spend.

Sequenced fundraising to meet the timing goals.
