
```{r}
targets::tar_source("R_functions")
```

## The network is a causal structure

The Person-place graph is a starting point for constructing a causal model, but it is not sufficient. Depending on the causal question, some edges in this graph are relevant and some are not. For example, if we were interested in a rumor network, we might decide to depict only people and not places in the causal graph. We might also choose to ignore the neighbor edges and focus only on the friend and employee ones, if it is the case that rumours are transmitted within households and across friendships but not to neighbors. 

If we were interested in an infectious disease, and in the study setting, there is a stay-at-home order so that friends do not meet, but neighbors possibly meet, then we might keep the neighbor ties and drop the friend and employee ties.  In either case, it is necessary to make changes to the Person-place network through network operations like ignoring or adding ties, or even grouping nodes to form a different graph altogether. 

We explore this in the Analysis appendix.