# Acknowledgements

::: {#aboutus}
RESPND-MI is a collective of activists and researchers which formed to respond to the 2022 outbreak of MPOX among sexual and gender minority individuals in New York City.

The investigator team consisted of X cisgender black gay men, two black transgender women, 1 asian cisgender gay man, one latinx cisgender gay man, X white cisgender gay men. Among them, X hold PhDs in epidemiology and related fields, X had experience working in an LGBT health services organization, X had experience in grassroots organizing, 1 had experience developing global health program guidance for LGBT people. It grew of the life of the project since anybody who did study-related work, or contributed to discussions about study design was invited to be a RESPND-MI investigator.

:::



::: {#acknowledgements}
**Principal investigator**: Keletso Makofane, MPH, PhD; **Co-investigators**: Jennifer Barnes-Balenciaga, Nicholas Diamond, MPH, Elle Lett, PhD, MA, MBiostat, Cody Nolan, MD, Martez Smith, LMSW, PhD, Nguyen Tran, MPH, PhD; **Former investigators**: Pedro Botti Careneiro, MPH, PhD, Seema Kara, MPH, James Krellenstein, Ken Nadolski, MPH, Robert Pitts, MD, Grant Roth, MPH, Sudipta Saha, MS, Christian Urrutia, Chris Wyman; **Translators**: Antón Castellanos Usigli, MPH, PhD; **Reference group**: Judith D. Auerbach, PhD (*University of California, San Francisco*), Lisa Berkman, PhD (*Harvard University*), Forrest W. Crawford, PhD (*Yale University*), William C. Goedel, PhD (*Brown University*), Gregg Gonsalves, PhD (*Yale University*), Ian W. Holloway, PhD, LCSW, MPH (*University of California, Los Angeles*), Louise Ivers, MB, BCh, MD, MPH, DTMH (*Massachusetts General Hospital)*, Lawrence C. Long, MCom, PhD (*Boston University)*, Kenneth Mayer, MD (*The Fenway Institute*), Gregorio Millett, MPH (*amfAR*), Eric J. Tchetgen Tchetgen, PhD (*University of Pennsylvania*); **Research sponsors and funders**: amfAR, National Institutes of Health, neo4j; **Marketing sponsors and funders**: Grindr, Hub for Health Intervention, UCLA Luskin School of Public Affairs; **Administration**: Christian Urrutia (prep4all), James Krellenstein (prep4all). **Report reviewers**: ...
:::
