```{r}

# Access custom defined functions
targets::tar_source("../R_functions")

```

In this appendix we contextualize the main analysis in the MPX NYC project in a framework we name Social and Spatial Network Analysis with Causal interpretation, or SNACC. This framework allows for the analysis and causal interpretation of network data. It offers guidance on concpetualizing and organizing spatial and social data as network data, as well as describing that data using statistics.

The goals of this appendix are to motivate the usefulness of the SSNAC framework by describing the dominant system for investigating causality in the field of epidemiology, which we will call "classic causal inference". We extend this system to situations where data are characterized by interdependancy rather than independence of observational units. First we accommodate social network data, naming this system "network causal inference", and finally we accommodate social and spatial data simultaneously in a framework we named SSNAC. In each case, we describe the assumptions and implications of each system, illustrating with worked examples.   

Classic causal inference, as articulated by ([@robins1986; @hernán2018]) and others helps us to sharpen epidemiologic reasoning by providing a template for conducting thought experiments about population health. Typically in these experiments, one considers what the effect of a hypothetical intervention would be on some outcome measured in a hypothetical population. The system allows the researcher to map this hypothetical experiment to data collected from (typically) people through explicit assumptions. Crucially, it allows the researcher to quantify the impact of the intervention on the outcome. 

For instance, consider a hyothetical intervention where every person in the United States receives free, unlimited access to healthcare. Under classic causal inference, we can ask whether the prevalence of diabetes would change if we implemented the intervention. More specifically, we can ask about the extent of change and estimate it using data that have already been observed. The frameowrk allows this firstly by making causal assumptions about the relationship between healthcare and diabetes prevalence and secondly by stating the hypothetical quantities that are generated in the hypothetical experiment as a function of observed and measured quantities where possible. It allows us to estimate quantities that would arise under different conditions of the thought experiments.

A crucial assumption made almost universally by practitoiners of classic causal inference is that of independence between observational units or groups of observational units. In our opening example, this assumptoin would imply that one person's access to healthcare does not affect any other person's diabetes risk. To be pointed, tt would imply that the diabetes risk for a married man who does not know how to cook would not be affected by improvements in health literacy experienced by his wife who does. The assumption of independence runs counter to our intuitions about social life. Humans are networked creatures - our lives are defined by our relationships with others. 

But the choice of adopting the independence assumption or not has more profound implications. In the frequentist tradition of statistics, the engine of uncertainty is repetition. We imagine that an experiment could be repeated over and over again and we summarize its behavior accross those repetitions. We do not often consider what exactly we mean by experiment and by repetition, though we make this distinction each time we decide how to analyse repeated measures data. 

An example clarifies. Consider a situation with two people, Tumi and Thabo, who each toss the same coin once at time 1 and again at time 2. There are several ways of parsing this situation into "experiment" and "repetition". We could say that: 
- we are conducting one experiment called "coin toss" and repeating it four times
- we are conducting two experiments called "Thabo tosses a coin" and "Tumi tosses a coin" and are repeating each twice
- we are conducting four experiments called "Thabo tosses a coin at time 1", "Thabo tosses a coin at time 2", "Tumi tosses a coin at time 1", and "Tumi tosses a coin at time 2, and got to observe each of these once. 

The choice between these interpretations turns on the experimenters prior beliefs about coin tossing: Does the likelihood of a head or tail change over time? Does it change based on the person? And does the result of one person's coin toss affect the result of another? This kind of decision-making is at the core statistical modelling. Yet, in practice, the modelling decision to categorize people as independent of each other is so well-entrenched that it is often represented as a minimum condition of doing any valid causal quantitative research. Our goal in this appendix and project is to offer alternative ideas and tools for causal inference that allow us to learn form interdependence rather than fear it. 

In crude terms, our approach involves moving from a framework where we consider the coin toss example one experiment, rather than break it up into two or four. We represent the whole experiement, therfore, as a vector of length 4 that comes from some joint distribution. But why would a researcher want to do that when asymptotic theory requires us to have as many samples as possible? How can we conduct valid statistical inference and measure uncertainty when we always have a sample size of 1? 

Briefly, we do that because a model which considers the coin toss example to be only one experiment is correct even if it turns out that the four coin tosses are independent of each other. We make the assumption of no-spillover between observations, which is that one person's outcome can not direcetly affect another person's outcome. This assumption is weaker than the independence assumption. We further assume that the causal relatiohships between and within individuals are homogenous in some ways, allowing our estimates to benefit from larger sample sizes. As it will turn out, under certain homogeneity assumptions, asymptotic theory can be used to improve estimates in a growing vector of inter-related observations, whereas it is usally applied to a growing collection of vectors of equal length

In the sections that follow, we describe classic causal inference, network causal infernce, and the SSNAC framework, each time discussing the assumptions, observed and counterfactual data, causal estimands, add identification and estimation. Finally, we describe the MPX NYC outbreak response analysis using the SSNAC framework and end with a brief summary of the appendix. 