## Causal modelling

### Classic causal inference

To investigate causal estimands, we have to know the possible interventions of interest. We are setting $\textbf{A}=\textbf{a}$.

```{r}
#| fig-height: 8
#| fig-width: 7
#| 
make_swig("independence")      |> 
  plot_swig(node_radius = 0.2) + 
  scale_fill_mpxnyc(option = "light")

```

```{=tex}
\begin{aligned}
L_i &= f_{L}(     &&      && U_{L}  &&                        ) \\
Y_i(a) &= f_{Y}(L_i, && a_i, && U_{Y} && ) \\
\end{aligned}
```


### Network causal inference

We write the counterfactual model

```{r}
#| fig-height: 8
#| fig-width: 7
make_swig("network_interference")      |> 
  plot_swig(node_radius = 0.2) + 
  scale_fill_mpxnyc(option = "light")

```

```{=tex}
\begin{aligned}
L_i &= f_{L}(     &&      && U_{L}  &&                         &&                         && ) \\
Y_i(a_i,\textbf{a}_{N_i} ) &= f_{Y}(L_i, && a_i, && U_{Y}, && g_{Y}(\textbf{L}_{N_i}),     && h_{Y}(\textbf{a}_{N_i})       &&  ) \\
\end{aligned} 
```


### SSNAC



#### Place to person intervention

```{r}
#| fig-height: 7
#| fig-width: 10

list_nodes <- list()
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "V0", label = r"($V_{0}$)"      , x = 1 , y = 8 , node_type = "Individual", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "R1", label = r"($R_{1}$)"      , x = 2 , y = 2 , node_type = "Community", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "T1", label = r"($T_{1}$)"      , x = 3 , y = 4 , node_type = "Community", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "M1", label = r"($M_{1}$)"      , x = 4 , y = 6 , node_type = "Individual", node_shape = "preintervention")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "m1", label = r"($m_{1}$)"      , x = 4 , y = 6 , node_type = "intervention", node_shape = "intervention")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "V1", label = r"($V_{1}(m_1)$)"      , x = 5 , y = 8 , node_type = "Individual", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "R2", label = r"($R_{2}(m_1)$)" , x = 6 , y = 2 , node_type = "Community", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "T2", label = r"($T_{2}(m_1)$)"      , x = 7 , y = 4 , node_type = "Community", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "M2", label = r"($M_{2}$)"      , x = 8 , y = 6 , node_type = "Individual", node_shape = "preintervention")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "m2", label = r"($m_{2}$)"      , x = 8 , y = 6 , node_type = "intervention", node_shape = "intervention")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "V2", label = r"($V_{2}(m_1, m_2)$)"      , x = 9 , y = 8 , node_type = "Individual", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "R3", label = r"($R_{3}(m_1, m_2)$)" , x = 10 , y = 2, node_type = "Community", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "T3", label = r"($T_{3}(m_1, m_2)$)"      , x = 11 , y = 4, node_type = "Community", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "M3", label = r"($M_{3}$)"      , x = 12 , y = 6, node_type = "Individual", node_shape = "preintervention")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "m3", label = r"($m_{3}$)"      , x = 12 , y = 6, node_type = "intervention", node_shape = "intervention")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "V3", label = r"($V_{3}(m_1, m_2, m_3)$)"      , x = 13 , y = 8, node_type = "Individual", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "R4", label = r"($R_{4}(m_1, m_2, m_3)$)" , x = 14 , y = 2, node_type = "Community", node_shape = "covariate")

list_edges <- list()
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V0", to = "R1")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "R1", to = "T1")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "T1", to = "M1")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "m1", to = "V1")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "R2", to = "T2")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "T2", to = "M2")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "m2", to = "V2")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "R3", to = "T3")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "T3", to = "M3")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "M3", to = "V3")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V1", to = "R2")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V2", to = "R3")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "m1", to = "M2")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "m2", to = "M3")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V1", to = "M2")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V2", to = "M3")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V3", to = "R4")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V0", to = "V1")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V1", to = "V2")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V2", to = "V3")


structural_nodes <- list_nodes |> dplyr::bind_rows() |> dplyr::mutate(label = latex2exp::TeX(label, output = "character", bold = TRUE))
structural_edges <- list_edges |> dplyr::bind_rows()


tidygraph::tbl_graph(nodes = structural_nodes, edges = structural_edges) |>
  plot_swig(node_radius = 0.5, nudge_intervention_labels = 0.3) +
  ggplot2::theme(
    plot.margin = ggplot2::margin(10, 10, 10, 10),
    legend.position = "none"
  ) +
  scale_fill_mpxnyc(option = "light")



```

#### Place to place intervention

```{r}
#| fig-height: 7
#| fig-width: 10

list_nodes <- list()
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "V0", label = r"($V_{0}$)"      , x = 1 , y = 8 , node_type = "Individual", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "R1", label = r"($R_{1}$)"      , x = 2 , y = 2 , node_type = "Community", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "T1", label = r"($T_{1}$)"      , x = 3 , y = 4 , node_type = "Community", node_shape = "preintervention")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "t1", label = r"($t_{1}$)"      , x = 3 , y = 4 , node_type = "intervention", node_shape = "intervention")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "M1", label = r"($M_{1}(t_1)$)"      , x = 4 , y = 6 , node_type = "Individual", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "V1", label = r"($V_{1}(t_1)$)"      , x = 5 , y = 8 , node_type = "Individual", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "R2", label = r"($R_{2}(t_1)$)" , x = 6 , y = 2 , node_type = "Community", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "T2", label = r"($T_{2}$)"      , x = 7 , y = 4 , node_type = "Community", node_shape = "preintervention")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "t2", label = r"($t_{2}$)"      , x = 7 , y = 4 , node_type = "intervention", node_shape = "intervention")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "M2", label = r"($M_{2}(t_1, t_2)$)"      , x = 8 , y = 6 , node_type = "Individual", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "V2", label = r"($V_{2}(t_1, t_2)$)"      , x = 9 , y = 8 , node_type = "Individual", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "R3", label = r"($R_{3}(t_1, t_2)$)" , x = 10 , y = 2, node_type = "Community", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "T3", label = r"($T_{3}$)"      , x = 11 , y = 4, node_type = "Community", node_shape = "preintervention")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "t3", label = r"($t_{3}$)"      , x = 11 , y = 4, node_type = "intervention", node_shape = "intervention")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "M3", label = r"($M_{3}(t_1, t_2, t_3)$)"      , x = 12 , y = 6, node_type = "Individual", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "V3", label = r"($V_{3}(t_1, t_2, t_3)$)"      , x = 13 , y = 8, node_type = "Individual", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "R4", label = r"($R_{4}(t_1, t_2, t_3)$)" , x = 14 , y = 2, node_type = "Community", node_shape = "covariate")

list_edges <- list()
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V0", to = "R1")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "R1", to = "T1")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "t1", to = "M1")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "M1", to = "V1")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "R2", to = "T2")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "t2", to = "M2")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "M2", to = "V2")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "R3", to = "T3")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "t3", to = "M3")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "M3", to = "V3")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V1", to = "R2")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V2", to = "R3")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "M1", to = "M2")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "M2", to = "M3")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V1", to = "M2")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V2", to = "M3")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V3", to = "R4")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V0", to = "V1")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V1", to = "V2")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V2", to = "V3")


structural_nodes <- list_nodes |> dplyr::bind_rows() |> dplyr::mutate(label = latex2exp::TeX(label, output = "character", bold = TRUE))
structural_edges <- list_edges |> dplyr::bind_rows()


tidygraph::tbl_graph(nodes = structural_nodes, edges = structural_edges) |>
  plot_swig(node_radius = 0.5, nudge_intervention_labels = 0.2) +
  ggplot2::theme(
    plot.margin = ggplot2::margin(10, 10, 10, 10),
    legend.position = "none"
  ) +
  scale_fill_mpxnyc(option = "light")



```

#### Edge interventions


```{r}
#| fig-height: 7
#| fig-width: 10

list_nodes <- list()
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "V0", label = r"($V_{0}$)"      , x = 1 , y = 8 , node_type = "Individual", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "R1", label = r"($R_{1}(g)$)"      , x = 2 , y = 2 , node_type = "Community", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "T1", label = r"($T_{1}(g)$)"      , x = 3 , y = 4 , node_type = "Community", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "M1", label = r"($M_{1}(g)$)"      , x = 4 , y = 6 , node_type = "Individual", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "V1", label = r"($V_{1}(g)$)"      , x = 5 , y = 8 , node_type = "Individual", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "R2", label = r"($R_{2}(g)$)" , x = 6 , y = 2 , node_type = "Community", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "T2", label = r"($T_{2}(g)$)"      , x = 7 , y = 4 , node_type = "Community", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "M2", label = r"($M_{2}(g)$)"      , x = 8 , y = 6 , node_type = "Individual", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "V2", label = r"($V_{2}(g)$)"      , x = 9 , y = 8 , node_type = "Individual", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "R3", label = r"($R_{3}(g)$)" , x = 10 , y = 2, node_type = "Community", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "T3", label = r"($T_{3}(g)$)"      , x = 11 , y = 4, node_type = "Community", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "M3", label = r"($M_{3}(g)$)"      , x = 12 , y = 6, node_type = "Individual", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "V3", label = r"($V_{3}(g)$)"      , x = 13 , y = 8, node_type = "Individual", node_shape = "covariate")
list_nodes[[length(list_nodes) + 1]] <- data.frame(name = "R4", label = r"($R_{4}(g)$)" , x = 14 , y = 2, node_type = "Community", node_shape = "covariate")

list_edges <- list()
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V0", to = "R1", edge_label = r"($g$)")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "R1", to = "T1", edge_label = r"()")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "T1", to = "M1", edge_label = r"()")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "M1", to = "V1", edge_label = r"()")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "R2", to = "T2", edge_label = r"()")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "T2", to = "M2", edge_label = r"()")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "M2", to = "V2", edge_label = r"()")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "R3", to = "T3", edge_label = r"()")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "T3", to = "M3", edge_label = r"()")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "M3", to = "V3", edge_label = r"()")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V1", to = "R2", edge_label = r"($g$)")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V2", to = "R3", edge_label = r"($g$)")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "M1", to = "M2", edge_label = r"()")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "M2", to = "M3", edge_label = r"()")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V1", to = "M2", edge_label = r"()")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V2", to = "M3", edge_label = r"()")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V3", to = "R4", edge_label = r"()")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V0", to = "V1", edge_label = r"()")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V1", to = "V2", edge_label = r"()")
list_edges[[length(list_edges) + 1]] <- data.frame(from = "V2", to = "V3", edge_label = r"()")


structural_nodes <- list_nodes |> dplyr::bind_rows() |> dplyr::mutate(label = latex2exp::TeX(label, output = "character", bold = TRUE))
structural_edges <- list_edges |> dplyr::bind_rows() 


tidygraph::tbl_graph(nodes = structural_nodes, edges = structural_edges) |>
  plot_swig(node_radius = 0.5, nudge_intervention_labels = 0.2) +
  ggplot2::theme(
    plot.margin = ggplot2::margin(10, 10, 10, 10),
    legend.position = "none"
  ) +
  scale_fill_mpxnyc(option = "light")



```



