```{r}

# Access custom defined functions
targets::tar_source("../R_functions")

```

### Example 2: Marriage, Wealth, Dress, Jobs {.unnumbered}

We mentioned that in our study sample, Person 1 and Person 2 are married to each other, and Person 1 and Person 3 are new colelagues. In the causal system connecting study participants wealth with their dress and their job opportunities, an argument could be made that Person 1's wealth affects Person 2's dress, since they pool their individually held wealth. It could also be argued that Person 1's wealth affects Person 2's job opportunities if wealth brings the married couple into contact with other couples who are connected to job markets. Finally, we could argue that Person 1's dress affects Person 2's job opportunities if some aspect of the reputation Person 2 enjoys in their job market derives from Person 1's status in that market. The argument is symmetric, Person 2 could also potentially affect Person 1 in the same ways. 

What about the relationship between Person 1 and Person 3? How does that shape the measuresments of either person? We can imagine that the wealth and dress of a newly acquainted colleague would have no bearing at all on the dress and job opportunities of her colleague. Whereas Person 1 and Person 2 are connected in DAG [], Person 1 and Person 3 are not because their relationship is irrelevant to the causal system under investigation. Person 2 and Person 3 do not affect each other since they have no relationship at all. 