
```{r}
targets::tar_source("R_functions")
```

## SSNAC components

The SSNAC framework is an approach to collecting, analyzing and interpreting data which explicitly accounts for relationships among people, the places they physical places they interact in or co-inhabit. 

It is applicable in two situations: when investigators want to describe the patterns in the relations among people, places, and across people and places; or when investigators are interested in inferring causality in the context of the system formed by people and places.

For the descriptive interest, it is necessary to have data on individuals, the physical spatial units they co-inhabit, relationships among individuals (network data), as well as the relationships among spatial units (spatial weights matrix). 

For the causal interest, it is necessary for the investigator should have the data mentioned above, as well as a theory or set of theories about the causal process under investigation. These theories must explicitly state:

-   the meaning of nodes (which entities they represent)

-   the meaning of ties (how they relate the entities they link)

-   an understanding of which ties are relevant to the causal question under investigation