

##### Place graph {.unnumbered}

The RESPND-MI/MPX NYC place graph has community districts as nodes. A pair of community districts is connected by a weighted edge when at least one participant has a residence or attended a gathering in both community districts. The weight of the edge is the count of participants who are shared by the two community districts. 

```{r}
#| fig-cap: Sample place network visualization
#| label: fig-example-community
#| fig-width: 8
#| fig-height: 4
  

make_example_network_data("places") |>
  plot_example_projection_network() +
  theme_mpxnyc_blank(legend.position = "right") +
  ggplot2::scale_size_manual(name = "Node type", values = c(10)) +
  scale_color_mpxnyc(name = "Node type", option = "dark_blue") +
  ggraph::scale_edge_width_manual(name = "Weight", values = c(1,2,3))

```



```{r include=FALSE}
#| tbl-cap: Sample place network data
#| label: tbl-example-place-nodes
#| layout-ncol: 2
#| tbl-subcap:
#|  - "Nodes"
#|  - "Edges"


make_example_network_data("places") |>
  data.frame() |>
  dplyr::transmute(Name = label, Type = ifelse(type, "Person", "Community District")) |>
  gt::gt()

make_example_network_data("places") |>
  dplyr::mutate(name = label, type, age) |>
  tidygraph::activate(edges) |>
  dplyr::mutate(from_name = tidygraph::.N()$name[from], to_name = tidygraph::.N()$name[to]) |>
  data.frame() |>
  dplyr::arrange(from, to) |>
  dplyr::transmute(From = from_name, To = to_name, Weight = weight) |>
  gt::gt()


```






