
## Example: Rapid research response {.unnumbered}

You are town epidemiologist live in a town of 8000 people who live and work across 5 communities within the town. There is news of a novel human transmitted infection coming to the town. You decide to map the spatial and sexual networks of the towns peopple to prepare for a response to the new infection. You take a random sample of 8 townspeople to conduct survey research. Participants were selected independently of each other and all invited participants accepted the invitation


{{< include fig-example-person-place-network.qmd >}}


@fig-example-person-place-network shows a simplified data graph.
Community district nodes are shown in blue and survey participant nodes
in pink. Each edge connects one community district with one survey
participant. Three kinds of edges are shown – those that indicate either
that the survey participant has a home in the community district, or
that they attended a gathering sexual contact or attended a gathering
without sexual contact in the community district. For instance,
*Participant 3* has a home in *Community District B*, he attended a
gathering with no sexual contact in *Community District A*, and he
attended two gathering (one sexual and one non-sexual) in *Community
District E*.