
##### Person-place graph {.unnumbered}


```{r}
#| fig-cap: Sample person-place network visualization
#| label: fig-example-participant-place
#| fig-width: 8
#| fig-height: 5


make_example_network_data("bipartite") |>
  plot_example_bipartite_network() +
  scale_color_mpxnyc(name = "Node type", option = "dark") +
  ggplot2::labs(fill = "Node type") +
  ggplot2::scale_size_manual(name = "Node type", values = c(7,10)) +
  theme_mpxnyc_blank(
    plot.margin = ggplot2::margin(0,0,0,0),
    legend.position = "bottom"
    ) 



```


The RESPND-MI/MPX NYC person-place graph is a data graph that contains all collected data. We define the person-place graph as an ordered pair with the first entry a set of node labels $\mathscr{N}$, and an adjacency function $\psi$. There are two types of nodes: community districts $\mathscr{N}_C$ and survey participants $\mathscr{N}_P$. 


$$
\mathscr{G}(\mathscr{N}, \psi)
$$


An adjacency function for this graph is a function that takes the label for a pair of nodes, and returns a value indicating the strength of the edge between those nodes. In unweighted networks, the strength of a tie is either zero, meaning the pair of nodes is not connected, or 1, meaning it is. Define $\psi(i,j)$ as the adjacency function for the RESPND-MI/MPX NYC person-place graph. Then for person $i$ and community $j$:


$$
\psi(i,j) = \text{count of gatherings/homes participant } i  \text{ has in community } j
$$

Edges can only exist between a participant and a community district - they indicate that the person either lives in or attended a gathering in that community district. i.e.: 


$$
i,j \in \mathscr{N}_P \text{ or } i,j \in \mathscr{N}_C \implies \psi(i,j) = 0
$$