



## Statistical inference

Main idea is: 

- You have some observational nodes that are people 

- You have some observational nodes are are places  

- People have affiliations with places 

- Affiliations are unlimited 

- If a place is a neighborhood, a person node could be affiliated to that place because they have a home there. They could additionally be affiliated to that place because they have attended a gathering there. 

- If a place is a household, a person could be affiliated to the household because they work in the househodl or because they have a friend there, or because they live there.  

- There are quantitative data associated with the people, places and affiliations

- Data are a realization of law $C_t \in M_{n\times 1}$, $\Psi_t \in M_{n\times n}$, and $Q_t \in M_{n^2 \times 1}$ for $t \in [1,k]$, $k \in \mathbf{Z}$ and arbitrarily large $n \in \mathbf{Z}$
- Goal is to infer population parameters using a sample.
  - We begin by defining a variable $\mathbf{s} \in M_{n\times 1}$ such that $s_i$, the selection indicator for $i^{th}$ observational unit is one when that unit is included in the sample, and zero otherwise
    - We make independence and homogeneity assumptions 
    - We make assumptions about the determinants of $\mathbf{s}$
  -  we only see this when $s_i = 1$: $C_{ti}$ 
  - we only see this when $s_i = 1$ and $s_j = 1$ : $\Psi(i,j)$ 
    
- Queston for the researcher:
  - Are there estimators that you want to prioritize showing? A class? A specific measure?
  - Are you willing to read non-parametric efficiency theory to write this section?
  - With that in mind, how much effort should you spend on the statistical inference section?
  - What will the statistical inference section buy the reader?
  - General enough to cover and extend dissertation household setup?
  - Can i trust proportion of edge characteristic d?
  
- We are interested in population quantities:

  - Node characteristics $m(C, \theta)$ 
  
  - Edge characteristics $m(Q, \theta)$
  
  - Edge formation process $m(\Psi, \theta)$
  
  - Combinations of characteristics $m(C, Q, \Psi, \theta)$
  
- We estimate these based on a random sample of person nodes

  - Node characteristics $m(\hat C, \theta)$ 
  
  - Edge characteristics $m(\hat Q, \theta)$
  
  - Edge formation process $m(\hat \Psi, \theta)$
  
  - Combinations of characteristics $m(\hat C, \hat Q, \hat \Psi, \theta)$

- We estabilsh assumptions for:

  - unbiasedness of estimators
  
  - efficiency bounds

  
- We use the bootstrap to estimate the standard error and use these to estimate confidence intervals

