
## Example: Rapid research response {.unnumbered}

You are town epidemiologist in a town of 8000 people who live and work across 5 communities. You hear news of a novel human transmitted infection coming to the town. You decide to map the spatial and sexual networks of the townspeople to prepare for a response to the new infection. You take a random sample of 8 townspeople to conduct survey research. Participants are selected independently of each other accept or decline the invitation independently of each other. 

You ask each participant to identify the community they live in, and the communities they have had physical or sexual contact in. 

{{< include fig-example-person-place-network.qmd >}}


@fig-example-person-place-network is a data graph showing collected data.
Community district nodes are shown in blue and survey participant nodes
in pink. Each edge connects one community district with one survey
participant. Three kinds of edges are shown – those that indicate either
that the survey participant has a home in the community district, or
that they attended a gathering with sexual contact or attended a gathering
without sexual contact in the community district. For instance,
*Participant 3* has a home in *Community District B*, he attended a
gathering with no sexual contact in *Community District A*, and he
attended two gathering (one sexual and one non-sexual) in *Community
District E*.

In this appendix, we outline an analysis of these data from the perspectives of: node characteristics, edge characteristics, local network structure, global network structure, and finally network dynamics. 

