### Network FFRCISTG model {.unnumbered}

::: {.aside}
To articulate homogeneity restrictions in the sections below, we draw on the work of @aronow2017 on exposure mappings.
:::

Say we have a FFRCISTG with $f_{Y_i}$ the structural equation for $Y_i$, and $U_{Y_i}$ the error term for that equation. Measures $\mathbf{X}_t \in \{0,1\}^n, t \in [1,K]$ precede $Y_i$. And say we have graph $\mathscr{G}(\mathscr{N}, \psi)$ with set $\mathscr{N}$ containing $n$ nodes, and adjacency function $\psi(i,j)$ which gives the weight between nodes $i$ and $j$. Weights are positive real numbers when nodes are connected in $\mathscr{G}$ and zero otherwise.

::: {#def-network-exposure-units .theorem}
# Network exposure units
The network exposure units for node $i$ in graph $\mathscr{G}(\mathscr{N}, \psi)$ are given by:

$$
\mathscr{N_i} = \{j \in \mathscr{N}: \psi(i, j) > 0\}
$$

:::


::: {#def-network-weights-vectors .theorem}
# Network weights vector
The network weights vector for node $i$ in graph $\mathscr{G}(\mathscr{N}, \psi)$ is defined:

$$
\Psi_i = [\psi(i,1), \psi(i,2), ..., \psi(i,n) ]^T
$$
:::





::: {#def-exposuremapping .theorem}
# Exposure mapping

The exposure mapping for $Y_i$ is a function $g_i() \in \mathbf{R}^{2K}$ such that:

$$
Y_i = f_{Y_i}(g_i(\mathbf{X}_1,  ..., \mathbf{X}_K), U_{Y_i})
$$
:::




::: {#def-separability .theorem}
# Separability

We say exposure mapping $g_i$ is separable if

$$
g_i(\mathbf{X}_{1}, ..., \mathbf{X}_{K}) = [g_0,    g_{1i}(\mathbf{X}_{1}), ...,   g_{Ki}(\mathbf{X}_{K})]^T
$$

where $g_0 = [X_{1i}, ..., X_{Ki}]^T$ and $g_{ti}() \in \mathbf{R}$. We call the functions $g_{ti}$ component functions of exposure mapping $g_i$.

:::



::: {#def-loyalty .theorem}
## Loyalty

We say a component function $g_{ti}$ is loyal to graph $\mathscr{G}$ if for $\mathbf{X},\mathbf{X}' \in \{0,1\}^n$

:::: {.aside}
**Some notation**: $X_i$ is the $i^{th}$ entry of vector $\mathbf{X}$ and $\mathbf{X}_{\mathscr{N_i}}$ is the sub-vector of $\mathbf{X}$ which contains entries related to person $i$'s network exposure units. Where the original vector already has a subscript, we append these symbols to that subscript. 
::::



$$
\begin{equation}
\mathbf{X}_{t\mathscr{N}_i} = \mathbf{X'}_{t\mathscr{N}_i}
\implies 
g_{ti}(\mathbf{X}) = g_{ti}( \mathbf{X'}) 
\end{equation}
$$
:::




::: {#def-invariance .theorem}
## Positional invariance

We say component functions $g_{ti}$ are positionally invariant if for $i,j \in \mathscr{N}$, $\mathbf{X},\mathbf{X}' \in \{0,1\}^n$ and conformable permutation matrix $\mathbf{M}$:

$$
\begin{equation}
\mathbf{X}_{\mathscr{N}_i} = \mathbf{M} \mathbf{X'}_{\mathscr{N}_j} \text{ and } \Psi_{i\mathscr{N}_i} =  \mathbf{M} \Psi_{j\mathscr{N}_j}\\
\implies \\
g_{ti}(\mathbf{X}) = g_{tj}(\mathbf{X'}) 
\end{equation}
$$
:::

:::: {.aside}
A **permutation matrix** is a square matrix whose row and column margins all equal 1 and whose entries are either zero or one. Pre-multiplying a vector with a conformable permutation matrix permutes the order of the entries in the vector.
::::


::: {#def-exposuremaping .theorem}
# Network exposure mapping/value

If functions $g_{ti}$ are positionally invariant with respect to $\mathscr{G}$ we say $g_{ti}$ is a "network exposure mapping for $\mathbf{Y}$ with respect to $\mathbf{X}$ in $\mathscr{G}$". The value of the function is called the "network exposure value for $Y_i$ with respect to $\mathbf{X}$ in $\mathscr{G}$". Furthermore,

$$
g_{ti}(\mathbf{X}) = g_{t}(\mathbf{X}, \Psi_i)
$$
:::




::: {#def-boundedness .theorem}
# Boundedness

We say that a network exposure mapping $g_{t}$ is bounded if for all $\mathbf{X} \in \{0,1\}^n, \mathbf{W} \in \mathbf{R}^n_+$ all possible network exposure values are contained by a finite set $\mathbf{D}$. i.e.: 

:::: {.aside}

The assumption of **boundedness** can obtain in three different ways. It could be as a result of restrictions on the structure of the graph. For example, if the only relationships of interest between individual participants were marriages, each node would have a degree of either 0 or 1, meaning the count of alters with $X_{tj} = 1, j \in \mathscr{N}_i$ is either zero or one.

It might obtain via restrictions on the value of $\mathbf{X}$ itself. It might be the case, for instance, that the count of $i$'s for which $X_{ti}=1$ is very low so that on average, the count of alters for which $X_{tj} = 1, j \in N_i$ will also be low.

Finally, boundedness could obtain as a result of the functional form of $g$ itself. This might happen if $g$ models a network exposure which has a ceiling effect in its dose-response curve with the outcome of interest. For example, if $X$ indicates ownership of a car, and $\mathscr{G}$ encodes close friendships, $g$ would be a network exposure mapping which tells us how each additional friend who has a car shifts the outcome of interest. For most health applications, its likely that beyond some number of friends who have a car, an additional friend who gets a car will not change the outcome.

::::

$$
g_t(\mathbf{X}, \mathbf{W})  \in \mathbf{D} 
$$

with $|\mathbf{D}| < c \in \mathbf{R}$ where $c$ is not a function of the number of interconnected units in graph $\mathscr{G}$.



:::



::: {#def-nffrcistg .theorem}
# Network FFRCISTG

A NFFRCISTG is a FFRCISTG associated with a graph. Each node in the graph represents an observational unit in the FFRCISTG. A network tie indicates a pair of observational units whose measures are causes of each other. All the structural equations in this model have exposure mappings which are separable with well-defined and bounded network exposure mappings and independent errors.

:::






