```{r  include=FALSE}
targets::tar_source("../R_functions")
```

# SSNAC II: Causality {#sec-causal-interpretation}

::: {#leading}
We summarize the leading approach to causal inference in epidemiologic studies, extending that approach to accommodate data which are characterized by complex patterns of interdependence. 
:::


::: {#acknowledgements}
[Acknowledgements]{.underline}: The statistical framework for SSNAC was first presented at the Society for Epidemiologic Research Meeting (Boston, June 2025) at a workshop titled "Single World Intervention Graphs (SWIGs) for the practicing epidemiologist" organized and taught by Aaron Sarvet (University of Massachusetts), Mats J. Stensrud (École polytechnique fédérale de Lausanne), and Kerollos Wanis (University of Texas), and also taught by Keletso Makofane (Ctrl+F), James M. Robins (Harvard University), and Thomas Richardson (University of Washington).

[Lead author]{.underline}: Keletso Makofane, MPH, PhD. [Editor]{.underline}: Nicholas Diamond, MPH. (Published: June 2025).
:::

```{r}
#| fig-width: 2
#| fig-height: 2
#| fig-align: center


plot_icon(icon_name = "droplets", color = "dark_purple", shape = 0)

```



















{{< include B_0__preface.qmd >}} 
{{< include B_1__classical_causal_inference.qmd >}} 
{{< include B_2__network_causal_inference.qmd >}} 
{{< include B_3__ssnac.qmd >}} 
{{< include B_4__control_intervention.qmd >}}

