#### Example 3: Vaccination {#sec-example-3 .unnumbered}

You are a public health officer at the department of health in Nowhereville and are planning to conduct and assess a three week flu vaccination campaign. None of the townspeople have been vaccinated against flu. There is a population of five residents in the city, and they each live in one of three neighborhoods. In addition, residents visit their friends' homes in other neighborhoods.

At time 0, *Person 1* lives in *Neighborhood A* and visits *Neighborhood B*. *Person 2* lives in *Neighborhood B*, but visits *Neighborhoods A* and *B*. *Person 3* lives in *Neighborhood C* and visits *Neighborhood B*. *Persons 5* and *6* live in *Neighborhood C* and they do not visit any other neighborhoods. At the beginning of each week, before any public health activities, resident of Nowhereville has the opportunity to change the neighborhoods they live in and visit. 

The city of Nowhereville has a very structured approach to vaccination campaigns. At the beginning of each week, each neighborhood gets a risk rating based on the prevalence of vaccination among its residents and visitors. Based on that rating, each neighborhood decides whether to conduct a local vaccination drive or not. Vaccination drives are conducted in the same way regardless of neighborhood - visitors and residents are offered immediate vaccination at a nearby mobile van through a pop-up message on the local dating app. Not everyone will receive the messages because some will not open the app during the period of the campaign. Those who do will have the choice of getting vaccinated or not. Each person can only get vaccinated once.

In this section of the appendix, we extend the NFFRCISTG model described in @sec-network-causal-inference by allowing for the possibility of including two types observational units (people and places), and allowing the relationships between people and places to be randomly generated by the causal model, and assuming homogenous network spillover with respect to the resulting random network. We name this the bipartite random network FFRCISTG model (BRNFFRCISTG) -- a causal model which includes one or more "network generators" - structural equations which model the network edges as random variables. 

First we introduce tools to mirror the shift we advocate from thinking about statistical inference as the task of inferring something about a probability distribution based on a growing number of realizations to thinking about the task as that of inferring something about the distribution of a growing vector of realizations: the DANG and SWING.

