### {.unnumbered}

We used data from RESPND-MI to assess the effectiveness of two approaches to conducting mass vaccination campaigns quickly. MPX NYC is an online survey of about 1300 individuals that was conducted in 2022 in New York City. Study participants were asked to indicate their home on a map and were asked to indicate places they had had social contact in a congregate setting. Spatial coordinates were converted into community district identifiers. Community districts spatially partition the city of New York.

Under the SSNAC framework, our intervention of interest might not be about setting the value of any particular variable, but setting a policy or a process that produces a set of variables in the causal model. This would be done by changing the structural equations which produce those variables. In the SWING shown in @fig-edge-intervention-swing and @eq-edge-intervention-swing, we show an intervention which replaces the function for the risk rating for each community ($\mathbf{R}$) with the function $h$. Every variable that is downstream of the first variable created using $h$ is marked with a superscript $(h)$ to show that it is partially determined by that function.

We can now ask what the impact of taking policy $h$ would be on the decision whether or not to vaccinate a neighborhood $j$ at time $s$ ($T_{js}$). We can also ask what the impact of the policy is on the the exposure of participant $i$ to the campaign message at time $s$ ($M_{is}$). 

Our interest in RESPND-MI, however, was initially to provide evidence to inform a targeted vaccination campaign, so the main outcomes of interest are the vaccination status of each individual $i$ at time $s$ ($V^{(h)}_{is}$). We were interested in contrasting two approaches to assigning risk-ratings to community districts: the contact-neutralizing approach and the movement-neutralizing approach.

Whereas the contact-neutralizing approach ranks community districts by how many individuals are connected to them, the movement-neutralizing approach ranks community districts by how centrally they are connected to other community districts through the exchange of individuals.