### a. Definitions {.unnumbered}

#### Classic causal inference








::: {#def-statistical-model .theorem}
## Statistical model

A statistical model is a collection of probability distributions on a set of random variables.

$$
\mathcal{M}=\{P_\theta:\theta\in\Theta\}\quad\text{on set of random variables }\mathbf V.
$$
:::

::: {#def-npsem .theorem}
## NPSEM

A nonparametric structural equation model with independent errors (NPSEM-IE) is a [statistical model](#def-statistical-model) in which each random variable is as deterministic function (defined by a structural equation) of other variables along with an error term. 

$$
\mathscr M=\{f_{j}:V_j\in\mathbf V\}
$$
where 

$$
V_{j} \;=\; f_{j}\!\big( V_{1},\dots,V_{j-1},\, U_{j} \big),
$$

:::

::: {#def-npsem-ie .theorem}
## NPSEM-IE

A nonparametric structural equation model with independent errors (NPSEM-IE) is an [NPSEM](#def-npsem) in which all error terms are indpendent. 


$$
V_{j} \;=\; f_{j}\!\big( V_{1},\dots,V_{j-1},\, U_{j} \big),
$$

$$
\{U_j\}_{V_j \in \mathbf V} \ \text{ mutually independent.}
$$
:::

::: {#def-parent-child .theorem}
## Parent

In an [NPSEM-IE](#def-npsem-ie), if variable $X$ appears in the structural equation for $Y$, then $X$ is a parent of $Y$ and $Y$. The set of parents for $X$ is denoted $\mathbf{Pa}(X)$.

:::


::: {#def-observational-unit .theorem}
## Observational unit

An observational unit is a subset of the random variables in a [statistical model](#def-statistical-model) that originate from the same data source. The collection of observational units forms a partition of the full set of random variables. 

Given a set of variables $\mathbf V_i$ an observational unit is a set $\mathbf V$ such that:

$$
\mathbf V=\bigcup_{i=1}^n \mathbf V_i,\qquad \mathbf V_i\cap \mathbf V_j=\varnothing\ (i\ne j).
$$
:::

::: {#def-equivalence .theorem}
## Equivalence

Two random variables are equivalent if they belong to different [observational units](#def-observational-unit) but represent the same construct. 

$$
X_i\sim X_j\iff i\ne j;\ X_i\in \mathbf V_i;\ X_j\in \mathbf V_j,\ X_i, X_j \text{ represent same construct}.
$$
Two sets of random variables are equivalent if each element in one set has an equivalent in the other set.


:::










::: {#def-no-spillover .theorem}
## No spillover assumption

In an [NPSEM-IE](#def-npsem-ie), the *no spillover* assumption requires that no variable is a [parent](#def-parent-child) of an [equivalent](#def-equivalence) variable in another [observational unit](#def-observational-unit).

$$
X\notin \mathbf{Pa}(X')\quad
\forall\, X\sim X',\ X\in \mathbf V_i,\ X'\in \mathbf V_j,\ i\ne j.
$$
:::

::: {#def-no-interference .theorem}
## No interference assumption

In an [NPSEM-IE](#def-npsem-ie), the *no interference* assumption requires that no variable is a [parent](#def-parent-child) of any non-[equivalent](#def-equivalence) variable in another [observational unit](#def-observational-unit).

$$
X\notin \mathbf{Pa}(Y)\quad
\forall\, X\in \mathbf V_i,\ Y\in \mathbf V_j,\ i\ne j,\ X\not\sim Y.
$$
:::

::: {#def-identical-distributions .theorem}
## Identical distributions assumption

In an [NPSEM-IE](#def-npsem-ie), the *identical distributions* assumption requires that [equivalent](#def-equivalence) variables have identical structural equations.

$$
X_i\sim X_j\Rightarrow f_{X_i}=f_{X_j}.
$$
:::



::: {#def-intervention-regime .theorem}
## Intervention regime

A set of deterministic functions called interventional structural equations which are defined in relation to $\mathbf{E} \subset \mathbf V$ is the subset of the random variables whose structural equations are to be intervened upon. Each interventional structrual equation must have the same domain and range as the structural equation it is to replace. 

$$
\Gamma = \{ h_V  : V \in \mathbf \mathbf{E} \text{ such that } h_V, f_V \text{ have identical arguments}\}
$$


:::




::: {#def-counterfactual-npsem .theorem}
# Counterfactual NPSEM-IE

Given intervention regime $\Gamma$ and NPSEM-IE $\mathscr{M}$, the counterfactual NPSEM-IE is defined


$$
\mathscr{M}^{(\Gamma)} =  \{f_V^{(\Gamma)}: V \in \mathbf V \}
$$

Where 

$$
f_V^{(\Gamma)} = \begin{cases}
  h_V & \text{if}  & V \in \mathbf E\\
  f_V & \text{otherwise}
\end{cases}
$$


:::



::: {#def-causal-model .theorem}
## Causal model

A causal model $\mathscr{C}$ is a statistical model combining an NPSEM-IE $\mathscr{M}$ with its related counterfactual NPSEM-IEs $\{\mathscr{M}^{(\Gamma)}\}_{\Gamma \in \mathscr{A}}$ defined in relation to a set of intervention regimes $\mathscr{A}$. 

$$
\mathscr{C} = \mathscr{M} \cup \{\mathscr{M}^{(\Gamma)}\}_{\Gamma \in \mathscr{A}} 
$$
The random variables included in the model include two subsets - observed random variables 

$$
\mathbf V^\mathscr{C} = \mathbf V \cup \{\mathbf V^{(\Gamma)}\}_{\Gamma \in \mathbf E}
$$

where $V \in \mathbf V$ is defined
$$
V  \;=\; f_V\big( \mathbf{Pa}(V), U_V \big)
$$

$$
 \{U_V\}_{V \in \mathbf V} \ \text{ mutually independent.}
$$
and for each $\Gamma \in \mathbf E$, $V^{(\Gamma)} \in\mathbf V^{(\Gamma)}$ is defined

$$
V^{(\Gamma)}  \;=\; f_V^{(\Gamma)}\big( \mathbf{Pa}(V)^{(\Gamma)}, U_V \big)
$$

By assumption, the error term for each counterfactual random variable is equal to the error term in the corresponding observed variable. 







:::

::: {#def-ffrcistg .theorem}
## FFRCISTG model

A finest fully randomized causally interpretable structured tree graph (FFRCISTG) model is a causal model that satisfies the (1) [no spillover](#def-no-spillover), (2) [no interference](#def-no-interference), and (3) [identical distributions](#def-identical-distributions) assumptions. 


:::

#### Network causal inference


::: {#def-graph .theorem}
## Graph

A *[graph](#def-graph)* is an ordered pair $\mathscr{G} = (\mathcal{N}, \psi)$ with nodeset $\mathcal{N}$and adjacency function $\psi$ which assigns a nonnegative weight to each unordered pair of nodes $(i,j)$. 

$$
\mathscr G=(\mathcal N,\psi),\qquad
\psi:\mathcal N\times\mathcal N\to \mathbb R_{\ge 0},\qquad
\psi(i,j)=\psi(j,i)
$$

Nodes $i,j \in \mathcal{N}$ are connected if and only if $\psi(i,j) > 0$.
:::


::: {#def-neighborhood .theorem}
## Neighborhood

Given a [graph](#def-graph) $\mathscr{G} = (\mathcal{N}, \psi)$, the *[neighborhood](#def-neighborhood)* of a node $i \in \mathcal{N}$ is

$$
\mathcal{N}_i = \{ j \in \mathcal{N} : \psi(i,j) > 0 \}.
$$
:::

::: {#def-network-weights-vector .theorem}
## Network weights 

Given a [graph](#def-graph) $\mathscr{G} = (\mathcal{N}, \psi)$, the *[network weights vector](#def-network-weights-vector)* for a node $i \in \mathcal{N}$ is

$$
\Psi_i = [\psi(i,1), \dots, \psi(i,n)]^T,
\qquad n=|\mathcal N|.
$$
:::

::: {#def-network-values .theorem}
## Network values 

Given a [graph](#def-graph) $\mathscr{G} = (\mathcal{N}, \psi)$ with [neighborhood](#def-neighborhood) $\mathcal N_i$ for each node $i$, and given a vector $\mathbf X \in \{0,1\}^n$ indexed by nodes in $\mathscr{N}$, the *network values* for $i$ with respect to  $\mathbf X$ is the subvector of $\mathbf X$ indexed by $\mathscr{N}_i$.

$$
\mathbf X_{\mathcal N_i}=\big(X_j\big)_{j\in \mathcal N_i}.
$$
:::

::: {#def-exposure-mapping .theorem}
## Exposure mapping

Given an [NPSEM-IE](#def-npsem-ie) with $f_{Y_i}$ the [structural equation](#def-npsem-ie) for $Y_i$, and $\mathbf{X}_1,\dots,\mathbf{X}_K \in \{0,1\}^n$ the [parents](#def-parent-child) of $Y_i$, the exposure mapping for $f_{Y_i}$* is a function

$$
g_i : \{0,1\}^{K \times n} \to \mathbb{R}^m
$$

such that

$$
Y_i = f_{Y_i}\big(g_i(\mathbf{X}_1,\dots,\mathbf{X}_K), U_{Y_i}\big).
$$
:::

::: {#def-separability .theorem}
## Separability

An [exposure mapping](#def-exposure-mapping) $g_i$ is *[separable](#def-separability)* if it can be written:

$$
g_i(\mathbf{X}_1,\dots,\mathbf{X}_K) 
  = \big[ \begin{pmatrix} X_{1i} \\ \dots \\ X_{Ki} \end{pmatrix},\, g_{1i}(\mathbf{X}_1),\, \dots,\, g_{Ki}(\mathbf{X}_K)\big]^T,
$$

where each $g_{ti} : \{0,1\}^n \to \mathbb{R}$ is a *component function* of $g_i$. 

A structural equation is said to be separable if its exposure mapping is separable. 
:::



::: {#def-positional-invariance .theorem}
## Positional invariance
Let $\mathcal{N}_{ti}$ denote the [neighborhood](#def-neighborhood) of node $i$ in [graph](#def-graph) $\mathscr{G}_t = (\mathcal{N}, \psi_t)$. A [component function](#def-separability) $g_{ti}$ is *[positionally invariant](#def-positional-invariance)* with respect to $\mathscr{G}_t$ if for all $\mathbf{X}, \mathbf{X}' \in \{0,1\}^n$


$$
\mathbf{X}_{\mathcal{N}_i} = \mathbf{M}\mathbf{X}'_{\mathcal{N}_j}, 
\quad 
\Psi_{i,\mathcal{N}_i} = \mathbf{M}\Psi_{j,\mathcal{N}_j}
\Rightarrow
g_{ti}(\mathbf{X}) = g_{tj}(\mathbf{X}').
$$

An exposure mapping shows positional invariance with respect to  $\{\mathscr{G}_t\}_{t \in [1:K]}$ if it is separable and all its component functions show positional invariance with respect to an element of  $\{\mathscr{G}_t\}_{t \in [1:K]}$. A structural equation is positionally invariant if its exposure mapping is positionally invariant. 
:::

::: {#def-boundedness .theorem}
## Boundedness

A [component function](#def-separability) $g_{ti}$ is *[bounded](#def-boundedness)* if there exists a finite set $\mathcal{D} \subset \mathbb{R}$ and a constant $c \in \mathbb{R}$, independent of the size of the network $|\mathcal{N}|$, such that for $\mathbf{X} \in \{0,1\}^n$

$$
g_{ti}(\mathbf{X}) \in \mathcal{D} \quad \text{ for }|\mathcal{D}|< c \in \mathbb{Z}.
$$

An exposure mapping is bounded if it is [separable](#def-separability) and all its component functions are bounded. 
:::

::: {#def-network-exposure-mapping .theorem}
## Network exposure mapping

A network exposure mapping with respect to [graph](#def-graph) $\mathscr{G}_t$  is defined as a [component function](#def-separability) which is [bounded](#def-boundedness) and [positionally invariant](#def-positional-invariance) with respect to  $\mathscr{G}_t$. 

:::

::: {#def-homogeneous-network-interference .theorem}
## Homogeneous network interference

An exposure mapping exhibits homogeneous network interference with respect to a [graph set](#def-graph) $\{\mathscr{G}_t\}_{t \in [1:K]}$ if it is separable and all its [component functions](#def-separability) are [network exposure mappings](#def-network-exposure-mapping). An NPSEM-IE exhibiits homogenous network interference if all its exposure mappings exhibit homogenous network interference. 

:::



::: {#def-network-ffrcistg .theorem}
##  NFFRCISTG model

A network finest fully randomized causally interpretable structured tree graph (NFFRCISTG) model is a causal model which satisfies the (1) [no spillover](#def-no-spillover), (2) [homogenous network interference](#def-no-interference) with respect to $\{\mathscr{G}_t\}_{t \in [1:K]}$, and (3) [identical distributions](#def-identical-distributions) assumptions. 


:::

#### Social and spatial inference


::: {#def-graph-generator .theorem}
# Random graph generator

In an NPSEM, a random edge generator $\psi$ is an $n \times n$ function whose entries $\psi(i,j)$ are each a deterministic function of the other variables in the model along with an error term. 


$$
\psi(i,j) = f_{\psi_{ij}}(\mathbf{Pa}(\psi(i,j)), U_{\psi_{ij}})
$$
To ensure that $\psi(i,j) = \psi(j,i)$ we define

$$
U_{\psi_{ij}} = U_{\psi_{ji}}
$$


:::

::: {#def-random-graph-npsem .theorem}
## Random graph NPSEM

A random graph NPSEM is an NPSEM which includes random graph generators among the structural equations. It has two parts -- the structural part which contains all the structural equations which are not graph generators, and the relationsal part which contains random graph generators.

The error terms of the structural part are mutually independent. In the relational part, error terms accross graph generators are independent. 

:::

::: {#def-homogenous-random-network-interference .theorem}
# Homogenous random network interference

An exposure mapping exhibits homogeneous random network interference with respect to a [random graph set](#def-random-graph) $\{\psi_t\}_{t \in [1:K]}$ if it is separable and all its [component functions](#def-separability) are [network exposure mappings](#def-network-exposure-mapping). An NPSEM-IE exhibiits homogenous random network interference if all its exposure mappings exhibit homogenous randomn network interference. 

:::


::: {#def-social-spatial-ffrcistg .theorem}
## RNFFRCISTG

A random network finest fully randomized causally interpretable structured tree graph (RNFFRCISTG) model is a causal model defined on a [random graph NPSEM-IE](#def-random-graph-npsem ) which satisfies the (1) [no spillover](#def-no-spillover), (2) [homogenous random network interference](#def-homogenous-random-network-interference), and (3) [identical distributions](#def-identical-distributions) assumptions.
:::


::: {#def-random-graph-npsem .theorem}
## Random bipartite graph NPSEM

A random bipartite graph NPSEM is a random graph NPSEM which whose generators produce bipartite graphs. 

 

:::








::: {#def-social-spatial-ffrcistg .theorem}
## BRNFFRCISTG model

A bipartite random network finest fully randomized causally interpretable structured tree graph (BRNFFRCISTG) model is a causal model defined on a [bipartite random graph NPSEM-IE](#def-bipartite-random-graph-npsem ) which satisfies the (1) [no spillover](#def-no-spillover), (2) [homogenous random network interference](#def-homogenous-random-network-interference), and (3) [identical distributions](#def-identical-distributions) assumptions.


:::
