

::: {#def-snffrcistg}
# Social and Spatial Network FFRCISTG model

A social and spatial network finest fully randomized causally interpretable structured tree graph (SSNFFRCISTG) model is a a collection of NPSEM-IE models constructed for the purpose of reasoning quantitatively about the impact of a specified hypothetical intervention. One NPSEM-IE model represents data as they would be observed without intervention, and at least one other NPSEM-IE model represents data as they would be under a specified intervention. 


In a SSNFFRCISTG model, all the NPSEM-IE models show the no spillover, homogenous network interference with respect to a random graph $\mathscr{H}(\mathscr{N}, \mathbf{F})$, and identical distribution assumptions.

- Graph is stochastic and bipartite with:
  - Fixed nodes: a set of nodes representing a set of fixed and known entities
  - Random nodes: a set of nodes, each representing an observational unit in a random sample
  - Random edges: a set of edges, each representing a relation between a random node and fixed node 
  
:::