::: {#def-boundedness .theorem}
# Boundedness

We say that a network exposure mapping $g_{t}$ is bounded if for all $\mathbf{X} \in \{0,1\}^n, \mathbf{W} \in \mathbf{R}^n_+$ all possible network exposure values are contained by a finite set $\mathbf{D}$. i.e.: 

:::: {.aside}

The assumption of **boundedness** can obtain in three different ways. It could be as a result of restrictions on the structure of the graph. For example, if the only relationships of interest between individual participants were marriages, each node would have a degree of either 0 or 1, meaning the count of alters with $X_{tj} = 1, j \in \mathscr{N}_i$ is either zero or one.

It might obtain via restrictions on the value of $\mathbf{X}$ itself. It might be the case, for instance, that the count of $i$'s for which $X_{ti}=1$ is very low so that on average, the count of alters for which $X_{tj} = 1, j \in N_i$ will also be low.

Finally, boundedness could obtain as a result of the functional form of $g$ itself. This might happen if $g$ models a network exposure which has a ceiling effect in its dose-response curve with the outcome of interest. For example, if $X$ indicates ownership of a car, and $\mathscr{G}$ encodes close friendships, $g$ would be a network exposure mapping which tells us how each additional friend who has a car shifts the outcome of interest. For most health applications, its likely that beyond some number of friends who have a car, an additional friend who gets a car will not change the outcome.

::::

$$
g_t(\mathbf{X}, \mathbf{W})  \in \mathbf{D} 
$$

with $|\mathbf{D}| < c \in \mathbf{R}$ where $c$ is not a function of the number of interconnected units in graph $\mathscr{G}$.



:::